= Red Hat OpenShift Container Platform and OKD
:current-version: {page-component-version}

To deploy {longhorn-product-name} on a cluster provisioned with OpenShift 4.x, some additional configurations are required.

NOTE: OKD currently does not support the ARM platform. For more information, see the https://www.okd.io[OKD website] and https://github.com/okd-project/okd/issues/1165[GitHub issue #1165] (_OKD in ARM platform_).

== Installation

=== Install With Helm

Please refer to this section xref:installation-setup/installation/install-using-helm.adoc[Install with Helm] first.

Install Longhorn with the following settings:

|===
| Setting | Value | Example

| `openshift.enabled`
| `true`
| N/A

| `image.openshift.oauthProxy.repository`
| Upstream image
| `quay.io/openshift/origin-oauth-proxy`

| `image.openshift.oauthProxy.tag`
| Version 4.1 or later
| `4.18`
|===

[subs="+attributes",bash]
----
helm install longhorn longhorn/longhorn \
  --namespace longhorn-system \
  --create-namespace \
  --set openshift.enabled=true \
  --set image.openshift.oauthProxy.repository=quay.io/openshift/origin-oauth-proxy \
  --set image.openshift.oauthProxy.tag=4.18
----

=== Install With `oc` Command

Perform the following steps to install Longhorn on [OKD](https://www.okd.io/) clusters.

. Download the `longhorn-okd.yaml` file.
+
----
wget https://raw.githubusercontent.com/longhorn/longhorn/v{{< current-version >}}/deploy/longhorn-okd.yaml
----
+
. Specify the target `oauth-proxy` container image in the `longhorn-okd.yaml` file (for example, `quay.io/openshift/origin-oauth-proxy:4.18`).
+
. Run the following command:
+
[subs="+attributes",shell]
----
oc apply -f longhorn-okd.yaml
----

One way to monitor the progress of the installation is to watch pods being created in the `longhorn-system` namespace:

[subs="+attributes",shell]
----
    oc get pods \
    --namespace longhorn-system \
    --watch
----

For more information, see xref:installation-setup/installation/install-using-kubectl.adoc[Install with Kubectl].

== Prepare A Customized Default Disk (Optional)

To understand more about configuring the disks for {longhorn-product-name}, please refer to the section xref:nodes/default-disk-and-node-config.adoc#_launch_longhorn_with_multiple_disks[Configuring Defaults for Nodes and Disks]

{longhorn-product-name} will use the directory `/var/lib/longhorn` as default storage mount point and that means {longhorn-product-name} uses the root device as the default storage. If you don't want to use the root device as the {longhorn-product-name} storage, set *_defaultSettings.createDefaultDiskLabeledNodes_* true when installing {longhorn-product-name} using Helm:

[,txt]
----
--set defaultSettings.createDefaultDiskLabeledNodes=true
----

And then add another device formatted for {longhorn-product-name}

=== Add An Extra Disk for {longhorn-product-name}

==== Create Filesystem For The Device

Create the filesystem on the device with the label `longhorn` on the storage node. Get into the node by oc command:

[,bash]
----
oc get nodes --no-headers | awk '{print $1}'
oc debug node/${NODE_NAME} -t -- chroot /host bash
----

Check if the device is present and format it with {longhorn-product-name} label:

[,bash]
----
lsblk
sudo mkfs.ext4 -L longhorn /dev/${DEVICE_NAME}
----

==== Mounting The Device On Boot with MachineConfig CRD

The secondary drive needs to be mounted automatically when node boots up by the `MachineConfig` that can be created and deployed by:

[subs="+attributes",bash]
----
cat <<EOF >>auto-mount-machineconfig.yaml
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 71-mount-storage-worker
spec:
  config:
    ignition:
      version: 3.2.0
    systemd:
      units:
        - name: var-mnt-longhorn.mount
          enabled: true
          contents: |
            [Unit]
            Before=local-fs.target
            [Mount]
            # Example mount point, you can change it to where you like for each device.
            Where=/var/mnt/longhorn
            What=/dev/disk/by-label/longhorn
            Options=rw,relatime,discard
            [Install]
            WantedBy=local-fs.target
EOF

oc apply -f auto-mount-machineconfig.yaml
----

==== Label and Annotate The Node

Please refer to the section xref:nodes/default-disk-and-node-config.adoc#_customizing_default_disks_for_new_nodes[Customizing Default Disks for New Nodes] to label and annotate storage node on where your device is by oc commands:

[,bash]
----
oc get nodes --no-headers | awk '{print $1}'

oc annotate node ${NODE_NAME} --overwrite node.longhorn.io/default-disks-config='[{"path":"/var/mnt/longhorn","allowScheduling":true}]'
oc label node ${NODE_NAME} --overwrite node.longhorn.io/create-default-disk=config
----

NOTE: You might need to reboot the node to validate the modified configuration.

== Reference

* https://github.com/longhorn/longhorn/pull/5004[OCP/OKD Documentation and Helm Support]
* https://www.okd.io/[OKD Official Website]
* https://docs.okd.io/latest/welcome/index.html[OKD Official Documentation Website]
* https://github.com/openshift/oauth-proxy/blob/master/contrib/sidecar.yaml[oauth-proxy]

== Main Contributor

* https://github.com/ArthurVardevanyan[@ArthurVardevanyan]
