= Important Notes
:weight: 4
:current-version: {page-component-version}

This page lists important notes for Longhorn v{current-version}.
Please see https://github.com/longhorn/longhorn/releases/tag/v{current-version}[here] for the full release note.

* <<general,General>>
 ** <<supported-kubernetes-versions,Supported Kubernetes Versions>>
 ** <<offline-upgrade-required-to-fully-prevent-unexpected-replica-expansion,Offline Upgrade Required To Fully Prevent Unexpected Replica Expansion>>
 ** <<default-priority-class,Default Priority Class>>
 ** <<new-node-drain-policies-added,New Node Drain Policies Added>>
 ** <<custom-resource-fields-deprecated,Custom Resource Fields Deprecated>>
 ** <<pod-security-policies-disabled--pod-security-admission-introduction,Pod Security Policies Disabled \& Pod Security Admission Introduction>>
 ** <<updating-csi-snapshot-crd-v1beta1-to-v1-v1beta1-removed,Updating CSI Snapshot CRD `v1beta1` to `v1`, `v1beta1` Removed>>
 ** <<engine-upgrade-enforcement,Engine Upgrade Enforcement>>
 ** <<danger-zone-setting-configuration,Danger Zone Setting Configuration>>
* <<v2-data-engine,V2 Data Engine>>
 ** <<longhorn-system-upgrade,Longhorn System Upgrade>>
 ** <<changing-default-huge-page-size-to-2-gib,Changing Default Huge Page Size to 2 GiB>>
 ** <<support-for-arm64-platform,Support for ARM64 Platform>>
 ** <<replacing-backendstoredriver-with-dataengine,Replacing `backendStoreDriver` with `dataEngine`>>
 ** <<updating-the-linux-kernel-on-longhorn-nodes,Updating the Linux Kernel on Longhorn Nodes>>

== General

=== Supported Kubernetes Versions

Please ensure your Kubernetes cluster is at least v1.21 before upgrading to Longhorn v{current-version} because this is the minimum version Longhorn v{current-version} supports.

=== Offline Upgrade Required To Fully Prevent Unexpected Replica Expansion

Longhorn v1.6.0 introduces a new mechanism to prevent xref:/home/jhk/projects/suse/longhorn-product-docs/modules/ROOT/kb/troubleshooting-unexpected-expansion-leads-to-degradation-or-attach-failure.adoc[unexpected replica
expansion]. This
mechanism is entirely transparent. However, a volume is only protected if it is running a new version of longhorn-engine
inside a new version of longhorn-instance-manager and managed by a new version of longhorn-manager. The xref:deploy/deploy/upgrade/upgrade-engine.adoc#_live_upgrade[live upgrade
process] results in a volume running a new version of longhorn-engine
in an old version of longhorn-instance-manager until it is detached (by scaling its consuming workload down) and
reattached (by scaling its consuming workload up). Consider scaling workloads down and back up again as soon as possible
after upgrading from a version without this mechanism (v1.5.1 or older) to v{current-version}.

=== Default Priority Class

Longhorn v1.6.0 introduces the default Priority Class `longhorn-critical`, which has the highest value and ensures that Longhorn pods are not evicted by kube-scheduler when system resources are low.

During upgrades, Longhorn applies the default Priority Class to components depending on specific settings.

* When all volumes are detached and you did not specify a value for the global Priority Class setting `priority-class`, the default Priority Class is applied to all Longhorn components. `priority-class` is updated.
* When all volumes are detached and you specified a value for the global Priority Class setting `priority-class`, the default Priority Class is applied only to user-deployed components. `priority-class` is not updated.
* When one or more volumes are attached and you did not specify a value for `PriorityClass` in the `chart/value.yaml` or `longhorn/deploy/longhorn.yaml`, the default Priority Class is applied only to user-deployed components. `priority-class` is not updated.

If you want to apply the default Priority Class to system-managed components, you must detach all volumes and change the Priority Class default setting value after the upgrade is successfully completed.

You can change these behaviors by customizing the following before starting the upgrade process:

* For user deployed components: `priorityClass` parameters for each component in the `values.yaml` file of the https://github.com/longhorn/longhorn/blob/v1.6.0/chart/values.yaml[Longhorn Helm chart]
* For system managed components: `defaultSetting.priorityClass` in the `values.yaml` file of the https://github.com/longhorn/longhorn/blob/v1.6.0/chart/values.yaml[Longhorn Helm chart]

=== New Node Drain Policies Added

There are two new options for the xref:deploy/references/settings.adoc#_node_drain_policy[Node Drain Policy] setting. Both `Block
For Eviction` and `Block for Eviction If Contains Last Replica` automatically evict replicas from draining nodes in
addition to preventing drain completion until volume data is sufficiently protected. `Block for Eviction` maintains
maximum data redundancy during maintenance operations, and both new options enable automated cluster upgrades when some
volumes have only one replica. See the new xref:deploy/maintenance/maintenance.adoc#_node_drain_policy_recommendations[Node Drain Policy
Recommendations] section for help deciding which
policy to use.

=== Custom Resource Fields Deprecated

Starting in `v1.6.0`, the following custom resource fields are deprecated. They will be removed in `v1.7.0`:

* Volume.status.evictionRequested

=== Pod Security Policies Disabled & Pod Security Admission Introduction

* Longhorn pods require privileged access to manage nodes' storage. In Longhorn `v1.3.x` or older, Longhorn was shipping some Pod Security Policies by default, (e.g., https://github.com/longhorn/longhorn/blob/4ba39a989b4b482d51fd4bc651f61f2b419428bd/chart/values.yaml#L260[link]).
However, Pod Security Policy has been deprecated since Kubernetes v1.21 and removed since Kubernetes v1.25, https://kubernetes.io/docs/concepts/security/pod-security-policy/[link].
Therefore, we stopped shipping the Pod Security Policies by default.
For Kubernetes < v1.25, if your cluster still enables Pod Security Policy admission controller, please do:
 ** Helm installation method: set the helm value `enablePSP` to `true` to install `longhorn-psp` PodSecurityPolicy resource which allows privileged Longhorn pods to start.
 ** Kubectl installation method: need to apply the https://raw.githubusercontent.com/longhorn/longhorn/master/deploy/podsecuritypolicy.yaml[podsecuritypolicy.yaml] manifest in addition to applying the `longhorn.yaml` manifests.
 ** Rancher UI installation method: set `Other Settings > Pod Security Policy` to `true` to install `longhorn-psp` PodSecurityPolicy resource which allows privileged Longhorn pods to start.
* As a replacement for Pod Security Policy, Kubernetes provides a new mechanism, https://kubernetes.io/docs/concepts/security/pod-security-admission/[Pod Security Admission].
If you enable the Pod Security Admission controller and change the default behavior to block privileged pods,
you must add the correct labels to the namespace where Longhorn pods run to allow Longhorn pods to start successfully
(because Longhorn pods require privileged access to manage storage).
For example, adding the following labels to the namespace that is running Longhorn pods:
  `yaml
  apiVersion: v1
  kind: Namespace
  metadata:
    name: longhorn-system
    labels:
      pod-security.kubernetes.io/enforce: privileged
      pod-security.kubernetes.io/enforce-version: latest
      pod-security.kubernetes.io/audit: privileged
      pod-security.kubernetes.io/audit-version: latest
      pod-security.kubernetes.io/warn: privileged
      pod-security.kubernetes.io/warn-version: latest
 	`

=== Updating CSI Snapshot CRD `v1beta1` to `v1`, `v1beta1` Removed

Support for the `v1beta1` version of CSI snapshot CRDs was previously deprecated in favor of the `v1` version.
The CSI components in Longhorn v{current-version} only function with the `v1` version.
Please follow the instructions at xref:deploy/snapshots-and-backups/csi-snapshot-support/enable-csi-snapshot-support.adoc[Enable CSI Snapshot Support] to update CSI snapshot CRDs and the CSI snapshot controller.
If you have Longhorn volume manifests or scripts that are still using `v1beta1` version, you must upgrade them to `v1` as well.

=== Engine Upgrade Enforcement

Beginning with version v1.6.0, Longhorn is implementing mandatory engine upgrades. See the https://github.com/longhorn/longhorn/releases/tag/v{current-version}[release note] for information about the minimum supported engine image version.

When upgrading through Helm, a component compatibility check is automatically performed. If the new Longhorn is not compatible with the engine images that are currently in use, the upgrade path is blocked through a pre-hook mechanism.

If you installed Longhorn using the manifests, engine upgrades are enforced by the Longhorn Manager. Attempts to upgrade Longhorn Manager may cause unsuccessful pod launches and generate corresponding error logs, although it poses no harm. If you encounter such errors, you must revert to the previous Longhorn version and then upgrade the engines that are using the incompatible engine images before the next upgrade.

WARNING: Whenever engine upgrade enforcement causes upgrade failure, Longhorn allows you to revert to the previous version because Longhorn Manager will block the entire upgrade. However, Longhorn prohibits downgrading when an upgrade is successful. For more information, see xref:deploy/deploy/upgrade.adoc#_upgrade_path_enforcement_and_downgrade_prevention[Upgrade Path Enforcement].

You can determine the versions of engine images that are currently in use with the following script:

[subs="+attributes",bash]
----
#!/bin/bash

namespace="longhorn-system"

engine_images=$(kubectl -n $namespace get engineimage -o=jsonpath='{.items[*].metadata.name}')

for engine_image in $engine_images; do
    cli_api_version=$(kubectl -n $namespace get engineimage $engine_image -o=jsonpath='{.status.cliAPIVersion}')
    controller_api_version=$(kubectl -n $namespace get engineimage $engine_image -o=jsonpath='{.status.controllerAPIVersion}')
    echo "EngineImage: $engine_image | cliAPIVersion: $cli_api_version | controllerAPIVersion: $controller_api_version"
done
----

Once you successfully upgrade to version v1.6.0, you will be able to view information about engine image versions on the UI.

=== Danger Zone Setting Configuration

Starting with Longhorn v1.6.0, Longhorn allows you to modify the https://longhorn.io/docs/1.6.0/references/settings/#danger-zone[Danger Zone settings] without the need to wait for all volumes to become detached. Your preferred settings are immediately applied in the following scenarios:

* No attached volumes: When no volumes are attached before the settings are configured, the setting changes are immediately applied.
* Engine image upgrade (live upgrade): During a live upgrade, which involves creating a new Instance Manager pod, the setting changes are immediately applied to the new pod.

Settings are synchronized hourly. When all volumes are detached, the settings in the following table are immediately applied and the system-managed components (for example, Instance Manager, CSI Driver, and engine images) are restarted. If you do not detach all volumes before the settings are synchronized, the settings are not applied and you must reconfigure the same settings after detaching the remaining volumes.

|===
| Setting | Additional Information | Affected Components

| xref:deploy/references/settings.adoc#_kubernetes_taint_toleration[Kubernetes Taint Toleration]
| xref:deploy/advanced-resources/deploy/taint-toleration.adoc[Taints and Tolerations]
| System-managed components

| xref:deploy/references/settings.adoc#_priority_class[Priority Class]
| xref:deploy/advanced-resources/deploy/priority-class.adoc[Priority Class]
| System-managed components

| xref:deploy/references/settings.adoc#_system_managed_components_node_selector[System Managed Components Node Selector]
| xref:deploy/advanced-resources/deploy/node-selector.adoc[Node Selector]
| System-managed components

| xref:deploy/references/settings.adoc#_storage_network[Storage Network]
| xref:deploy/advanced-resources/deploy/storage-network.adoc[Storage Network]
| Instance Manager and Backing Image components

| xref:deploy/references/settings.adoc#_v1_data_engine[V1 Data Engine]
|
| Instance Manager component

| xref:deploy/references/settings.adoc#_v2_data_engine[V2 Data Engine]
| xref:deploy/v2-data-engine.adoc[V2 Data Engine (Preview Feature)]
| Instance Manager component

| xref:deploy/references/settings.adoc#_guaranteed_instance_manager_cpu[Guaranteed Instance Manager CPU]
|
| Instance Manager component

| xref:deploy/references/settings.adoc#_guaranteed_instance_manager_cpu_for_v2_data_engine[Guaranteed Instance Manager CPU for V2 Data Engine]
|
| Instance Manager component
|===

For V1 and V2 Data Engine settings, you can disable the Data Engines only when all associated volumes are detached. For example, you can disable the V2 Data Engine only when all V2 volumes are detached (even when V1 volumes are still attached).

== V2 Data Engine

=== Longhorn System Upgrade

Longhorn currently does not support live upgrading of V2 volumes. Ensure that all V2 volumes are detached before initiating the upgrade process.

=== Changing Default Huge Page Size to 2 GiB

The default huge page size for the V2 Data Engine has been raised to 2 GiB, allowing the creation of more V2 volumes and enhancing the overall user experience. Before upgrading to v1.6.0, ensure that the configured huge page size on each node is 2 GiB.

=== Support for ARM64 Platform

As of Longhorn v1.6.0, volumes using the V2 Data Engine support the ARM64 platform. For more information, see xref:deploy/v2-data-engine/prerequisites.adoc[Prerequisites].

=== Replacing `backendStoreDriver` with `dataEngine`

The attribute `backendStoreDriver`, which is defined in the parameters of StorageClasses and other Longhorn resources (for example, volumes, engines, and replicas), has been replaced with `dataEngine`. You must remove the existing StorageClasses for V2 volumes and create new ones that use `dataEngine`.

=== Updating the Linux Kernel on Longhorn Nodes

Host machines with Linux kernel 5.15 may unexpectedly reboot when volume-related IO errors occur. Update the Linux kernel on Longhorn nodes to version 5.19 or later to prevent such issues. For more information, see xref:deploy/v2-data-engine/prerequisites.adoc[Prerequisites].
