= Fazer upgrade do Kubernetes no Azure Kubernetes Service (AKS)
:revdate: 2026-01-12
:page-revdate: {revdate}
:current-version: {page-component-version}

O AKS fornece `az aks upgrade` para fazer upgrade dos nós no local por meio da reimagem de nós, mas isso fará com que os discos originais {longhorn-product-name} fiquem ausentes, então não haverá discos permitindo a reconstrução de réplicas nos nós atualizados.

Sugerimos usar a substituição do pool de nós para fazer upgrade dos nós do agente, mas usar `az aks upgrade` para os nós do plano de controle para garantir a segurança dos dados.

. Em {longhorn-product-name}, defina `replica-replenishment-wait-interval` como `0`.
. Fazer upgrade do plano de controle do AKS.
+
----
 AKS_RESOURCE_GROUP=<aks-resource-group>
 AKS_CLUSTER_NAME=<aks-cluster-name>
 AKS_K8S_VERSION_UPGRADE=<aks-k8s-version>

 az aks upgrade \
     --resource-group ${AKS_RESOURCE_GROUP} \
     --name ${AKS_CLUSTER_NAME} \
     --kubernetes-version ${AKS_K8S_VERSION_UPGRADE} \
     --control-plane-only
----

. Adicionar um novo pool de nós.
+
----
 AKS_NODEPOOL_NAME_NEW=<new-nodepool-name>
 AKS_DISK_SIZE=<disk-size-in-gb>
 AKS_NODE_NUM=<number-of-nodes>

 az aks nodepool add \
   --resource-group ${AKS_RESOURCE_GROUP} \
   --cluster-name ${AKS_CLUSTER_NAME} \
   --name ${AKS_NODEPOOL_NAME_NEW} \
   --node-count ${AKS_NODE_NUM} \
   --node-osdisk-size ${AKS_DISK_SIZE} \
   --kubernetes-version ${AKS_K8S_VERSION_UPGRADE} \
   --mode System
----

. Usando a interface {longhorn-product-name} para desativar o agendamento de disco e solicitar a evacuação para os nós no antigo pool de nós.
. Cordon e drenar os nós do Kubernetes no antigo pool de nós.
+
----
 AKS_NODEPOOL_NAME_OLD=<old-nodepool-name>

 for n in `kubectl get nodes | grep ${AKS_NODEPOOL_NAME_OLD}- | awk '{print $1}'`; do
   kubectl cordon $n && \
   kubectl drain $n --ignore-daemonsets --delete-emptydir-data
 done
----

. Excluir o antigo pool de nós.
+
----
 az aks nodepool delete \
   --cluster-name ${AKS_CLUSTER_NAME} \
   --name ${AKS_NODEPOOL_NAME_OLD} \
   --resource-group ${AKS_RESOURCE_GROUP}
----
