= Crie um Ingress com Autenticação Básica (nginx)
:revdate: 2026-03-17
:page-revdate: {revdate}
:current-version: {page-component-version}

[NOTE]
====
A partir de novembro de 2025, o projeto Kubernetes anunciou a aposentadoria do controlador ingress-nginx. Para detalhes, https://kubernetes.io/blog/2025/11/11/ingress-nginx-retirement/[veja o anúncio oficial].

*Alternativa Recomendada*:

* **Traefik Ingress**: O padrão atual para ambientes RKE2/K3s. Veja xref:longhorn-system/system-access/longhorn-ingress-traefik.adoc[Crie um Ingress com Traefik].
* **Gateway API**: O sucessor moderno do Ingress para roteamento avançado. Veja xref:longhorn-system/system-access/longhorn-httproute.adoc[Crie um HTTPRoute com Gateway API].
====

Se você instalar {longhorn-product-name} em um cluster Kubernetes com kubectl ou Helm, precisará criar um Ingress para permitir que o tráfego externo chegue à interface do usuário {longhorn-product-name}.

A autenticação não está habilitada por padrão para instalações com kubectl e Helm. Nestes passos, você aprenderá como criar um Ingress com autenticação básica usando anotações para o controlador ingress-nginx.

. Crie um arquivo de autenticação básica `auth`. É importante que o arquivo gerado seja nomeado auth (ou seja, que o segredo possua uma chave `data.auth`); caso contrário, o Ingress retornará um 503.
+
[,console]
----
$ USER=<USERNAME_HERE>; PASSWORD=<PASSWORD_HERE>; echo "${USER}:$(openssl passwd -stdin -apr1 <<< ${PASSWORD})" >> auth
----

. Crie um segredo:
+
[subs="+attributes",bash]
----
$ kubectl -n longhorn-system create secret generic basic-auth --from-file=auth
----

. Crie um manifesto de Ingress `longhorn-ingress.yml`:
+
____
Desde a versão v1.2.0, {longhorn-product-name} suporta o upload de imagem de fundo pela interface do usuário; portanto, especifique `nginx.ingress.kubernetes.io/proxy-body-size: 10000m` conforme abaixo para garantir que o upload de imagens funcione como esperado.
____
+
[subs="+attributes",yaml]
----
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: longhorn-ingress
  namespace: longhorn-system
  annotations:
    # type of authentication
    nginx.ingress.kubernetes.io/auth-type: basic
    # prevent the controller from redirecting (308) to HTTPS
    nginx.ingress.kubernetes.io/ssl-redirect: 'false'
    # name of the secret that contains the user/password definitions
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    # message to display with an appropriate context why the authentication is required
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required '
    # custom max body size for file uploading like backing image uploading
    nginx.ingress.kubernetes.io/proxy-body-size: 10000m
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: longhorn-frontend
            port:
              number: 80
----

. Crie o Ingress:
+
[subs="+attributes",bash]
----
$ kubectl -n longhorn-system apply -f longhorn-ingress.yml
----

Por exemplo:

[,console]
----
$ USER=foo; PASSWORD=bar; echo "$\{USER}:$(openssl passwd -stdin -apr1 <<< $\{PASSWORD})" >> auth
$ cat auth
foo:$apr1$FnyKCYKb$6IP2C45fZxMcoLwkOwf7k0

$ kubectl -n longhorn-system create secret generic basic-auth --from-file=auth
secret/basic-auth created
$ kubectl -n longhorn-system get secret basic-auth -o yaml
apiVersion: v1
data:
  auth: Zm9vOiRhcHIxJEZueUtDWUtiJDZJUDJDNDVmWnhNY29Md2tPd2Y3azAK
kind: Secret
metadata:
  creationTimestamp: "2020-05-29T10:10:16Z"
  name: basic-auth
  namespace: longhorn-system
  resourceVersion: "2168509"
  selfLink: /api/v1/namespaces/longhorn-system/secrets/basic-auth
  uid: 9f66233f-b12f-4204-9c9d-5bcaca794bb7
type: Opaque

$ echo "
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: longhorn-ingress
  namespace: longhorn-system
  annotations:
    # type of authentication
    nginx.ingress.kubernetes.io/auth-type: basic
    # prevent the controller from redirecting (308) to HTTPS
    nginx.ingress.kubernetes.io/ssl-redirect: 'false'
    # name of the secret that contains the user/password definitions
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    # message to display with an appropriate context why the authentication is required
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required '
spec:
  rules:

* http:
  paths:
 ** pathType: Prefix
path: "/"
backend:
  service:
    name: longhorn-frontend
    port:
      number: 80
" | kubectl -n longhorn-system create -f -
ingress.networking.k8s.io/longhorn-ingress created

$ kubectl -n longhorn-system get ingress
NAME               HOSTS   ADDRESS                                     PORTS   AGE
longhorn-ingress   *       45.79.165.114,66.228.45.37,97.107.142.125   80      2m7s

$ curl -v http://97.107.142.125/

* Trying 97.107.142.125...
* TCP_NODELAY set
* Connected to 97.107.142.125 (97.107.142.125) port 80 (#0)
+
____
GET / HTTP/1.1
Host: 97.107.142.125
User-Agent: curl/7.64.1
Accept: _/_

< HTTP/1.1 401 Unauthorized
< Server: openresty/1.15.8.1
< Date: Fri, 29 May 2020 11:47:33 GMT
< Content-Type: text/html
< Content-Length: 185
< Connection: keep-alive
< WWW-Authenticate: Basic realm="Authentication Required"
<
----
