= Identificar réplicas corruptas
:revdate: 2025-06-27
:page-revdate: {revdate}
:current-version: {page-component-version}

En el caso de que uno de los discos utilizados por Longhorn fallara, podrías experimentar errores intermitentes de entrada/salida al utilizar un volumen de Longhorn.

Por ejemplo, a veces un archivo no se puede leer, pero más tarde sí. En este escenario, es probable que uno de los discos haya fallado, lo que resulta en que una de las réplicas devuelva datos incorrectos al usuario.

Para recuperar el volumen, podemos identificar la réplica corrupta y eliminarla del volumen:

. Reduce la carga de trabajo para desacoplar el volumen.
. Encuentra todas las ubicaciones de las réplicas comprobando la interfaz de usuario de Longhorn. Los directorios utilizados por las réplicas se mostrarán como un tooltip para cada réplica en la interfaz de usuario.
. Inicia sesión en cada nodo que contenga una réplica del volumen y accede al directorio que contiene los datos de la réplica.
+
Por ejemplo, la réplica podría estar almacenada en:

  /var/lib/longhorn/replicas/pvc-06b4a8a8-b51d-42c6-a8cc-d8c8d6bc65bc-d890efb2

. Ejecuta una suma de comprobación para cada archivo en ese directorio.
+
Por ejemplo:
+
----
 # sha512sum /var/lib/longhorn/replicas/pvc-06b4a8a8-b51d-42c6-a8cc-d8c8d6bc65bc-d890efb2/*
 fcd1b3bb677f63f58a61adcff8df82d0d69b669b36105fc4f39b0baf9aa46ba17bd47a7595336295ef807769a12583d06a8efb6562c093574be7d14ea4d6e5f4  /var/lib/longhorn/replicas/pvc-06b4a8a8-b51d-42c6-a8cc-d8c8d6bc65bc-d890efb2/revision.counter
 c53649bf4ad843dd339d9667b912f51e0a0bb14953ccdc9431f41d46c85301dff4a021a50a0bf431a931a43b16ede5b71057ccadad6cf37a54b2537e696f4780  /var/lib/longhorn/replicas/pvc-06b4a8a8-b51d-42c6-a8cc-d8c8d6bc65bc-d890efb2/volume-head-000.img
 f6cd5e486c88cb66c143913149d55f23e6179701f1b896a1526717402b976ed2ea68fc969caeb120845f016275e0a9a5b319950ae5449837e578665e2ffa82d0  /var/lib/longhorn/replicas/pvc-06b4a8a8-b51d-42c6-a8cc-d8c8d6bc65bc-d890efb2/volume-head-000.img.meta
 e6f6e97a14214aca809a842d42e4319f4623adb8f164f7836e07dc8a3f4816a0389b67c45f7b0d9f833d50a731ae6c4670ba1956833f1feb974d2d12421b03f7  /var/lib/longhorn/replicas/pvc-06b4a8a8-b51d-42c6-a8cc-d8c8d6bc65bc-d890efb2/volume.meta
----

. Compara la salida de cada réplica. Una de ellas debería fallar o tener resultados diferentes en comparación con las demás. Esta será la réplica que debemos eliminar del volumen.
. Utiliza la interfaz de usuario de Longhorn para eliminar la réplica identificada del volumen.
. Aumenta la carga de trabajo para asegurarte de que el error ha desaparecido.
