= Personnaliser les paramètres par défaut
:revdate: 2025-06-29
:page-revdate: {revdate}
:experimental:
:current-version: {page-component-version}

Vous pouvez personnaliser les paramètres par défaut de {longhorn-product-name} lors de l'installation ou de la mise à niveau. Vous pouvez spécifier, par exemple, `Create Default Disk With Node Labeled` et `Default Data Path` avant de commencer {longhorn-product-name}.

[NOTE]
====
Lors de l'utilisation du fichier YAML de déploiement Longhorn ou de Helm pour l'installation, la mise à jour ou la mise à niveau, si la valeur d'un paramètre par défaut est une chaîne vide et valide, le paramètre par défaut sera nettoyé dans {longhorn-product-name}. Sinon, {longhorn-product-name} ignorera les valeurs invalides et ne mettra pas à jour les valeurs par défaut.
====

== Installation

=== Utiliser l'interface utilisateur de Rancher

Depuis la vue projet dans Rancher, allez à menu:Applications et Marketplace[Longhorn > Installer > Suivant > Modifier les options > Paramètres par défaut de Longhorn > Personnaliser les paramètres par défaut] et modifiez les paramètres avant d'installer l'appli.

=== Utiliser le fichier YAML de déploiement Longhorn

. Téléchargez le dépôt longhorn{nbsp}:
+
[subs="+attributes",shell]
----
git clone https://github.com/longhorn/longhorn.git
----

. Modifiez la carte de configuration nommée `longhorn-default-setting` dans le fichier YAML `longhorn/deploy/longhorn.yaml`.
+
Dans l'exemple ci-dessous, les utilisateurs personnalisent les paramètres par défaut, la cible de sauvegarde, le secret d'identification de la cible de sauvegarde et le chemin de données par défaut.
 Lorsque le paramètre est absent ou a un symbole `#` en tête, le paramètre par défaut utilisera la valeur par défaut dans {longhorn-product-name} ou les valeurs personnalisées précédemment configurées.
+
[subs="+attributes",yaml]
----
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: longhorn-default-setting
  namespace: longhorn-system
data:
  default-setting.yaml: |-
    backup-target: s3://backupbucket@us-east-1/backupstore
    backup-target-credential-secret: minio-secret
    #allow-recurring-job-while-volume-detached:
    #create-default-disk-labeled-nodes:
    default-data-path: /var/lib/longhorn-example/
    #replica-soft-anti-affinity:
    #replica-auto-balance:
    #storage-over-provisioning-percentage:
    #storage-minimal-available-percentage:
    #upgrade-checker:
    #upgrade-responder-url:
    #default-replica-count:
    #default-data-locality:
    #default-longhorn-static-storage-class:
    #backupstore-poll-interval:
    #taint-toleration:
    #system-managed-components-node-selector:
    #priority-class:
    #auto-salvage:
    #auto-delete-pod-when-volume-detached-unexpectedly:
    #disable-scheduling-on-cordoned-node:
    #replica-zone-soft-anti-affinity:
    #replica-disk-soft-anti-affinity:
    #node-down-pod-deletion-policy:
    #node-drain-policy:
    #replica-replenishment-wait-interval:
    #concurrent-replica-rebuild-per-node-limit:
    #disable-revision-counter:
    #system-managed-pods-image-pull-policy:
    #allow-volume-creation-with-degraded-availability:
    #auto-cleanup-system-generated-snapshot:
    #concurrent-automatic-engine-upgrade-per-node-limit:
    #backing-image-cleanup-wait-interval:
    #backing-image-recovery-wait-interval:
    #guaranteed-instance-manager-cpu:
    #kubernetes-cluster-autoscaler-enabled:
    #orphan-resource-auto-deletion:
    #storage-network:
    #recurring-successful-jobs-history-limit:
    #recurring-failed-jobs-history-limit:
---
----

=== Utiliser Helm

[NOTE]
====
Utilisez Helm 3 lors de l'installation et de la mise à niveau de {longhorn-product-name}. Helm 2 n'est https://helm.sh/blog/helm-2-becomes-unsupported/[plus pris en charge].
====

Utilisez la commande Helm avec le drapeau `--set` pour modifier les paramètres par défaut. Par exemple :

[subs="+attributes",shell]
----
helm install longhorn longhorn/longhorn \
  --namespace longhorn-system \
  --create-namespace \
  --set defaultSettings.taintToleration="key1=value1:NoSchedule; key2:NoExecute"
----

Vous pouvez également fournir une copie du fichier `values.yaml` avec les paramètres par défaut modifiés au drapeau `--values` lors de l'exécution de la commande Helm{nbsp}:

. Obtenez une copie du fichier `values.yaml` depuis GitHub{nbsp}:
+
[subs="+attributes",shell]
----
curl -Lo values.yaml https://raw.githubusercontent.com/longhorn/charts/master/charts/longhorn/values.yaml
----

. Modifiez les paramètres par défaut dans le fichier YAML. Voici un extrait d'exemple de `values.yaml`{nbsp}:
+
Lorsque le paramètre est absent ou a un symbole `#` en tête, le paramètre par défaut utilisera la valeur par défaut dans {longhorn-product-name} ou les valeurs personnalisées précédemment configurées.
+
[subs="+attributes",yaml]
----
defaultSettings:
  backupTarget: s3://backupbucket@us-east-1/backupstore
  backupTargetCredentialSecret: minio-secret
  createDefaultDiskLabeledNodes: true
  defaultDataPath: /var/lib/longhorn-example/
  replicaSoftAntiAffinity: false
  storageOverProvisioningPercentage: 600
  storageMinimalAvailablePercentage: 15
  upgradeChecker: false
  defaultReplicaCount: 2
  defaultDataLocality: disabled
  defaultLonghornStaticStorageClass: longhorn-static-example
  backupstorePollInterval: 500
  taintToleration: key1=value1:NoSchedule; key2:NoExecute
  systemManagedComponentsNodeSelector: "label-key1:label-value1"
  priorityClass: high-priority
  autoSalvage: false
  disableSchedulingOnCordonedNode: false
  replicaZoneSoftAntiAffinity: false
  replicaDiskSoftAntiAffinity: false
  volumeAttachmentRecoveryPolicy: never
  nodeDownPodDeletionPolicy: do-nothing
  guaranteedInstanceManagerCpu: 15
  orphanAutoDeletion: ""
  orphanResourceAutoDeletionGracePeriod: 300
----

. Exécutez Helm avec `values.yaml`{nbsp}:
+
[subs="+attributes",shell]
----
helm install longhorn longhorn/longhorn \
  --namespace longhorn-system \
  --create-namespace \
  --values values.yaml
----

Pour plus d'informations sur l'utilisation de Helm, consultez la section xref:installation-setup/installation/install-using-helm.adoc[installer {longhorn-product-name} avec Helm].

=== Utilisation du Contrôleur Helm

Dans le fichier YAML de HelmChart, ajoutez des lignes à spec.set avec les paramètres souhaités{nbsp}:

[,yaml]
----
spec:
  ...
  set:
    defaultSettings.priorityClass: system-node-critical
    defaultSettings.replicaAutoBalance: least-effort
    defaultSettings.storageOverProvisioningPercentage: "200"
    persistence.defaultClassReplicaCount: "2"
----

=== Utilisation du Contrôleur Helm

Dans le fichier YAML de HelmChart, ajoutez des lignes à `spec.set` avec les paramètres souhaités{nbsp}:

[,yaml]
----
spec:
  ...
  set:
    defaultSettings.priorityClass: system-node-critical
    defaultSettings.replicaAutoBalance: least-effort
    defaultSettings.storageOverProvisioningPercentage: "200"
    persistence.defaultClassReplicaCount: "2"
----

== Paramètres de mise à jour

=== Utilisation de l'interface utilisateur {longhorn-product-name}

Nous recommandons d'utiliser l'interface utilisateur {longhorn-product-name} pour modifier le paramètre {longhorn-product-name} sur le cluster existant. Cela rendrait le paramètre persistant.

=== Utiliser l'interface utilisateur de Rancher

Depuis la vue projet dans Rancher, allez à menu:Apps && Marketplace[Longhorn > Mettre à niveau > Suivant > Modifier les options > Paramètres par défaut de Longhorn > Personnaliser les paramètres par défaut] et modifiez les paramètres avant de mettre à niveau l'appli vers la version actuelle {longhorn-product-name}.

=== Utilisation de Kubectl

Si vous préférez mettre à jour le paramètre depuis la ligne de commande, utilisez `kubectl`. Pour éviter les collisions avec d'autres CRD, n'utilisez pas le simple `settings`. Utilisez plutôt `settings.longhorn.io` ou `lhs`.

[subs="+attributes",shell]
----
kubectl edit settings.longhorn.io <SETTING-NAME> -n longhorn-system
----

=== Utiliser Helm

Modifiez les paramètres par défaut dans le fichier YAML comme décrit dans <<_using_helm,Installation fraîche > Utilisation de Helm>> puis mettez à jour les paramètres en utilisant

----
helm upgrade longhorn longhorn/longhorn --namespace longhorn-system --values ./values.yaml --version `helm list -n longhorn-system -o json | jq -r .'[0].app_version'`
----

== Mise à niveau

=== Utiliser l'interface utilisateur de Rancher

Depuis la vue projet dans Rancher, allez à menu:Apps && Marketplace[Longhorn > Mettre à niveau > Suivant > Modifier les options > Paramètres par défaut de Longhorn > Personnaliser les paramètres par défaut] et modifiez les paramètres avant de mettre à niveau l'appli.

=== Utiliser le fichier YAML de déploiement Longhorn

Modifiez la carte de configuration nommée `longhorn-default-setting` dans le fichier YAML `longhorn/deploy/longhorn.yaml` comme décrit dans <<_using_the_longhorn_deployment_yaml_file,Installation fraîche > Utilisation du fichier YAML de déploiement Longhorn>> puis mettez à niveau le système Longhorn en utilisant `kubectl`.

=== Utiliser Helm

Modifiez les paramètres par défaut dans le fichier YAML comme décrit dans <<_using_helm,Installation fraîche > Utilisation de Helm>> puis mettez à niveau le système Longhorn en utilisant `helm upgrade`.

== History

Disponible depuis v1.3.0 (https://github.com/longhorn/longhorn/issues/2570[Référence])
