= Personalizar la configuración predeterminada
:revdate: 2025-06-29
:page-revdate: {revdate}
:experimental:
:current-version: {page-component-version}

Puedes personalizar la configuración predeterminada de {longhorn-product-name} durante la instalación o al actualizar versión. Puedes especificar, por ejemplo, `Create Default Disk With Node Labeled` y `Default Data Path` antes de iniciar {longhorn-product-name}.

[NOTE]
====
Al utilizar el archivo YAML de ampliación de Longhorn o Helm para la instalación, la actualización o la actualización de versión, si el valor de una configuración predeterminada es una cadena vacía y válida, la configuración predeterminada se limpiará en {longhorn-product-name}. Si no, {longhorn-product-name} ignorará los valores no válidos y no actualizará los valores predeterminados.
====

== Instalación

=== Usando la interfaz de usuario de Rancher

Desde la vista del proyecto en Rancher, ve a menu:Apps && Marketplace[Longhorn > Instalar > Siguiente > Editar opciones > Configuración predeterminada de Longhorn > Personalizar la configuración predeterminada] y edita la configuración antes de instalar la aplicación.

=== Usando el archivo YAML de ampliación de Longhorn

. Descarga el repositorio de Longhorn:
+
[subs="+attributes",shell]
----
git clone https://github.com/longhorn/longhorn.git
----

. Modifica el mapa de configuración llamado `longhorn-default-setting` en el archivo YAML `longhorn/deploy/longhorn.yaml`.
+
En el siguiente ejemplo, los usuarios personalizan la configuración predeterminada, el objetivo de respaldo, el secreto de credenciales del objetivo de respaldo y la ruta de datos predeterminada.
 Cuando la configuración está ausente o tiene un símbolo `#` al principio, la configuración predeterminada utilizará el valor predeterminado en {longhorn-product-name} o los valores personalizados configurados previamente.
+
[subs="+attributes",yaml]
----
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: longhorn-default-setting
  namespace: longhorn-system
data:
  default-setting.yaml: |-
    backup-target: s3://backupbucket@us-east-1/backupstore
    backup-target-credential-secret: minio-secret
    #allow-recurring-job-while-volume-detached:
    #create-default-disk-labeled-nodes:
    default-data-path: /var/lib/longhorn-example/
    #replica-soft-anti-affinity:
    #replica-auto-balance:
    #storage-over-provisioning-percentage:
    #storage-minimal-available-percentage:
    #upgrade-checker:
    #upgrade-responder-url:
    #default-replica-count:
    #default-data-locality:
    #default-longhorn-static-storage-class:
    #backupstore-poll-interval:
    #taint-toleration:
    #system-managed-components-node-selector:
    #priority-class:
    #auto-salvage:
    #auto-delete-pod-when-volume-detached-unexpectedly:
    #disable-scheduling-on-cordoned-node:
    #replica-zone-soft-anti-affinity:
    #replica-disk-soft-anti-affinity:
    #node-down-pod-deletion-policy:
    #node-drain-policy:
    #replica-replenishment-wait-interval:
    #concurrent-replica-rebuild-per-node-limit:
    #disable-revision-counter:
    #system-managed-pods-image-pull-policy:
    #allow-volume-creation-with-degraded-availability:
    #auto-cleanup-system-generated-snapshot:
    #concurrent-automatic-engine-upgrade-per-node-limit:
    #backing-image-cleanup-wait-interval:
    #backing-image-recovery-wait-interval:
    #guaranteed-instance-manager-cpu:
    #kubernetes-cluster-autoscaler-enabled:
    #orphan-resource-auto-deletion:
    #storage-network:
    #recurring-successful-jobs-history-limit:
    #recurring-failed-jobs-history-limit:
---
----

=== Usando Helm

[NOTE]
====
Utiliza Helm 3 al instalar y al actualizar versión {longhorn-product-name}. Helm 2 https://helm.sh/blog/helm-2-becomes-unsupported/[ya no está soportado].
====

Utiliza el comando Helm con la bandera `--set` para modificar la configuración predeterminada. Por ejemplo:

[subs="+attributes",shell]
----
helm install longhorn longhorn/longhorn \
  --namespace longhorn-system \
  --create-namespace \
  --set defaultSettings.taintToleration="key1=value1:NoSchedule; key2:NoExecute"
----

También puedes proporcionar una copia del archivo `values.yaml` con la configuración predeterminada modificada a la bandera `--values` al ejecutar el comando Helm:

. Obtén una copia del archivo `values.yaml` de GitHub:
+
[subs="+attributes",shell]
----
curl -Lo values.yaml https://raw.githubusercontent.com/longhorn/charts/master/charts/longhorn/values.yaml
----

. Modifica la configuración predeterminada en el archivo YAML. A continuación se muestra un fragmento de ejemplo de `values.yaml`:
+
Cuando la configuración está ausente o tiene un símbolo `#` al principio, la configuración predeterminada utilizará el valor predeterminado en {longhorn-product-name} o los valores personalizados configurados previamente.
+
[subs="+attributes",yaml]
----
defaultSettings:
  backupTarget: s3://backupbucket@us-east-1/backupstore
  backupTargetCredentialSecret: minio-secret
  createDefaultDiskLabeledNodes: true
  defaultDataPath: /var/lib/longhorn-example/
  replicaSoftAntiAffinity: false
  storageOverProvisioningPercentage: 600
  storageMinimalAvailablePercentage: 15
  upgradeChecker: false
  defaultReplicaCount: 2
  defaultDataLocality: disabled
  defaultLonghornStaticStorageClass: longhorn-static-example
  backupstorePollInterval: 500
  taintToleration: key1=value1:NoSchedule; key2:NoExecute
  systemManagedComponentsNodeSelector: "label-key1:label-value1"
  priorityClass: high-priority
  autoSalvage: false
  disableSchedulingOnCordonedNode: false
  replicaZoneSoftAntiAffinity: false
  replicaDiskSoftAntiAffinity: false
  volumeAttachmentRecoveryPolicy: never
  nodeDownPodDeletionPolicy: do-nothing
  guaranteedInstanceManagerCpu: 15
  orphanAutoDeletion: ""
  orphanResourceAutoDeletionGracePeriod: 300
----

. Ejecuta Helm con `values.yaml`:
+
[subs="+attributes",shell]
----
helm install longhorn longhorn/longhorn \
  --namespace longhorn-system \
  --create-namespace \
  --values values.yaml
----

Para más información sobre el uso de helm, consulta la sección xref:installation-setup/installation/install-using-helm.adoc[instalar {longhorn-product-name} con Helm].

=== Usando el Controlador de Helm

En el archivo YAML de HelmChart, añade líneas a spec.set con la configuración deseada:

[,yaml]
----
spec:
  ...
  set:
    defaultSettings.priorityClass: system-node-critical
    defaultSettings.replicaAutoBalance: least-effort
    defaultSettings.storageOverProvisioningPercentage: "200"
    persistence.defaultClassReplicaCount: "2"
----

=== Usando Helm Controller

En el archivo YAML de HelmChart, añade líneas a `spec.set` con la configuración deseada:

[,yaml]
----
spec:
  ...
  set:
    defaultSettings.priorityClass: system-node-critical
    defaultSettings.replicaAutoBalance: least-effort
    defaultSettings.storageOverProvisioningPercentage: "200"
    persistence.defaultClassReplicaCount: "2"
----

== Ajustes de actualización

=== Usando la interfaz de usuario de {longhorn-product-name}

Recomendamos usar la interfaz de usuario de {longhorn-product-name} para cambiar la configuración de {longhorn-product-name} en el clúster existente. Haría que la configuración fuera persistente.

=== Usando la interfaz de usuario de Rancher

Desde la vista del proyecto en Rancher, ve a menu:Apps && Marketplace[Longhorn > Actualizar versión > Siguiente > Editar opciones > Configuración predeterminada de Longhorn > Personalizar la configuración predeterminada] y edita la configuración antes de actualizar la aplicación a la versión actual {longhorn-product-name}.

=== Usando Kubectl

Si prefieres actualizar la configuración desde la línea de comandos, usa `kubectl`. Para evitar colisiones con otros CRDs, no uses el simple `settings`. En su lugar, usa `settings.longhorn.io` o `lhs`.

[subs="+attributes",shell]
----
kubectl edit settings.longhorn.io <SETTING-NAME> -n longhorn-system
----

=== Usando Helm

Modifica la configuración predeterminada en el archivo YAML como se describe en <<_using_helm,Instalación Fresca > Usando Helm>> y luego actualiza la configuración usando

----
helm upgrade longhorn longhorn/longhorn --namespace longhorn-system --values ./values.yaml --version `helm list -n longhorn-system -o json | jq -r .'[0].app_version'`
----

== Actualización

=== Usando la interfaz de usuario de Rancher

Desde la vista del proyecto en Rancher, ve a menu:Apps && Marketplace[Longhorn > Actualizar versión > Siguiente > Editar opciones > Configuración predeterminada de Longhorn > Personalizar la configuración predeterminada] y edita la configuración antes de actualizar la aplicación.

=== Usando el archivo YAML de ampliación de Longhorn

Modifica el mapa de configuración llamado `longhorn-default-setting` en el archivo YAML `longhorn/deploy/longhorn.yaml` como se describe en <<_using_the_longhorn_deployment_yaml_file,Instalación Fresca > Usando el archivo YAML de ampliación de Longhorn>> y luego actualiza versión el sistema Longhorn usando `kubectl`.

=== Usando Helm

Modifica la configuración predeterminada en el archivo YAML como se describe en <<_using_helm,Instalación Fresca > Usando Helm>> y luego actualiza versión el sistema Longhorn usando `helm upgrade`.

== Historial

Disponible desde v1.3.0 (https://github.com/longhorn/longhorn/issues/2570[Referencia])
