= Restore a Volume from a Backup
:current-version: {page-component-version}

Longhorn can easily restore backups to a volume.

For more information on how backups work, refer to the xref:introduction/concepts.adoc#_3_backups_and_secondary_storage[concepts] section.

When you restore a backup, it creates a volume of the same name by default. If a volume with the same name as the backup already exists, the backup will not be restored.

To restore a backup,

. Navigate to the *Backup.* menu
. Select the backup(s) you wish to restore and click *Restore Latest Backup.*
. In the *Name* field, select the volume you wish to restore.
. Click *OK.*

You can then create the PV/PVC from the volume after restoring a volume from a backup. Here you can specify the `storageClassName` or leave it empty to use the `storageClassName` inherited from the PVC of the backup volume. The `StorageClass` should be already in the cluster to prevent any further issue.

*Result:* The restored volume is available on the *Volume* page.
