= Volume Snapshots and Backups
:current-version: {page-component-version}

____
In earlier versions, Longhorn used a "blocking way" for communication with the remote backup target. Consequently, there are some involuntary factors impacting the functions relying on remote backup target. For example, network latency, listing backups, or causing further cascading problems after the backup target operation.
____

____
In current versions, Longhorn started using an asynchronous backup operations to resolve the aforementioned issues in the previous version.

* To do this, create the backup cluster custom resources first, then perform the following snapshot and backup operations to the remote backup target.
* Once the backup creation is completed, asynchronously pull the state of backup volumes and backups from the remote backup target. Then, update the status of the corresponding cluster custom resources.

This enhancement is scalable for the backup query to assist with resolving the costly resources caused by the blocking way. This was because all backups are saved as custom resources instead of querying from the remote target directly.

NOTE: After the Longhorn upgrade, if a volume has not been upgraded to the latest Longhorn engine (≥v1.2.0). When creating a backup, it will have the intermediate transition state of the name of the created backup (due to the different backup name handling in the latest longhorn version ≥ v1.2.0). Longhorn will then ensure the backup is synced with the remote backup target and the backup will be updated to the final correct state with the remote backup target is the single source of truth. To upgrade the Longhorn engine, refer to xref:upgrades/longhorn-components/manually-upgrade-engine.adoc[] or xref:upgrades/longhorn-components/auto-upgrade-engine.adoc[].
____

* xref:/snapshots-backups/volume-snapshots-backups/configure-backup-target.adoc[Setting a Backup Target]
* xref:/snapshots-backups/volume-snapshots-backups/create-backup.adoc[Create a Backup]
* xref:/snapshots-backups/volume-snapshots-backups/restore-volume-from-backup.adoc[Restore from a Backup]
* xref:/snapshots-backups/volume-snapshots-backups/restore-volume-statefulset.adoc[Restoring Volumes for Kubernetes StatefulSets]
