= Install {longhorn-product-name} in an Air-Gapped Environment
:current-version: {page-component-version}
:doctype: book

{longhorn-product-name} can be installed in an air gapped environment by using a Helm chart, or the Rancher UI.

== Prerequisites

* https://helm.sh/docs/[Helm] v3.0 or later is required.
* Deploy {longhorn-product-name} components images to your own registry.
* Deploy Kubernetes CSI driver components images to your own registry.

== Image Management for Air-Gapped Environments

. **Obtain the list of required images** +
Run the script to download the complete list of all images required for {longhorn-product-name}. The script will generate a `longhorn-images.txt` file containing the list of images.
+
[,bash]
----
#!/usr/bin/env bash
CHART_REF=oci://dp.apps.rancher.io/charts/suse-storage:{current-version}
set -euo pipefail
setopt shwordsplit 2>/dev/null || true
# Check for dependencies
for cmd in yq jq helm tar; do
  if ! command -v "$cmd" >/dev/null 2>&1; then
    echo >&2 "Error: '$cmd' is required but not installed."
    exit 1
  fi
done
tmp_dir=$(mktemp -d)
cleanup() {
  rm -rf "$tmp_dir"
}
trap cleanup EXIT
helm pull "$CHART_REF" --untar --untardir "$tmp_dir"
# Pull and extract chart
helm pull "$CHART_REF" --untar --untardir "$tmp_dir"
# The folder name is just the chart name, not the version
chart_dir="$tmp_dir/suse-storage"
# Extract 'helm.sh/images' annotation and convert to JSON, then print image list (one per line)
yq eval '.annotations."helm.sh/images"' "$chart_dir/Chart.yaml" | yq -o=json eval - | jq -r '.[] | .image' | sort > longhorn-images.txt
----

. **Pull and save {longhorn-product-name} images** + 
{longhorn-product-name} provides the https://raw.githubusercontent.com/longhorn/longhorn/v{current-version}/scripts/save-images.sh[`save-images.sh` script] to quickly pull images listed in the `longhorn-images.txt` file. To pull and save Longhorn images to a `tar.gz` file (for example, `longhorn-images.tar.gz`), run the following commands:
+
[,bash]
----
wget https://raw.githubusercontent.com/longhorn/longhorn/v{current-version}/scripts/save-images.sh
chmod +x save-images.sh
./save-images.sh --image-list longhorn-images.txt --images longhorn-images.tar.gz
----
+
Then, copy the generated `longhorn-images.tar.gz` file to your air-gapped environment. If you do not specify a filename using the `--images` flag, the script will only pull the images to your local Docker image cache without saving them to a file.

. **Load and push {longhorn-product-name} images to your private registry** + 
{longhorn-product-name} provides another script, https://raw.githubusercontent.com/longhorn/longhorn/v{current-version}/scripts/load-images.sh[`load-images.sh` script], to push images to your private container registry. To load images from a `tar.gz` file (for example, `longhorn-images.tar.gz`) and push them to your registry, run the following commands. Replace `<YOUR-PRIVATE-REGISTRY>` with the actual address of your private registry.
+
[,bash]
----
wget https://raw.githubusercontent.com/longhorn/longhorn/v{current-version}/scripts/load-images.sh
chmod +x load-images.sh
./load-images.sh --image-list longhorn-images.txt --images longhorn-images.tar.gz --registry <YOUR-PRIVATE-REGISTRY>
----
+
If you do not specify a `tar.gz` file using the `--images` flag, the script will find images in your local Docker cache and push them to the registry.

. **View script options**: + 
For more options when using these scripts, see their respective `--help` flags:
+
[,bash]
----
./save-images.sh --help
./load-images.sh --help
----

== Using a Helm Chart

. ** Obtain {longhorn-product-name} Chart** +
Obtain the {longhorn-product-name} Chart and decompress the downloaded tarball:
+
[,bash]
----
helm pull longhorn oci://dp.apps.rancher.io/charts/suse-storage:{current-version}
tar -zxf suse-storage-{current-version}.tgz
cd suse-storage
----

. **Configure Image Settings in `values.yaml`** +
After cloning, configure your image settings in the `values.yaml` file based on your chosen method:
+
[cols="1,2a",options="header",width="100%"]
|===
| Method
| Configuration Details

| Using Default Image Names
|
In `values.yaml`, specify your `Private registry URL`. If the registry requires authentication, also specify `Private registry user`, `Private registry password`, and `Private registry secret`. {longhorn-product-name} will automatically generate a secret with that information and use it to pull images from your private registry.

[,yaml]
----
defaultSettings:
  registrySecret: <SECRET_NAME>

privateRegistry:
    registryUrl: <REGISTRY_URL>
    registryUser: <REGISTRY_USER>
    registryPasswd: <REGISTRY_PASSWORD>
    registrySecret: <REGISTRY_SECRET_NAME>
----

| Using Custom Image Names
|
In `values.yaml`, configure the image settings for each component.

[NOTE]
====
Do not include the private registry prefix (for example, `example.com/username/`); it will be added automatically. If your image is `example.com/username/longhorn-manager`, use `username/longhorn-manager` in the following charts.
====

Specify the `repository` and `tag` for each {longhorn-product-name} component image:

[,yaml]
----
  image:
    longhorn:
      engine:
        repository: containers/longhorn-engine
        tag: <LONGHORN_ENGINE_IMAGE_TAG>
      manager:
        repository: containers/longhorn-manager
        tag: <LONGHORN_MANAGER_IMAGE_TAG>
      ui:
        repository: containers/longhorn-ui
        tag: <LONGHORN_UI_IMAGE_TAG>
      instanceManager:
        repository: containers/longhorn-instance-manager
        tag: <LONGHORN_INSTANCE_MANAGER_IMAGE_TAG>
      shareManager:
        repository: containers/longhorn-share-manager
        tag: <LONGHORN_SHARE_MANAGER_IMAGE_TAG>
----
Specify the `repository` and `tag` for CSI Driver components images:

[,yaml]
----
    csi:
      attacher:
        repository: containers/csi-attacher
        tag: <CSI_ATTACHER_IMAGE_TAG>
      provisioner:
        repository: containers/csi-provisioner
        tag: <CSI_PROVISIONER_IMAGE_TAG>
      nodeDriverRegistrar:
        repository: containers/csi-node-driver-registrar
        tag: <CSI_NODE_DRIVER_REGISTRAR_IMAGE_TAG>
      resizer:
        repository: containers/csi-resizer
        tag: <CSI_RESIZER_IMAGE_TAG>
      snapshotter:
        repository: containers/csi-snapshotter
        tag: <CSI_SNAPSHOTTER_IMAGE_TAG>
----
Finally, specify your `Private registry URL`. If the registry requires authentication, specify `Private registry user`, `Private registry password`, and `Private registry secret`. {longhorn-product-name} will automatically generate a secret with that information and use it to pull images from your private registry.

[,yaml]
----
  defaultSettings:
    registrySecret: <SECRET_NAME>

  privateRegistry:
      registryUrl: <REGISTRY_URL>
      registryUser: <REGISTRY_USER>
      registryPasswd: <REGISTRY_PASSWORD>
----
|===

. **Install {longhorn-product-name}** +
Install {longhorn-product-name} by running the following command in the cloned directory:
+
[,bash]
----
helm install longhorn --namespace longhorn-system --create-namespace ./
----


=== Helm/Rancher Installation: `longhorn-manager` DaemonSet Fails Due to Missing Private Registry Secret

If you are using a private container registry and forgot to submit a Kubernetes secret for authentication, the `longhorn-manager` DaemonSet will fail to deploy.

==== Steps to Resolve

. *Create the Kubernetes Secret* + 
Replace the placeholder values with your actual registry credentials:
+ 
[,shell]
----
kubectl -n longhorn-system create secret docker-registry <SECRET_NAME> \
  --docker-server=<REGISTRY_URL> \
  --docker-username=<REGISTRY_USER> \
  --docker-password=<REGISTRY_PASSWORD>
----

. *Create the `registry-secret` Setting Object* +
Create a YAML file (for example, `registry-secret.yml`) with the following content:
+
[,yaml]
----
apiVersion: longhorn.io/v1beta2
kind: Setting
metadata:
  name: registry-secret
  namespace: longhorn-system
value: <SECRET_NAME>
----
+
Apply the configuration:
+
[,shell]
----
kubectl apply -f registry-secret.yml
----

. *Reinstall {longhorn-product-name}* +
Uninstall and reinstall {longhorn-product-name} to apply the changes:
+
[,shell]
----
helm uninstall longhorn --namespace longhorn-system ./
helm install longhorn --namespace longhorn-system ./
----
