= Installation
:revdate: 2025-07-24
:page-revdate: {revdate}
:description: Install SUSE® Storage on Kubernetes
:doctype: book
:current-version: {page-component-version}

NOTE: This quick installation guide uses some configurations which are not for production usage.
Please see xref:installation-setup/best-practices.adoc[Best Practices] for how to configure {longhorn-product-name} for production usage.

{longhorn-product-name} can be installed on a Kubernetes cluster in several ways:

* xref:installation-setup/installation/install-using-rancher.adoc[]
* xref:installation-setup/installation/install-using-helm.adoc[]
* xref:installation-setup/installation/install-using-fleet.adoc[]
* xref:installation-setup/installation/install-using-flux.adoc[]
* xref:installation-setup/installation/install-using-argocd.adoc[]

To install {longhorn-product-name} in an air-gapped environment, refer to xref:installation-setup/installation/airgapped-environment.adoc[Air-Gapped Installation].

For information on customizing the default settings, refer to xref:longhorn-system/customize-default-settings.adoc[Customizing Default Settings].

For information on deploying {longhorn-product-name} on specific nodes and rejecting general workloads for those nodes, refer to the section on xref:nodes/taints-tolerations.adoc[Taints and Tolerations].
