= Propriedade e PermissĂŁo de PVC
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2025-10-22
:page-revdate: {revdate}
:current-version: {page-component-version}

O Kubernetes suporta os 2 https://kubernetes.io/docs/concepts/storage/persistent-volumes/#volume-mode[modos de volume] para PVC: Sistema de arquivos e bloco.
Quando um pod define o contexto de seguranĂ§a e solicita um PVC Longhorn, o Kubernetes lidarĂˇ com a modificaĂ§ĂŁo de propriedade e permissĂŁo do PVC de maneira diferente com base no modo de volume.

== PVC Longhorn com Modo de Volume em Sistema de Arquivos

Como o driver CSI Longhorn `csiDriver.spec.fsGroupPolicy` estĂˇ definido como `ReadWriteOnceWithFSType`, o Kubelet tenta alterar a propriedade e a permissĂŁo de um PVC Longhorn da seguinte maneira:

. Verificar `pod.spec.securityContext.fsGroup`.
 ** Se nĂŁo estiver vazio, continue para a prĂłxima etapa.
 ** Se estiver vazio, o Kubelet nĂŁo tenta alterar a propriedade e a permissĂŁo para o volume.
. Verificar `fsType` do PV e `accessModes` do PVC.
 ** Se o `fsType` do PV estiver definido e a lista `accessModes` do PVC contiver `ReadWriteOnce`, continue para a prĂłxima etapa.
 ** Caso contrĂˇrio, o Kubelet nĂŁo tenta alterar a propriedade e a permissĂŁo para o volume.
. Verificar `pod.spec.securityContext.fsGroupChangePolicy`.
 ** Se o `pod.spec.securityContext.fsGroupChangePolicy` estiver definido como `always` ou vazio, o Kubelet realiza as seguintes aĂ§Ăµes:
  *** Garante que todos os processos dos contĂŞineres dentro do pod sejam parte do grupo suplementar id `pod.spec.securityContext.fsGroup`
  *** Garante que quaisquer novos arquivos criados no volume estarĂŁo no grupo id `pod.spec.securityContext.fsGroup`
  *** Altera recursivamente a permissĂŁo e a propriedade do volume para ter o mesmo grupo id que `pod.spec.securityContext.fsGroup` toda vez que o volume for montado
 ** Se o `pod.spec.securityContext.fsGroupChangePolicy` estiver definido como `OnRootMismatch`:
  *** Se a raiz do volume jĂˇ tiver as permissĂµes corretas (ou seja, pertencer ao grupo id como `pod.spec.securityContext.fsGroup`), a alteraĂ§ĂŁo recursiva de permissĂŁo e propriedade serĂˇ pulada.
  *** Caso contrĂˇrio, o Kubelet altera recursivamente a permissĂŁo e a propriedade do volume para ter o mesmo grupo id que `pod.spec.securityContext.fsGroup`

Para obter mais informaĂ§Ăµes, consulte:

* https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#configure-volume-permission-and-ownership-change-policy-for-pods
* https://github.com/longhorn/longhorn/issues/2131#issuecomment-778897129

== Longhorn PVC com Modo de Volume em Bloco

Para PVC com modo de volume em bloco, o Kubelet nunca tenta alterar a permissĂŁo e a propriedade do dispositivo de bloco ao disponibilizĂˇ-lo dentro do contĂŞiner.
VocĂŞ deve definir o ID de grupo correto no `pod.spec.securityContext` para que o pod possa ler e escrever no dispositivo de bloco ou executar o contĂŞiner como [root].

Por padrĂŁo, o Longhorn coloca o dispositivo de bloco no ID de grupo 6, que geralmente estĂˇ associado ao grupo "disco".
Portanto, os pods que usam Longhorn PVC com modo de volume em bloco devem definir o ID de grupo 6 no `pod.spec.securityContext` ou executar como [root].
Por exemplo:

. Pod que define o ID de grupo 6 no `pod.spec.securityContext`
+
[subs="+attributes",yaml]
----
 apiVersion: v1
 kind: PersistentVolumeClaim
 metadata:
   name: longhorn-block-vol
 spec:
   accessModes:
     - ReadWriteOnce
   volumeMode: Block
   storageClassName: longhorn
   resources:
     requests:
       storage: 2Gi
 ---
 apiVersion: v1
 kind: Pod
 metadata:
   name: block-volume-test
   namespace: default
 spec:
   securityContext:
     runAsGroup: 1000
     runAsNonRoot: true
     runAsUser: 1000
     supplementalGroups:
     - 6
   containers:
     - name: block-volume-test
       image: ubuntu:20.04
       command: ["sleep", "360000"]
       imagePullPolicy: IfNotPresent
       volumeDevices:
         - devicePath: /dev/longhorn/testblk
           name: block-vol
   volumes:
     - name: block-vol
       persistentVolumeClaim:
         claimName: longhorn-block-vol
----

. Pod que executa como [root]
+
[subs="+attributes",yaml]
----
 apiVersion: v1
 kind: PersistentVolumeClaim
 metadata:
   name: longhorn-block-vol
 spec:
   accessModes:
     - ReadWriteOnce
   volumeMode: Block
   storageClassName: longhorn
   resources:
     requests:
       storage: 2Gi
 ---
 apiVersion: v1
 kind: Pod
 metadata:
   name: block-volume-test
   namespace: default
 spec:
   containers:
     - name: block-volume-test
       image: ubuntu:20.04
       command: ["sleep", "360000"]
       imagePullPolicy: IfNotPresent
       volumeDevices:
         - devicePath: /dev/longhorn/testblk
           name: block-vol
   volumes:
     - name: block-vol
       persistentVolumeClaim:
         claimName: longhorn-block-vol
----
