= OCP/OKD Support
:weight: 4
:current-version: {page-component-version}

To deploy Longhorn on a cluster provisioned with OpenShift 4.x, some additional configurations are required.

NOTE: OKD currently does not support the ARM platform. For more information, see the https://www.okd.io/crc/?h=arm[OKD website] and https://github.com/okd-project/okd/issues/1165[GitHub issue #1165] (_OKD in ARM platform_).

* <<install-longhorn,Install Longhorn>>
 ** <<install-with-helm,Install With Helm>>
 ** <<install-with-oc-command,Install With `oc` Command>>
* <<prepare-a-customized-default-longhorn-disk-optional,Prepare A Customized Default Longhorn Disk (Optional)>>
 ** <<add-an-extra-disk-to-longhorn-storage,Add An Extra Disk to Longhorn Storage>>
  *** <<create-filesystem-for-the-device,Create Filesystem For The Device>>
  *** <<mounting-the-device-on-boot-with-machineconfig-crd,Mounting The Device On Boot with MachineConfig CRD>>
  *** <<label-and-annotate-the-node,Label and Annotate The Node>>
* <<reference,Reference>>
* <<main-contributor,Main Contributor>>

== Install Longhorn

=== Install With Helm

Please refer to this section xref:deploy/install/install-with-helm.adoc[Install with Helm] first.

And then install Longhorn with setting *_openshift.enabled_* true:

[subs="+attributes",bash]
----
  helm install longhorn longhorn/longhorn --namespace longhorn-system --create-namespace --set openshift.enabled=true
----

=== Install With `oc` Command

You can install Longhorn on https://www.okd.io/[OKD] clusters using the following command:

[subs="+attributes",shell]
----
    oc apply -f https://raw.githubusercontent.com/longhorn/longhorn/v{current-version}/deploy/longhorn-okd.yaml
----

One way to monitor the progress of the installation is to watch pods being created in the `longhorn-system` namespace:

[subs="+attributes",shell]
----
    oc get pods \
    --namespace longhorn-system \
    --watch
----

For more information, see xref:deploy/install/install-with-kubectl.adoc[Install with Kubectl].

== Prepare A Customized Default Longhorn Disk (Optional)

To understand more about configuring the disks for Longhorn, please refer to the section xref:nodes-and-volumes/nodes/default-disk-and-node-config.adoc#_launch_longhorn_with_multiple_disks[Configuring Defaults for Nodes and Disks]

Longhorn will use the directory `/var/lib/longhorn` as default storage mount point and that means Longhorn use the root device as the default storage. If you don't want to use the root device as the Longhorn storage, set *_defaultSettings.createDefaultDiskLabeledNodes_* true when installing Longhorn by helm:

[,txt]
----
--set defaultSettings.createDefaultDiskLabeledNodes=true
----

And then add another device formatted to Longhorn storage

=== Add An Extra Disk to Longhorn Storage

==== Create Filesystem For The Device

Create the filesystem on the device with the label `longhorn` on the storage node. Get into the node by oc command:

[subs="+attributes",bash]
----
oc get nodes --no-headers | awk '{print $1}'
oc debug node/${NODE_NAME} -t -- chroot /host bash
----

Check if the device is present and format it with Longhorn label:

[subs="+attributes",bash]
----
lsblk
sudo mkfs.ext4 -L longhorn /dev/${DEVICE_NAME}
----

==== Mounting The Device On Boot with MachineConfig CRD

The secondary drive needs to be mounted automatically when node boots up by the `MachineConfig` that can be created and deployed by:

[subs="+attributes",bash]
----
cat <<EOF >>auto-mount-machineconfig.yaml
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 71-mount-storage-worker
spec:
  config:
    ignition:
      version: 3.2.0
    systemd:
      units:
        - name: var-mnt-longhorn.mount
          enabled: true
          contents: |
            [Unit]
            Before=local-fs.target
            [Mount]
            # Example mount point, you can change it to where you like for each device.
            Where=/var/mnt/longhorn
            What=/dev/disk/by-label/longhorn
            Options=rw,relatime,discard
            [Install]
            WantedBy=local-fs.target
EOF

oc apply -f auto-mount-machineconfig.yaml
----

==== Label and Annotate The Node

Please refer to the section xref:nodes-and-volumes/nodes/default-disk-and-node-config.adoc#_customizing_default_disks_for_new_nodes[Customizing Default Disks for New Nodes] to label and annotate storage node on where your device is by oc commands:

[subs="+attributes",bash]
----
oc get nodes --no-headers | awk '{print $1}'

oc annotate node ${NODE_NAME} --overwrite node.longhorn.io/default-disks-config='[{"path":"/var/mnt/longhorn","allowScheduling":true}]'
oc label node ${NODE_NAME} --overwrite node.longhorn.io/create-default-disk=config
----

NOTE: You might need to reboot the node to validate the modified configuration.

== Reference

* https://github.com/longhorn/longhorn/pull/5004[OCP/OKD Documentation and Helm Support]
* https://www.okd.io/[OKD Official Website]
* https://docs.okd.io/latest/welcome/index.html[OKD Official Documentation Website]
* https://github.com/openshift/oauth-proxy/blob/master/contrib/sidecar.yaml[oauth-proxy]

== Main Contributor

* https://github.com/ArthurVardevanyan[@ArthurVardevanyan]
