= Fehlerbehebung
:revdate: 2025-06-27
:page-revdate: {revdate}
:aliases: ["/spdk/troubleshooting.md"]
:current-version: {page-component-version}

== Installation

=== Fehler "Paket 'linux-modules-extra-x.x.x-x-generic' hat keinen Installationskandidaten" während der Installation auf Debian-Maschinen

Für Debian-Maschinen, wenn Sie Fehler ähnlich den folgenden beim Installieren von zusätzlichen Linux-Kernel-Modulen feststellen, müssen Sie eine verfügbare Version auf den pkg-Sammlungswebseiten wie https://pkgs.org/search/?q=linux-modules-extra[dieser] finden, anstatt sich direkt auf `uname -r` zu verlassen:

[subs="+attributes",log]
----
apt install -y linux-modules-extra-`uname -r`
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package linux-modules-extra-5.15.0-67-generic is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'linux-modules-extra-5.15.0-67-generic' has no installation candidate
----

Zum Beispiel, für Ubuntu 22.04, ist eine gültige Version `linux-modules-extra-5.15.0-76-generic`:

[subs="+attributes",shell]
----
apt update -y
apt install -y linux-modules-extra-5.15.0-76-generic
----

== Festplatte

=== Fehler "Ungültiges Argument" im Festplattensstatus nach Hinzufügen einer Blocktyp-Festplatte

Nach dem Hinzufügen einer Blocktyp-Festplatte zeigt der Festplattensstatus Fehlermeldungen an:

----
Disk disk-1(/dev/nvme1n1) on node dereksu-ubuntu-pool1-bf77ed93-2d2p9 is not ready:
failed to generate disk config: error: rpc error: code = Internal desc = rpc error: code = Internal
desc = failed to add block device: failed to create AIO bdev: error sending message, id 10441,
method bdev_aio_create, params {disk-1 /host/dev/nvme1n1 4096}: {"code": -22,"message": "Invalid argument"}
----

Überprüfen Sie als Nächstes die Protokollnachricht des Instance-Manager-Pods auf demselben Knoten. Wenn das Protokoll Folgendes zeigt:

----
[2023-06-29 08:51:53.762597] bdev_aio.c: 762:create_aio_bdev: *WARNING*: Specified block size 4096 does not match auto-detected block size 512
[2023-06-29 08:51:53.762640] bdev_aio.c: 788:create_aio_bdev: *ERROR*: Disk size 100000000000 is not a multiple of block size 4096
----

Diese Nachrichten zeigen an, dass die Größe Ihrer Festplatte kein Vielfaches der Blockgröße 4096 ist und vom Longhorn-System nicht unterstützt wird.

Um dieses Problem zu lösen, können Sie die folgenden Schritte ausführen

. Entfernen Sie die neu hinzugefügte Blocktyp-Festplatte vom Knoten.
. Partitionieren Sie die Blocktyp-Festplatte mit dem `fdisk` Dienstprogramm und stellen Sie sicher, dass die Partitionsgröße ein Vielfaches der Blockgröße 4096 ist.
. Fügen Sie die partitionierte Festplatte dem Longhorn-Knoten hinzu.
