= Volume Recovery
:current-version: {page-component-version}

{longhorn-product-name} provides two mechanisms for maintaining volume functionality in a variety of situations.

== Automatic Workload Pod Deletion

This recovery mechanism is enabled by the setting xref:longhorn-system/settings.adoc#_automatically_delete_workload_pod_when_the_volume_is_detached_unexpectedly[_Automatically Delete Workload Pod when The Volume Is Detached Unexpectedly_].

When one of the following situations occurs, {longhorn-product-name} automatically attempts to delete workload pods that are managed by a controller (for example, Deployment, StatefulSet, or DaemonSet). After deletion, the controller restarts the workload pod and Kubernetes handles volume reattachment and remounting.

. A volume was unexpectedly detached, possibly because of a https://github.com/longhorn/longhorn/issues/703[Kubernetes upgrade], https://github.com/longhorn/longhorn/issues/686[container runtime reboot], network connectivity issue, or volume engine crash.
. A volume was automatically salvaged after all replicas became faulty, possibly because of a network connectivity issue. {longhorn-product-name} attempts to identify the usable replicas and uses them for the volume.
. An error occurred on a Share Manager pod that uses an RWX volume.

If you want to prevent {longhorn-product-name} from automatically deleting workload pods, disable the setting xref:longhorn-system/settings.adoc#_automatically_delete_workload_pod_when_the_volume_is_detached_unexpectedly[_Automatically Delete Workload Pod when The Volume Is Detached Unexpectedly_] on the {longhorn-product-name} UI.

{longhorn-product-name} does not delete pods without a controller because such pods cannot be restarted after deletion. To recover volumes that are unexpectedly detached, you must manually delete and restart the pods without a controller.

== Automatic Volume Remounting

This recovery mechanism is not controlled by any specific setting.

The state of a volume can change to read-only when IO errors occur. IO errors can be caused by a variety of issues, including the following:

* Network disconnection: Interrupted connection between the engine and replicas.
* High disk latency: Significant delay in the transfer of data between a replica and the corresponding disk.

{longhorn-product-name} checks the state of the volume's global mount point every 10 seconds. When the volume's filesystem changes to read-only, {longhorn-product-name} updates the condition to the volume's data engine. {longhorn-product-name} then automatically attempts to remount the global mount point on the host to change the state back to read-write. Upon successful remounting, the workload pods continue functioning without disruption. However, if the mount point becomes write-protected and {longhorn-product-name} fails to remount the mount point, you may still need to manually recreate the workload to force it reattach and remount the volume.

NOTE: This mechanism might not work in some situations. For example, when the volume's data engine crashes, {longhorn-product-name} automatically detaches and reattaches the volume. The filesystem changes to read-only in this case. {longhorn-product-name} will detect the read-only mode and update the state, but <<_automatic_volume_remounting,Automatic Volume Remounting>> cannot change it back to read_write because the device is now write_protected. In this case, you can only rely on the <<_automatic_workload_pod_deletion,Automatic Workload Pod Deletion>> mechanism, which enables volume remounting after the workload pod is recreated.

== Summary

<<_automatic_workload_pod_deletion,Automatic Workload Pod Deletion>> is triggered when unexpected failures happen. The controller deletes and then restarts the workload pod, and Kubernetes handles volume reattachment and remounting. The process may cause interruptions to the workload. If you want to prevent {longhorn-product-name} from automatically deleting workload pods, disable the setting xref:longhorn-system/settings.adoc#_automatically_delete_workload_pod_when_the_volume_is_detached_unexpectedly[_Automatically Delete Workload Pod when The Volume Is Detached Unexpectedly_] on the {longhorn-product-name} UI.

<<_automatic_volume_remounting,Automatic Volume Remounting>> is triggered when the volume's filesystem changes to read-only. {longhorn-product-name} remounts the global mount point on the host to change the state back to read-write.
