= Personalizar Configurações Padrão
:revdate: 2025-06-29
:page-revdate: {revdate}
:experimental:
:current-version: {page-component-version}

Você pode personalizar as configurações padrão de {longhorn-product-name} durante a instalação ou fazer upgrade. Você pode especificar, por exemplo, `Create Default Disk With Node Labeled` e `Default Data Path` antes de iniciar {longhorn-product-name}.

[NOTE]
====
Ao usar o arquivo YAML de Implantação do Longhorn ou o Helm para instalação, atualização ou fazer upgrade, se o valor de uma configuração padrão for uma string vazia e válida, a configuração padrão será limpa em {longhorn-product-name}. Caso contrário, {longhorn-product-name} ignorará os valores inválidos e não atualizará os valores padrão.
====

== Instalação

=== Usando a interface do Rancher

Na visualização do projeto no Rancher, vá para menu:Apps && Marketplace[Longhorn > Instalar > Próximo > Editar Opções > Configurações Padrão do Longhorn > Personalizar Configurações Padrão] e edite as configurações antes de instalar o app.

=== Usando o Arquivo YAML de Implantação do Longhorn

. Baixe o repositório do longhorn:
+
[subs="+attributes",shell]
----
git clone https://github.com/longhorn/longhorn.git
----

. Modifique o mapa de configuração chamado `longhorn-default-setting` no arquivo YAML `longhorn/deploy/longhorn.yaml`.
+
No exemplo abaixo, os usuários personalizam as configurações padrão, backup-target, backup-target-credential-secret e default-data-path.
 Quando a configuração está ausente ou tem um símbolo `#` à frente, a configuração padrão usará o valor padrão em {longhorn-product-name} ou os valores personalizados configurados anteriormente.
+
[subs="+attributes",yaml]
----
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: longhorn-default-setting
  namespace: longhorn-system
data:
  default-setting.yaml: |-
    backup-target: s3://backupbucket@us-east-1/backupstore
    backup-target-credential-secret: minio-secret
    #allow-recurring-job-while-volume-detached:
    #create-default-disk-labeled-nodes:
    default-data-path: /var/lib/longhorn-example/
    #replica-soft-anti-affinity:
    #replica-auto-balance:
    #storage-over-provisioning-percentage:
    #storage-minimal-available-percentage:
    #upgrade-checker:
    #upgrade-responder-url:
    #default-replica-count:
    #default-data-locality:
    #default-longhorn-static-storage-class:
    #backupstore-poll-interval:
    #taint-toleration:
    #system-managed-components-node-selector:
    #priority-class:
    #auto-salvage:
    #auto-delete-pod-when-volume-detached-unexpectedly:
    #disable-scheduling-on-cordoned-node:
    #replica-zone-soft-anti-affinity:
    #replica-disk-soft-anti-affinity:
    #node-down-pod-deletion-policy:
    #node-drain-policy:
    #replica-replenishment-wait-interval:
    #concurrent-replica-rebuild-per-node-limit:
    #disable-revision-counter:
    #system-managed-pods-image-pull-policy:
    #allow-volume-creation-with-degraded-availability:
    #auto-cleanup-system-generated-snapshot:
    #concurrent-automatic-engine-upgrade-per-node-limit:
    #backing-image-cleanup-wait-interval:
    #backing-image-recovery-wait-interval:
    #guaranteed-instance-manager-cpu:
    #kubernetes-cluster-autoscaler-enabled:
    #orphan-resource-auto-deletion:
    #storage-network:
    #recurring-successful-jobs-history-limit:
    #recurring-failed-jobs-history-limit:
---
----

=== Usando o Helm

[NOTE]
====
Use o Helm 3 ao instalar e fazer upgrade de {longhorn-product-name}. O Helm 2 não é https://helm.sh/blog/helm-2-becomes-unsupported/[mais suportado].
====

Use o comando Helm com a flag `--set` para modificar as configurações padrão. Por exemplo:

[subs="+attributes",shell]
----
helm install longhorn longhorn/longhorn \
  --namespace longhorn-system \
  --create-namespace \
  --set defaultSettings.taintToleration="key1=value1:NoSchedule; key2:NoExecute"
----

Você também pode fornecer uma cópia do arquivo `values.yaml` com as configurações padrão modificadas para a flag `--values` ao executar o comando Helm:

. Obtenha uma cópia do arquivo `values.yaml` do GitHub:
+
[subs="+attributes",shell]
----
curl -Lo values.yaml https://raw.githubusercontent.com/longhorn/charts/master/charts/longhorn/values.yaml
----

. Modifique as configurações padrão no arquivo YAML. Veja a seguir um exemplo de trecho de `values.yaml`:
+
Quando a configuração está ausente ou tem um símbolo `#` à frente, a configuração padrão usará o valor padrão em {longhorn-product-name} ou os valores personalizados configurados anteriormente.
+
[subs="+attributes",yaml]
----
defaultSettings:
  backupTarget: s3://backupbucket@us-east-1/backupstore
  backupTargetCredentialSecret: minio-secret
  createDefaultDiskLabeledNodes: true
  defaultDataPath: /var/lib/longhorn-example/
  replicaSoftAntiAffinity: false
  storageOverProvisioningPercentage: 600
  storageMinimalAvailablePercentage: 15
  upgradeChecker: false
  defaultReplicaCount: 2
  defaultDataLocality: disabled
  defaultLonghornStaticStorageClass: longhorn-static-example
  backupstorePollInterval: 500
  taintToleration: key1=value1:NoSchedule; key2:NoExecute
  systemManagedComponentsNodeSelector: "label-key1:label-value1"
  priorityClass: high-priority
  autoSalvage: false
  disableSchedulingOnCordonedNode: false
  replicaZoneSoftAntiAffinity: false
  replicaDiskSoftAntiAffinity: false
  volumeAttachmentRecoveryPolicy: never
  nodeDownPodDeletionPolicy: do-nothing
  guaranteedInstanceManagerCpu: 15
  orphanAutoDeletion: ""
  orphanResourceAutoDeletionGracePeriod: 300
----

. Execute o Helm com `values.yaml`:
+
[subs="+attributes",shell]
----
helm install longhorn longhorn/longhorn \
  --namespace longhorn-system \
  --create-namespace \
  --values values.yaml
----

Para mais informações sobre como usar o helm, veja a seção xref:installation-setup/installation/install-using-helm.adoc[instalar {longhorn-product-name} com o Helm].

=== Usando o Controlador Helm

No arquivo YAML do HelmChart, adicione linhas ao spec.set com as configurações desejadas:

[,yaml]
----
spec:
  ...
  set:
    defaultSettings.priorityClass: system-node-critical
    defaultSettings.replicaAutoBalance: least-effort
    defaultSettings.storageOverProvisioningPercentage: "200"
    persistence.defaultClassReplicaCount: "2"
----

=== Usando o Controlador Helm

No arquivo YAML do HelmChart, adicione linhas a `spec.set` com as configurações desejadas:

[,yaml]
----
spec:
  ...
  set:
    defaultSettings.priorityClass: system-node-critical
    defaultSettings.replicaAutoBalance: least-effort
    defaultSettings.storageOverProvisioningPercentage: "200"
    persistence.defaultClassReplicaCount: "2"
----

== Atualizar configurações

=== Usando a interface do usuário {longhorn-product-name}

Recomendamos usar a interface do usuário {longhorn-product-name} para alterar a configuração {longhorn-product-name} no cluster existente. Isso tornaria a configuração persistente.

=== Usando a interface do Rancher

Na visualização do projeto no Rancher, vá para menu:Apps && Marketplace[Longhorn > Fazer upgrade > Próximo > Editar Opções > Configurações Padrão do Longhorn > Personalizar Configurações Padrão] e edite as configurações antes de fazer upgrade do app para a versão atual {longhorn-product-name}.

=== Usando o Kubectl

Se você preferir atualizar a configuração pela linha de comando, use `kubectl`. Para evitar colisões com outros CRDs, não use o simples `settings`. Em vez disso, use `settings.longhorn.io` ou `lhs`.

[subs="+attributes",shell]
----
kubectl edit settings.longhorn.io <SETTING-NAME> -n longhorn-system
----

=== Usando o Helm

Modifique as configurações padrão no arquivo YAML conforme descrito em <<_using_helm,Instalação Limpa > Usando o Helm>> e, em seguida, atualize as configurações usando

----
helm upgrade longhorn longhorn/longhorn --namespace longhorn-system --values ./values.yaml --version `helm list -n longhorn-system -o json | jq -r .'[0].app_version'`
----

== Upgrade

=== Usando a interface do Rancher

Na visualização do projeto no Rancher, vá para menu:Apps && Marketplace[Longhorn > Fazer upgrade > Próximo > Editar Opções > Configurações Padrão do Longhorn > Personalizar Configurações Padrão] e edite as configurações antes de fazer upgrade do app.

=== Usando o Arquivo YAML de Implantação do Longhorn

Modifique o mapa de configuração chamado `longhorn-default-setting` no arquivo YAML `longhorn/deploy/longhorn.yaml` conforme descrito em <<_using_the_longhorn_deployment_yaml_file,Instalação Limpa > Usando o Arquivo YAML de Implantação do Longhorn>> e, em seguida, faça upgrade do sistema Longhorn usando `kubectl`.

=== Usando o Helm

Modifique as configurações padrão no arquivo YAML conforme descrito em <<_using_helm,Instalação Limpa > Usando o Helm>> e, em seguida, faça upgrade do sistema Longhorn usando `helm upgrade`.

== Histórico

Disponível desde a v1.3.0 (https://github.com/longhorn/longhorn/issues/2570[Referência])
