= Grupos de Nós Gerenciados no Azure Kubernetes Service (AKS)
:revdate: 2025-06-27
:page-revdate: {revdate}
:current-version: {page-component-version}

Veja https://docs.microsoft.com/en-us/azure/aks/use-multiple-node-pools[Criar e gerenciar múltiplos pools de nós para um cluster no Azure Kubernetes Service (AKS)] para mais informações.

A seguir, há um exemplo de como substituir os nós do cluster por um novo tamanho de armazenamento.

== Expansão de Armazenamento

O AKS não suporta disco adicional em seu https://docs.microsoft.com/en-us/azure/templates/Microsoft.ContainerService/2022-01-01/managedclusters?tabs=bicep#template-format[template]. É possível a anexação manual de disco. Então, o dispositivo bruto precisa ser montado, seja montando manualmente na VM ou durante o lançamento com o CustomScriptExtension que https://docs.microsoft.com/en-us/azure/aks/support-policies#user-customization-of-agent-nodes[não é suportado] no AKS.

. No Longhorn, defina `replica-replenishment-wait-interval` para `0`.
. Adicione um novo pool de nós. Mais tarde, os componentes do Longhorn serão implantados automaticamente nos nós deste pool.
+
----
 AKS_NODEPOOL_NAME_NEW=<new-nodepool-name>
 AKS_RESOURCE_GROUP=<aks-resource-group>
 AKS_CLUSTER_NAME=<aks-cluster-name>
 AKS_DISK_SIZE_NEW=<new-disk-size-in-gb>
 AKS_NODE_NUM=<number-of-nodes>
 AKS_K8S_VERSION=<kubernetes-version>

 az aks nodepool add \
   --resource-group ${AKS_RESOURCE_GROUP} \
   --cluster-name ${AKS_CLUSTER_NAME} \
   --name ${AKS_NODEPOOL_NAME_NEW} \
   --node-count ${AKS_NODE_NUM} \
   --node-osdisk-size ${AKS_DISK_SIZE_NEW} \
   --kubernetes-version ${AKS_K8S_VERSION} \
   --mode System
----

. Usando a interface do Longhorn para desativar o agendamento de disco e solicitar evacuação para nós no antigo pool de nós.
. Cordon e drene os nós do Kubernetes no antigo pool de nós.
+
----
 AKS_NODEPOOL_NAME_OLD=<old-nodepool-name>

 for n in `kubectl get nodes | grep ${AKS_NODEPOOL_NAME_OLD}- | awk '{print $1}'`; do
   kubectl cordon $n && \
   kubectl drain $n --ignore-daemonsets --delete-emptydir-data
 done
----

. Exclua o antigo pool de nós.
+
----
 az aks nodepool delete \
   --cluster-name ${AKS_CLUSTER_NAME} \
   --name ${AKS_NODEPOOL_NAME_OLD} \
   --resource-group ${AKS_RESOURCE_GROUP}
----
