= Integrate SUSE® Storage Metrics into the Rancher Monitoring System
:current-version: {page-component-version}

== About the Rancher Monitoring System

Using Rancher, you can monitor the state and processes of your cluster nodes, Kubernetes components, and software deployments through integration with https://prometheus.io/[Prometheus], a leading open-source monitoring solution.

See https://rancher.com/docs/rancher/v2.x/en/monitoring-alerting/[here] for the instruction about how to deploy/enable the Rancher monitoring system.

== Add Longhorn Metrics to the Rancher Monitoring System

If you are using Rancher to manage your Kubernetes and already enabled Rancher monitoring, you can add Longhorn metrics to Rancher monitoring by simply deploying the following ServiceMonitor:

[subs="+attributes",yaml]
----
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: longhorn-prometheus-servicemonitor
  namespace: longhorn-system
  labels:
    name: longhorn-prometheus-servicemonitor
spec:
  selector:
    matchLabels:
      app: longhorn-manager
  namespaceSelector:
    matchNames:
    - longhorn-system
  endpoints:
  - port: manager
----

Once the ServiceMonitor is created, Rancher will automatically discover all Longhorn metrics.

You can then set up a Grafana dashboard for visualization.

You can import our prebuilt https://grafana.com/grafana/dashboards/13032[Longhorn example dashboard] to have an idea.

You can also set up alerts in Rancher UI.
