= Standard-Einstellungen anpassen
:revdate: 2025-06-29
:page-revdate: {revdate}
:experimental:
:current-version: {page-component-version}

Sie können die Standardeinstellungen von {longhorn-product-name} während der Installation oder des Upgrades anpassen. Sie können beispielsweise `Create Default Disk With Node Labeled` und `Default Data Path` vor dem Start von {longhorn-product-name} angeben.

[NOTE]
====
Wenn Sie die Longhorn-Implementierungs-YAML-Datei oder Helm für die Installation, Aktualisierung oder Upgrade verwenden und der Wert einer Standardeinstellung ein leerer und gültiger String ist, wird diese in {longhorn-product-name} bereinigt. Andernfalls ignoriert {longhorn-product-name} die ungültigen Werte und aktualisiert die Standardwerte nicht.
====

== Installation

=== Verwendung der Rancher-Benutzeroberfläche

Gehen Sie in der Projektansicht in Rancher zu menu:Apps && Marketplace[Longhorn > Installieren > Weiter > Optionen bearbeiten > Longhorn-Standardeinstellungen > Standard-Einstellungen anpassen] und bearbeiten Sie die Einstellungen vor der Installation der App.

=== Verwendung der Longhorn-Implementierungs-YAML-Datei

. Laden Sie das Longhorn-Repository herunter:
+
[subs="+attributes",shell]
----
git clone https://github.com/longhorn/longhorn.git
----

. Ändern Sie die Konfigurationskarte mit dem Namen `longhorn-default-setting` in der YAML-Datei `longhorn/deploy/longhorn.yaml`.
+
Im folgenden Beispiel passen die Benutzer die Standardeinstellungen, das Sicherungsziel, das Sicherungsziel-Anmeldegeheimnis und den Standard-Datenpfad an.
 Wenn die Einstellung fehlt oder ein führendes `#`-Symbol hat, verwendet die Standardeinstellung den Standardwert in {longhorn-product-name} oder die zuvor konfigurierten benutzerdefinierten Werte.
+
[subs="+attributes",yaml]
----
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: longhorn-default-setting
  namespace: longhorn-system
data:
  default-setting.yaml: |-
    backup-target: s3://backupbucket@us-east-1/backupstore
    backup-target-credential-secret: minio-secret
    #allow-recurring-job-while-volume-detached:
    #create-default-disk-labeled-nodes:
    default-data-path: /var/lib/longhorn-example/
    #replica-soft-anti-affinity:
    #replica-auto-balance:
    #storage-over-provisioning-percentage:
    #storage-minimal-available-percentage:
    #upgrade-checker:
    #upgrade-responder-url:
    #default-replica-count:
    #default-data-locality:
    #default-longhorn-static-storage-class:
    #backupstore-poll-interval:
    #taint-toleration:
    #system-managed-components-node-selector:
    #priority-class:
    #auto-salvage:
    #auto-delete-pod-when-volume-detached-unexpectedly:
    #disable-scheduling-on-cordoned-node:
    #replica-zone-soft-anti-affinity:
    #replica-disk-soft-anti-affinity:
    #node-down-pod-deletion-policy:
    #node-drain-policy:
    #replica-replenishment-wait-interval:
    #concurrent-replica-rebuild-per-node-limit:
    #disable-revision-counter:
    #system-managed-pods-image-pull-policy:
    #allow-volume-creation-with-degraded-availability:
    #auto-cleanup-system-generated-snapshot:
    #concurrent-automatic-engine-upgrade-per-node-limit:
    #backing-image-cleanup-wait-interval:
    #backing-image-recovery-wait-interval:
    #guaranteed-instance-manager-cpu:
    #kubernetes-cluster-autoscaler-enabled:
    #orphan-resource-auto-deletion:
    #storage-network:
    #recurring-successful-jobs-history-limit:
    #recurring-failed-jobs-history-limit:
---
----

=== Verwendung von Helm

[NOTE]
====
Verwenden Sie Helm 3 bei der Installation und beim Upgrade von {longhorn-product-name}. Helm 2 wird https://helm.sh/blog/helm-2-becomes-unsupported/[nicht mehr unterstützt].
====

Verwenden Sie den Helm-Befehl mit dem `--set`-Flag, um die Standardeinstellungen zu ändern. Beispiel:

[subs="+attributes",shell]
----
helm install longhorn longhorn/longhorn \
  --namespace longhorn-system \
  --create-namespace \
  --set defaultSettings.taintToleration="key1=value1:NoSchedule; key2:NoExecute"
----

Sie können auch eine Kopie der `values.yaml`-Datei mit den geänderten Standardeinstellungen an das `--values`-Flag übergeben, wenn Sie den Helm-Befehl ausführen:

. Holen Sie sich eine Kopie der `values.yaml`-Datei von GitHub:
+
[subs="+attributes",shell]
----
curl -Lo values.yaml https://raw.githubusercontent.com/longhorn/charts/master/charts/longhorn/values.yaml
----

. Ändern Sie die Standardeinstellungen in der YAML-Datei. Das folgende ist ein Beispielausschnitt von `values.yaml`:
+
Wenn die Einstellung fehlt oder ein führendes `#`-Symbol hat, verwendet die Standardeinstellung den Standardwert in {longhorn-product-name} oder die zuvor konfigurierten benutzerdefinierten Werte.
+
[subs="+attributes",yaml]
----
defaultSettings:
  backupTarget: s3://backupbucket@us-east-1/backupstore
  backupTargetCredentialSecret: minio-secret
  createDefaultDiskLabeledNodes: true
  defaultDataPath: /var/lib/longhorn-example/
  replicaSoftAntiAffinity: false
  storageOverProvisioningPercentage: 600
  storageMinimalAvailablePercentage: 15
  upgradeChecker: false
  defaultReplicaCount: 2
  defaultDataLocality: disabled
  defaultLonghornStaticStorageClass: longhorn-static-example
  backupstorePollInterval: 500
  taintToleration: key1=value1:NoSchedule; key2:NoExecute
  systemManagedComponentsNodeSelector: "label-key1:label-value1"
  priorityClass: high-priority
  autoSalvage: false
  disableSchedulingOnCordonedNode: false
  replicaZoneSoftAntiAffinity: false
  replicaDiskSoftAntiAffinity: false
  volumeAttachmentRecoveryPolicy: never
  nodeDownPodDeletionPolicy: do-nothing
  guaranteedInstanceManagerCpu: 15
  orphanAutoDeletion: ""
  orphanResourceAutoDeletionGracePeriod: 300
----

. Führen Sie Helm mit `values.yaml` aus:
+
[subs="+attributes",shell]
----
helm install longhorn longhorn/longhorn \
  --namespace longhorn-system \
  --create-namespace \
  --values values.yaml
----

Für weitere Informationen zur Verwendung von Helm siehe den Abschnitt xref:installation-setup/installation/install-using-helm.adoc[installiere {longhorn-product-name} mit Helm].

=== Verwendung des Helm-Controllers

Fügen Sie in der HelmChart YAML-Datei Zeilen zu spec.set mit den gewünschten Einstellungen hinzu:

[,yaml]
----
spec:
  ...
  set:
    defaultSettings.priorityClass: system-node-critical
    defaultSettings.replicaAutoBalance: least-effort
    defaultSettings.storageOverProvisioningPercentage: "200"
    persistence.defaultClassReplicaCount: "2"
----

=== Verwendung des Helm Controllers

Fügen Sie in der HelmChart YAML-Datei Zeilen zu `spec.set` mit den gewünschten Einstellungen hinzu:

[,yaml]
----
spec:
  ...
  set:
    defaultSettings.priorityClass: system-node-critical
    defaultSettings.replicaAutoBalance: least-effort
    defaultSettings.storageOverProvisioningPercentage: "200"
    persistence.defaultClassReplicaCount: "2"
----

== Update-Einstellungen

=== Verwendung der {longhorn-product-name} Benutzeroberfläche

Wir empfehlen die Verwendung der {longhorn-product-name} Benutzeroberfläche, um die {longhorn-product-name} Einstellung im bestehenden Cluster zu ändern. Es würde die Einstellung dauerhaft machen.

=== Verwendung der Rancher-Benutzeroberfläche

Gehen Sie in der Projektansicht in Rancher zu menu:Apps && Marketplace[Longhorn-Standardeinstellungen > Upgrade > Weiter > Optionen bearbeiten > Longhorn-Standardeinstellungen > Standardeinstellungen anpassen] und bearbeiten Sie die Einstellungen, bevor Sie die App auf die aktuelle {longhorn-product-name} Version aktualisieren.

=== Verwendung von Kubectl

Wenn Sie die Einstellung lieber über die Befehlszeile aktualisieren möchten, verwenden Sie `kubectl`. Um Kollisionen mit anderen CRDs zu vermeiden, verwenden Sie nicht das einfache `settings`. Verwenden Sie stattdessen `settings.longhorn.io` oder `lhs`.

[subs="+attributes",shell]
----
kubectl edit settings.longhorn.io <SETTING-NAME> -n longhorn-system
----

=== Verwendung von Helm

Ändern Sie die Standardeinstellungen in der YAML-Datei wie in <<_using_helm,Frische Installation > Verwendung von Helm>> beschrieben und aktualisieren Sie dann die Einstellungen mit

----
helm upgrade longhorn longhorn/longhorn --namespace longhorn-system --values ./values.yaml --version `helm list -n longhorn-system -o json | jq -r .'[0].app_version'`
----

== Aufrüsten

=== Verwendung der Rancher-Benutzeroberfläche

Gehen Sie in der Projektansicht in Rancher zu menu:Apps && Marketplace[Longhorn-Standardeinstellungen > Upgrade > Next > Optionen bearbeiten > Longhorn-Standardeinstellungen > Standardeinstellungen anpassen] und bearbeiten Sie die Einstellungen, bevor Sie die App aktualisieren.

=== Verwendung der Longhorn-Implementierungs-YAML-Datei

Ändern Sie die Konfigurationskarte mit dem Namen `longhorn-default-setting` in der YAML-Datei `longhorn/deploy/longhorn.yaml` wie in <<_using_the_longhorn_deployment_yaml_file,Frische Installation > Verwendung der Longhorn-Implementierungs-YAML-Datei>> beschrieben und aktualisieren Sie dann das Longhorn-System mit `kubectl`.

=== Verwendung von Helm

Ändern Sie die Standardeinstellungen in der YAML-Datei wie in <<_using_helm,Frische Installation > Verwendung von Helm>> beschrieben und aktualisieren Sie dann das Longhorn-System mit `helm upgrade`.

== Verlauf

Verfügbar seit v1.3.0 (https://github.com/longhorn/longhorn/issues/2570[Referenz])
