= Migrieren Sie vom Flexvolume-Treiber zu CSI
:revdate: 2025-06-27
:page-revdate: {revdate}
:current-version: {page-component-version}

Der Flexvolume-Treiber wird nicht mehr unterstützt. Sie können vom Flexvolume-Treiber zu CSI migrieren, das die neueste, nicht in den Kubernetes-Kern integrierte Speicher-Schnittstelle darstellt.

____
Beachten Sie, dass Volumes, die mit einem Treiber erstellt und verwendet wurden, von Kubernetes mit dem anderen Treiber nicht erkannt werden. Bitte wechseln Sie den Treiber (z. B. während eines Upgrades) nicht, wenn Sie bereits Volumes mit dem alten Treiber erstellt haben.
____

Stellen Sie sicher, dass Ihre Longhorn-App auf dem neuesten Stand ist. Befolgen Sie das entsprechende Upgrade-Verfahren, bevor Sie fortfahren.

Der Migrationspfad zwischen den Treibern erfordert das Sichern und Wiederherstellen jedes Volumes und verursacht sowohl API-Ausfallzeiten als auch Ausfallzeiten der Arbeitslast. Dies kann ein mühsamer Prozess sein. Erwägen Sie, unwichtige Arbeitslasten mit dem alten Treiber zu löschen, um den Aufwand zu reduzieren.

. xref:snapshots-backups/volume-snapshots-backups/create-backup.adoc[Sichern Sie vorhandene Volumes].
. Navigieren Sie in der Rancher-Benutzeroberfläche zum `Catalog Apps`-Bildschirm, suchen Sie die `Longhorn`-App und klicken Sie auf die `Up to date`-Schaltfläche. Wählen Sie unter `Kubernetes Driver` `flexvolume` aus. Wir empfehlen, `Flexvolume Path` leer zu lassen. Klicken Sie auf `Upgrade`.
. Stellen Sie jedes Volume wieder her. Dieses xref:snapshots-backups/volume-snapshots-backups/restore-volume-statefulset.adoc[Verfahren] ist auf die StatefulSet-Arbeitslast zugeschnitten, aber der Prozess ist für alle Arbeitslasten ungefähr gleich.
