= Install Longhorn Using Helm
:current-version: {page-component-version}

== Prerequisites

* Kubernetes cluster: Ensure that each node fulfills the xref:../../installation-setup/requirements.adoc[installation requirements].
* Your workstation: Install https://helm.sh/docs/[Helm] v3.0 or later.

____
https://github.com/longhorn/longhorn/blob/v{current-version}/scripts/environment_check.sh[This script] can be used to check the Longhorn environment for potential issues.
____

== Installing Longhorn

____
*Note*:

* The initial settings for Longhorn can be found in xref:../../longhorn-system/customize-default-settings.adoc#_using_helm[customized using Helm options or by editing the deployment configuration file.]
* For Kubernetes < v1.25, if your cluster still enables Pod Security Policy admission controller, set the helm value `enablePSP` to `true` to install `longhorn-psp` PodSecurityPolicy resource which allows privileged Longhorn pods to start.
____

. Add the Longhorn Helm repository:
+
[subs="+attributes",shell]
----
helm repo add longhorn https://charts.longhorn.io
----

. Fetch the latest charts from the repository:
+
[subs="+attributes",shell]
----
helm repo update
----

. Install Longhorn in the `longhorn-system` namespace.
+
[subs="+attributes",shell]
----
 helm install longhorn longhorn/longhorn --namespace longhorn-system --create-namespace --version {current-version}
----

. To confirm that the deployment succeeded, run:
+
[subs="+attributes",bash]
----
 kubectl -n longhorn-system get pod
----
+
The result should look like the following:
+
[subs="+attributes",bash]
----
 NAME                                                READY   STATUS    RESTARTS   AGE
 longhorn-ui-b7c844b49-w25g5                         1/1     Running   0          2m41s
 longhorn-manager-pzgsp                              1/1     Running   0          2m41s
 longhorn-driver-deployer-6bd59c9f76-lqczw           1/1     Running   0          2m41s
 longhorn-csi-plugin-mbwqz                           2/2     Running   0          100s
 csi-snapshotter-588457fcdf-22bqp                    1/1     Running   0          100s
 csi-snapshotter-588457fcdf-2wd6g                    1/1     Running   0          100s
 csi-provisioner-869bdc4b79-mzrwf                    1/1     Running   0          101s
 csi-provisioner-869bdc4b79-klgfm                    1/1     Running   0          101s
 csi-resizer-6d8cf5f99f-fd2ck                        1/1     Running   0          101s
 csi-provisioner-869bdc4b79-j46rx                    1/1     Running   0          101s
 csi-snapshotter-588457fcdf-bvjdt                    1/1     Running   0          100s
 csi-resizer-6d8cf5f99f-68cw7                        1/1     Running   0          101s
 csi-attacher-7bf4b7f996-df8v6                       1/1     Running   0          101s
 csi-attacher-7bf4b7f996-g9cwc                       1/1     Running   0          101s
 csi-attacher-7bf4b7f996-8l9sw                       1/1     Running   0          101s
 csi-resizer-6d8cf5f99f-smdjw                        1/1     Running   0          101s
 instance-manager-b34d5db1fe1e2d52bcfb308be3166cfc   1/1     Running   0          114s
 engine-image-ei-df38d2e5-cv6nc                      1/1     Running   0          114s
----

. To enable access to the Longhorn UI, you will need to set up an Ingress controller. Authentication to the Longhorn UI is not enabled by default. For information on creating an NGINX Ingress controller with basic authentication, refer to xref:../../longhorn-system/system-access/create-ingress.adoc[this section.]
. Access the Longhorn UI using xref:../../longhorn-system/system-access/system-access.adoc[these steps.]
