= Installation
:description: Install SUSE® Storage on Kubernetes
:doctype: book
:current-version: {page-component-version}

NOTE: This quick installation guide uses some configurations which are not for production usage.
Please see xref:installation-setup/best-practices.adoc[] for how to configure SUSE® Storage for production usage.

SUSE® Storage can be installed on a Kubernetes cluster in several ways:

* xref:installation-setup/installation/install-using-rancher.adoc[]
* xref:installation-setup/installation/install-using-kubectl.adoc[]
* xref:installation-setup/installation/install-using-helm.adoc[]
* xref:installation-setup/installation/install-using-fleet.adoc[]
* xref:installation-setup/installation/install-using-flux.adoc[]
* xref:installation-setup/installation/install-using-argocd.adoc[]

To install SUSE® Storage in an air gapped environment, refer to xref:installation-setup/installation/airgapped-environment.adoc[this section].

For information on customizing the default settings, refer to xref:longhorn-system/customize-default-settings.adoc[this section].

For information on deploying SUSE® Storage on specific nodes and rejecting general workloads for those nodes, refer to the section on xref:nodes/taints-tolerations.adoc[].