= Installation
:description: Install Longhorn on Kubernetes
:doctype: book
:current-version: {page-component-version}

NOTE: This quick installation guide uses some configurations which are not for production usage.
Please see xref:introduction/best-practices.adoc[] for how to configure Longhorn for production usage.

Longhorn can be installed on a Kubernetes cluster in several ways:

* xref:installation-setup/installation/install-using-rancher.adoc[]
* xref:installation-setup/installation/install-using-kubectl.adoc[]
* xref:installation-setup/installation/install-using-helm.adoc[]
* xref:installation-setup/installation/install-using-fleet.adoc[]
* xref:installation-setup/installation/install-using-flux.adoc[]
* xref:installation-setup/installation/install-using-argocd.adoc[]

To install Longhorn in an air gapped environment, refer to xref:installation-setup/installation/airgapped-environment.adoc[this section].

For information on customizing Longhorn's default settings, refer to xref:longhorn-system/customize-default-settings.adoc[this section].

For information on deploying Longhorn on specific nodes and rejecting general workloads for those nodes, refer to the section on xref:nodes/taints-tolerations.adoc[].