= Convenciones de documentos
:revdate: 2025-06-27
:page-revdate: {revdate}

== Etiquetas de Lanzamiento

Cada lanzamiento menor es compatible hasta que el siguiente lanzamiento menor se vuelva estable.

* *Dev*: El software está en desarrollo activo y no ha sido probado exhaustivamente. No se admite la actualización desde lanzamientos anteriores o a lanzamientos posteriores. Los lanzamientos "Dev" suelen ocurrir al final de un sprint y pueden ocurrir cuando se cumplen otras definiciones de finalización. Dada la naturaleza no oficial del lanzamiento, utilice el software solo con fines de prueba.

* *Último*: El software ha pasado todas las etapas de verificación y prueba. Todos los problemas conocidos restantes se consideran aceptables. Utilice el software solo con fines de prueba.

* *Estable*: El software se considera fiable y libre de problemas críticos. Este lanzamiento se recomienda para uso general.

* *FIN DE VIDA ÚTIL*: El software ha alcanzado el final de su vida útil y no se proporciona más mantenimiento a nivel de código. Puede continuar utilizando el software dentro de los términos del acuerdo de licencia. Se recomienda actualizar a un lanzamiento estable.

[NOTE]
====
{longhorn-product-name} proporciona documentación sobre nuevas características, mejoras y correcciones de fallos implementadas en lanzamientos principales, menores y de parches.
====

== Etiquetas de características

Las características etiquetadas como **Experimental** y **Technical Preview** ofrecen un vistazo a las innovaciones futuras y brindan oportunidades para probar nuevas tecnologías en su entorno.

* *Experimental*: La característica está incompleta, pero su funcionalidad esencial está operativa. Las pruebas en un entorno controlado han demostrado que puede coexistir con características estables existentes. Debido a los componentes faltantes y/o la funcionalidad en evolución, no se recomienda el uso de la característica en entornos de producción.

* *Technical Preview*: La característica está casi completa y no se espera que su funcionalidad cambie significativamente. Las pruebas en un entorno controlado han demostrado que puede coexistir con características estables existentes. Explore la característica a fondo antes de usarla en entornos de producción.

Estas características tienen las siguientes limitaciones:

* Aún en desarrollo y pueden estar funcionalmente incompletas, inestables o de alguna otra manera inadecuadas para su uso en producción.
* No es compatible.
* Puede estar disponible solo para arquitecturas de hardware específicas. Los detalles y la funcionalidad están sujetos a cambios. Como resultado, actualizar a versiones posteriores puede ser imposible y puede requerir una instalación nueva.
* Puede ser eliminada del producto en cualquier momento. Esto puede ocurrir, por ejemplo, si descubrimos que la característica no satisface las necesidades del cliente o del mercado, o no cumple con los estándares empresariales.

[NOTE]
====
Las características *Experimental* y *Technical Preview* suelen estar desactivadas por defecto. La documentación proporciona información sobre cómo puede habilitar y configurar tales características.
====

== Advertencias

Las advertencias son bloques de texto que proporcionan información adicional o importante. Cada bloque de texto está marcado con una etiqueta y un icono especiales.

* *Nota*: Información adicional que es útil pero no crítica.

* *Importante*: Información que requiere atención especial, como cambios en el comportamiento del producto.

* *Sugerencia*: Consejos y sugerencias útiles, como los métodos alternativos para completar una tarea.

* *Precaución*: Información que debe considerarse antes de proceder con acciones específicas, como errores que pueden ocurrir.

* *Advertencia*: Información crítica sobre consecuencias perjudiciales, como daños irreversibles y pérdida de datos.