= Important Notes
:revdate: 2025-08-28
:page-revdate: {revdate}
:current-version: {page-component-version}

Please see https://github.com/longhorn/longhorn/releases/tag/v{patch-version}[here] for the full release notes.

== Removal

=== `longhorn.io/v1beta1` API

The `v1beta1` version of the Longhorn API is removed since Longhorn v1.10.0.

For more details, see link:https://github.com/longhorn/longhorn/issues/10249[Issue #10249].

== General

=== Kubernetes Version Requirement

The upgrade of the CSI external snapshotter to version v8.2.0 requires that all clusters run Kubernetes v1.25 or later. Ensure your Kubernetes version meets this requirement before you upgrade to {longhorn-product-name} v1.8.0 or a newer version.

=== CRD Upgrade Validation

During an upgrade, the Custom Resource Definition (CRD) might be applied after the new Longhorn Manager starts. This order helps prevent the controller from processing objects that contain deprecated data or fields. However, this sequencing can cause the Longhorn Manager to fail during the initial upgrade phase if the CRD is not yet applied.

If the Longhorn Manager crashes during the upgrade, check the logs to determine if the CRD not being applied is the cause of the failure. In such cases, the logs might contain error messages similar to the following:

[,log]
----
time="2025-03-27T06:59:55Z" level=fatal msg="Error starting manager: upgrade resources failed: BackingImage in version \"v1beta2\" cannot be handled as a BackingImage: strict decoding error: unknown field \"spec.diskFileSpecMap\", unknown field \"spec.diskSelector\", unknown field \"spec.minNumberOfCopies\", unknown field \"spec.nodeSelector\", unknown field \"spec.secret\", unknown field \"spec.secretNamespace\"" func=main.main.DaemonCmd.func3 file="daemon.go:94"
----

=== Upgrade Check Events

{longhorn-product-name} performs a pre-upgrade check when upgrading with Helm or the Rancher App Marketplace. If a check fails, the upgrade process stops, and the reason for the failure is recorded in an event. For more details, see xref:upgrades/longhorn-components/upgrade-longhorn-manager.adoc[Upgrading Longhorn Manager].

=== Manual Checks Before Upgrade

Automated checks are performed only on some upgrade paths, and the pre-upgrade checker might not cover all scenarios. Manual checks, performed using either `kubectl` or the UI, are recommended for these scenarios. You can then take mitigating actions or defer the upgrade until any identified issues are addressed.

* Ensure that all V2 Data Engine volumes are detached and their replicas are stopped. The V2 Data Engine currently does not support live upgrades.
* Avoid upgrading when volumes are in the `"Faulted"` status. If all replicas are deemed unusable, they might be deleted, potentially leading to permanent data loss if no usable backups exist.
* Avoid upgrading if a failed `BackingImage` exists. For more information, see xref:volumes/backing-images/backing-images.adoc[Backing Image].
* Create a xref:snapshots-backups/system-backups/create-system-backup.adoc[Longhorn system backup] before performing the upgrade. This ensures that all critical resources, such as volumes and backing images, are backed up and can be restored if any issues arise during the upgrade.

== V1 Data Engine

=== IPv6 Support

Longhorn v1.10.0 and later versions support the usage of V1 volumes in single-stacked IPv6 Kubernetes clusters. For more information, see https://github.com/longhorn/longhorn/issues/2259[Issue #2259].

[IMPORTANT]
====
Dual-stack Kubernetes clusters and V2 volumes are not supported in this version.
====

== V2 Data Engine

=== {longhorn-product-name} System Upgrade

{longhorn-product-name} currently does not support live upgrading of V2 volumes. Ensure that all V2 volumes are detached before initiating the upgrade process.

=== Newly Introduced Functionalities since {longhorn-product-name} v1.10.0

== Backup And Restore

=== Configurable Backup Block Size

Starting in {longhorn-product-name} v1.10.0, users can configure the backup block size when creating a volume. This feature provides greater flexibility, allowing the block size to be adjusted based on different needs and cost considerations to balance performance, efficiency, and transmission cost.

For more information, see xref:volumes/create-volumes.adoc[Create Longhorn Volumes].
