= Instalação
:revdate: 2026-01-12
:page-revdate: {revdate}
:description: Instale o SUSE® Storage no Kubernetes
:doctype: book
:current-version: {page-component-version}

NOTE: Este guia de instalação rápida utiliza algumas configurações que não são para uso em produção.
Por favor, veja xref:installation-setup/best-practices.adoc[Melhores Práticas] para saber como configurar {longhorn-product-name} para uso em produção.

{longhorn-product-name} pode ser instalado em um cluster Kubernetes de várias maneiras:

* xref:installation-setup/installation/install-using-rancher.adoc[]
* xref:installation-setup/installation/install-using-helm.adoc[]
* xref:installation-setup/installation/install-using-fleet.adoc[]
* xref:installation-setup/installation/install-using-flux.adoc[]
* xref:installation-setup/installation/install-using-argocd.adoc[]

Para instalar {longhorn-product-name} em um ambiente air-gapped, consulte xref:installation-setup/installation/airgapped-environment.adoc[Instalação Air-Gapped].

Para informações sobre como personalizar as configurações padrão, consulte xref:longhorn-system/customize-default-settings.adoc[Personalizando Configurações Padrão].

Para informações sobre como implantar {longhorn-product-name} em nós específicos e rejeitar cargas de trabalho gerais para esses nós, consulte a seção sobre xref:nodes/taints-tolerations.adoc[Taints e Tolerations].
