= 前提条件
:revdate: 2025-06-27
:page-revdate: {revdate}
:aliases: ["/spdk/prerequisites.md"]
:current-version: {page-component-version}

== 前提条件

Longhornノードは次の要件を満たしている必要があります:

* AMD64またはARM64 CPU
+
____
*通知*

AMD64 CPUはSSE4.2命令のサポートが必要です。
____

* Linuxカーネル
+
NVMe over TCPサポートには5.19以降が必要です。
+
____
*通知*

Linuxカーネル5.15を使用しているホストマシンは、ボリューム関連の入出力エラーが発生すると予期せず再起動する可能性があります。そのような問題を防ぐために、LonghornノードのLinuxカーネルをバージョン5.19以降に更新してください。
____
+
システムの安定性を向上させるために、v6.7以降を推奨します。
+
____
*通知*

Linuxカーネルのバージョンが6.7よりも古いホストではメモリ破損が発生する可能性があり、これはこのSPDKアップストリームの問題で強調されています:https://github.com/spdk/spdk/issues/3116#issuecomment-1890984674. Longhorn環境では、カーネルパニックは`nvme-tcp`ドライバとSPDK間の通信における一般的な入出力タイムアウトによって引き起こされる可能性があります。その問題が発生しないように、LonghornノードのLinuxカーネルをバージョン6.7以降に更新してください。
____

* Linuxカーネルモジュール
 ** `vfio_pci`
 ** `uio_pci_generic`
 ** `nvme-tcp`
* 巨大ページのサポート
 ** 2 MiBサイズのページで構成された合計2 GiB

== 注意

=== CPU

V2データエンジンが有効な場合、各インスタンスマネージャーポッドは*1 CPUコア*を利用します。この高いCPU使用率は、各インスタンスマネージャーポッド内で実行されている`spdk_tgt`プロセスに起因しています。spdk_tgtプロセスは、入出力（IO）操作を処理する責任があり、集中的なポーリングを必要とします。その結果、入出力リクエストを効率的に管理および処理するために、専用のCPUコアの100%を消費し、ストレージ操作の最適なパフォーマンスと応答性を確保します。

=== メモリ

SPDKは、パフォーマンスを向上させ、メモリオーバーヘッドを最小限に抑えるために巨大ページを活用します。巨大ページを使用するために、各Longhornノードで2 MiBサイズの巨大ページを構成する必要があります。具体的には、各Longhornノードに1024ページ（合計2 GiBに相当）が利用可能でなければなりません。

=== ディスク

SPDKは、Linuxがサポートするすべての種類のディスクをサポートするためにカーネルドライバーを活用しています。しかし、SPDKはユーザースペースのNVMeドライバーを備えており、ユーザースペースアプリケーションからSSDへのゼロコピーで高並列の直接アクセスを提供します。このため、*ローカルNVMeディスク*を使用することが、V2ボリュームが最適なストレージパフォーマンスを達成するために強く推奨されます。
