= Backups do Sistema SUSE® Storage
:revdate: 2025-06-27
:page-revdate: {revdate}
:current-version: {page-component-version}

____
Versões anteriores permitiam que você restaurasse o sistema SUSE® Storage usando ferramentas de terceiros.
____

* xref:snapshots-backups/system-backups/restore-to-cluster-using-rancher-snapshot.adoc[Restaurar para um cluster que contém dados usando o instantâneo do Rancher]
* xref:snapshots-backups/system-backups/restore-to-new-cluster-using-velero.adoc[Restaurar para um novo cluster usando o Velero]

____
As versões atuais do SUSE® Storage incluem backup e restauração do sistema prontos para uso.

* Os recursos personalizados do SUSE® Storage serão submetidos a backup e agrupados em um único arquivo de backup do sistema, que será salvo no destino de backup remoto.
* Mais tarde, você pode escolher um backup do sistema para restaurar em um novo cluster ou restaurar em um cluster existente.
____

* xref:snapshots-backups/system-backups/create-system-backup.adoc[Backup do sistema Longhorn]
* xref:snapshots-backups/system-backups/restore-system.adoc[Restaurar o sistema Longhorn]
