= インストール
:revdate: 2026-01-12
:page-revdate: {revdate}
:description: KubernetesにSUSE® Storageをインストールする
:doctype: book
:current-version: {page-component-version}

NOTE: このクイックインストールガイドでは、プロダクション使用には適さないいくつかの設定を使用しています。
プロダクション使用のために{longhorn-product-name}を設定する方法については、xref:installation-setup/best-practices.adoc[ベストプラクティス]をご覧ください。

{longhorn-product-name}は、Kubernetesクラスターにいくつかの方法でインストールできます：

* xref:installation-setup/installation/install-using-rancher.adoc[]
* xref:installation-setup/installation/install-using-helm.adoc[]
* xref:installation-setup/installation/install-using-fleet.adoc[]
* xref:installation-setup/installation/install-using-flux.adoc[]
* xref:installation-setup/installation/install-using-argocd.adoc[]

エアギャップ(された)環境に{longhorn-product-name}をインストールするには、xref:installation-setup/installation/airgapped-environment.adoc[エアギャップ(された)インストール]を参照してください。

デフォルト設定のカスタマイズに関する情報は、xref:longhorn-system/customize-default-settings.adoc[デフォルト設定のカスタマイズ]を参照してください。

特定のノードに{longhorn-product-name}をデプロイする方法およびこれらのノードに対して一般的なワークロードを拒否する方法については、xref:nodes/taints-tolerations.adoc[テイントとトレランス]のセクションを参照してください。
