= 概要
:revdate: 2025-06-27
:page-revdate: {revdate}

{longhorn-product-name-tm}は、Kubernetes向けの軽量で信頼性が高く、使いやすい分散ブロックストレージシステムです。

{longhorn-product-name}を使用して、以下のことができます。

* {longhorn-product-name}ボリュームを、Kubernetesクラスター内の分散ステートフルアプリケーションの永続ストレージとして使用します。
* ブロックストレージを{longhorn-product-name}ボリュームに分割し、クラウドプロバイダーの有無にかかわらずKubernetesボリュームを使用できるようにします。
* 可用性を高めるために、複数のノードやデータセンターにわたってブロックストレージを複製します。
* バックアップデータをNFSやAWS S3などの外部ストレージに保存します。
* クロスクラスターのディザスタリカバリボリュームを作成し、プライマリKubernetesクラスターのデータを、セカンダリKubernetesクラスターのバックアップから迅速に復元できるようにします。
* ボリュームの定期的なスナップショットをスケジュールし、NFSまたはS3互換のセカンダリストレージへの定期的なバックアップをスケジュールします。
* バックアップからボリュームを復元します。
* 永続ボリュームを中断することなく{longhorn-product-name}をアップグレードします。

{longhorn-product-name}はスタンドアロンのUIを備えており、Helm、kubectl、またはRancherアプリカタログを使用してインストールできます。

== マイクロサービスによる分散ブロックストレージの簡素化

現代のクラウド環境では、数万から数百万の分散ブロックストレージボリュームが必要なため、一部のストレージコントローラーは非常に複雑な分散システムになっています。対照的に、{longhorn-product-name}は、大きなブロックストレージコントローラーを、共通のディスクプールから構築できる限り、いくつかの小さなストレージコントローラーに分割することで、ストレージシステムを簡素化できます。ボリュームごとに1つのストレージコントローラーを使用することで、{longhorn-product-name}は各ボリュームをマイクロサービスに変えます。コントローラーはLonghorn Engineと呼ばれます。

Longhorn ManagerコンポーネントはLonghorn Enginesを調整し、協調して動作するようにします。

== クラウドプロバイダーに依存せずにKubernetesで永続ストレージを使用します。

Podはストレージを直接参照できますが、Podやコンテナのポータビリティを許可しないため、推奨されません。代わりに、ワークロードのストレージ要件は、Kubernetesの永続ボリューム（PVs）および永続ボリュームクレーム（PVCs）で定義する必要があります。{longhorn-product-name}を使用すると、ボリュームのサイズ、同期レプリカの数、およびボリュームのストレージリソースを提供するホスト全体で必要なその他のボリューム特有の設定を指定できます。そのため、Kubernetesリソースは各{longhorn-product-name}ボリュームに対してPVCおよび対応するPVを使用するか、ワークロードのためにPVを自動的に作成する{longhorn-product-name}ストレージクラスを使用できます。

レプリカは、基盤となるディスクまたはネットワークストレージ上でシンプロビジョニングされています。

== 複数のコンピュートまたはストレージホストにわたって複数のレプリカをスケジュールします。

可用性を高めるために、{longhorn-product-name}は各ボリュームのレプリカを作成します。レプリカには、ボリュームのスナップショットのチェーンが含まれており、各スナップショットは前のスナップショットからの変更を保存します。各ボリュームのレプリカはコンテナ内で実行されるため、3つのレプリカを持つボリュームは4つのコンテナを生成します。

各ボリュームのレプリカの数は{longhorn-product-name}で設定可能であり、レプリカがスケジュールされるノードも設定できます。{longhorn-product-name}は各レプリカの健康状態を監視し、必要に応じて修復し、レプリカを再構築します。

== 各ボリュームに対して複数のストレージフロントエンドを割り当てます。

一般的なフロントエンドには、Linuxカーネルデバイス（/dev/longhornの下にマッピングされている）およびiSCSIターゲットが含まれます。

== 定期的なスナップショットおよびバックアップ操作のスケジュールを指定します。

これらの操作の頻度（毎時、毎日、毎週、毎月、毎年）、これらの操作が実行される正確な時間（例：毎週日曜日の午前3時）、および保持される定期的なスナップショットとバックアップセットの数を指定します。
