= スナップショットスペース管理
:revdate: 2025-06-27
:page-revdate: {revdate}
:current-version: {page-component-version}

Longhornでは、各ボリュームの最大スナップショット数と最大合計スナップショットサイズを設定できます。これらの設定は、削除されたスナップショット、バックイメージ、およびボリュームヘッドスナップショットを考慮しません。これらの制限のいずれかに達した場合、新しいスナップショットを作成する前にスナップショットを削除する必要があります。

以前のバージョンでは、最大スナップショット数は設定できず（値は250）、スナップショットスペースの使用を制限する方法はありません。

== 設定

=== グローバル設定

*スナップショット最大数*:各ボリュームに対して作成できるスナップショットの最大数。

"2"から"250"の間の値を指定する必要があります。Longhornは、特にボリュームの再構築中に、正常に機能するために少なくとも2つのスナップショットを必要とします。既存のスナップショットがマージされると1つのスナップショットが作成され、再構築プロセス中にもう1つのスナップショットが作成されます。
デフォルト値は"250"です。

`.Spec.SnapshotMaxCount`のデフォルト値を変更せずにボリュームを作成すると、Longhornは`snapshot-max-count`設定の値を適用します。`snapshot-max-count`の値を変更しても、既存のボリュームには影響しません。

=== ボリューム固有の設定

*スナップショット最大数*:特定のボリュームに対して作成できるスナップショットの最大数。

"0"または"2"から"250"の間の任意の値を指定できます。デフォルト値は"0"です。

この設定のデフォルト値を変更せずにボリュームを作成すると、Longhornは`snapshot-max-count`設定の値を適用します。

*スナップショット最大サイズ*:特定のボリュームに対するスナップショットの最大合計サイズ。

"0"または`Volume.Spec.Size`に2を掛けた値より大きい任意の値を指定できます。Longhornが正常に機能するためには、`Volume.Spec.Size`の値を2倍にする必要があります。スナップショットは少なくとも2つ必要です。

デフォルト値は"0"であり、これにより設定が実質的に無効になります。

ボリュームサイズを拡張すると、Longhornはこの設定の値を`Volume.Spec.Size`に2を掛けた値に自動的に増加させます（現在の値が小さい場合）。
