= Instale {longhorn-product-name} usando o Helm Controller
:revdate: 2026-02-02
:page-revdate: {revdate}
:current-version: {page-component-version}

Você pode instalar {longhorn-product-name} usando o Helm Controller integrado ao RKE2 e K3s.

== Pré-requisitos

[NOTE]
====
A instalação do {longhorn-product-name} requer acesso autenticado ao SUSE Application Collection. Para mais detalhes, consulte https://docs.apps.rancher.io/get-started/authentication[guia de autenticação].
====

* Kubernetes cluster: Certifique-se de que cada nó atenda aos xref:installation-setup/requirements.adoc[requisitos de instalação]. O cluster deve estar executando RKE2 ou K3s.

____
A xref:longhorn-system/system-access/longhorn-cli.adoc[Ferramenta de Linha de Comando Longhorn] pode ser usada para verificar o ambiente {longhorn-product-name} em busca de problemas potenciais.
____

== Instalação

[NOTE]
====
* As configurações iniciais podem ser xref:longhorn-system/customize-default-settings.adoc#_using_helm[personalizadas usando opções do Helm ou editando o arquivo de configuração da implantação].
* Para Kubernetes v1.25 ou anterior, se seu cluster ainda habilitar o controlador de admissão de Política de Segurança de Pod, defina o valor do helm `enablePSP` como `true` para instalar o recurso PodSecurityPolicy `longhorn-psp` que permite que pods Longhorn privilegiados sejam iniciados.
====

. Crie um arquivo YAML HelmChart semelhante ao seguinte:
+
[subs="+attributes",yaml]
----
apiVersion: helm.cattle.io/v1
  kind: HelmChart
  metadata:
    annotations:
      helmcharts.cattle.io/managed-by: helm-controller
    finalizers:
    - wrangler.cattle.io/on-helm-chart-remove
    generation: 1
    name: longhorn-install
    namespace: default
  spec:
    version: v{patch-version}
    chart: longhorn
    repo: https://charts.longhorn.io
    failurePolicy: abort
    targetNamespace: longhorn-system
    createNamespace: true
----
+
[IMPORTANT]
====
* Certifique-se de que `spec.failurePolicy` esteja definido como "abort".  O único outro valor é o padrão: "reinstall", que desinstala {longhorn-product-name}.  Com "abort", ele tenta novamente periodicamente, dando ao usuário a chance de corrigir o problema.
+
* Em vez de especificar o repositório, versão e nome do gráfico, o YAML também pode usar uma imagem dos próprios gráficos:
+
[,yaml]
----
spec:
  chartContent:  <tarball of chart directory | base64 -w 0>
----
+
Para detalhes completos, consulte a documentação do controlador HelmChart: https://documentation.suse.com/cloudnative/rke2/latest/en/add-ons/helm.html[{rke2-product-name} - Helm] ou https://documentation.suse.com/cloudnative/k3s/latest/en/helm.html[{k3s-product-name} - Helm].
====
+
. Aplique o YAML para criar o CR HelmChart e um trabalho de instalação.
+
[,shell]
----
$ kubectl apply -f helmchart_repo_install.yaml
helmchart.helm.cattle.io/longhorn-install created
----
+
[NOTE]
====
Excluir o CR HelmChart inicia a desinstalação do {longhorn-product-name}.
====
. Verifique os recursos criados.
+
[subs="+attributes",shell]
----
$ kubectl get jobs
NAME                            COMPLETIONS   DURATION   AGE
helm-install-longhorn-install   0/1           8s         8s
$ kubectl get pods
NAME                                  READY   STATUS      RESTARTS   AGE
helm-install-longhorn-install-lngm8   0/1     Completed   0          25s
$ kubectl get helmcharts
NAME               JOB                     CHART      TARGETNAMESPACE   VERSION   REPO                         HELMVERSION   BOOTSTRAP
longhorn-install   helm-install-longhorn   longhorn   longhorn-system   v{patch-version}    https://charts.longhorn.io
----
+
. Verifique se a implantação foi bem-sucedida.
+
[,bash]
----
kubectl -n longhorn-system get pod
----
+
Exemplo de resultado:
+
[,bash]
----
NAME                                                READY   STATUS    RESTARTS      AGE
csi-attacher-85c7684cfd-67kqc                       1/1     Running   0             29m
csi-attacher-85c7684cfd-jbddj                       1/1     Running   0             29m
csi-attacher-85c7684cfd-t85bw                       1/1     Running   0             29m
csi-provisioner-68cdb8b96-46d9q                     1/1     Running   0             29m
csi-provisioner-68cdb8b96-dgf5f                     1/1     Running   0             29m
csi-provisioner-68cdb8b96-mh8q7                     1/1     Running   0             29m
csi-resizer-86dd765b9-d27cs                         1/1     Running   0             29m
csi-resizer-86dd765b9-scqxm                         1/1     Running   0             29m
csi-resizer-86dd765b9-zpcv7                         1/1     Running   0             29m
csi-snapshotter-65b46b8749-dtvh2                    1/1     Running   0             29m
csi-snapshotter-65b46b8749-g67fn                    1/1     Running   0             29m
csi-snapshotter-65b46b8749-nfgzm                    1/1     Running   0             29m
engine-image-ei-221c9c21-gd5d6                      1/1     Running   0             29m
engine-image-ei-221c9c21-v6clp                      1/1     Running   0             29m
engine-image-ei-221c9c21-zzdrt                      1/1     Running   0             29m
instance-manager-77d11dda6091967f9b30011c9876341b   1/1     Running   0             29m
instance-manager-870c250b69a4fe01382ed46156d33f47   1/1     Running   0             29m
instance-manager-a4099c5ce28b423c3cc2667906f4b0b4   1/1     Running   0             29m
longhorn-csi-plugin-jfbh5                           3/3     Running   0             29m
longhorn-csi-plugin-w768w                           3/3     Running   0             29m
longhorn-csi-plugin-xcghm                           3/3     Running   0             29m
longhorn-driver-deployer-586bc86bf9-bkwk6           1/1     Running   0             30m
longhorn-manager-c4xtv                              1/1     Running   1 (30m ago)   30m
longhorn-manager-kgqts                              1/1     Running   0             30m
longhorn-manager-n8xdr                              1/1     Running   0             30m
longhorn-ui-69667f9678-2lvxn                        1/1     Running   0             30m
longhorn-ui-69667f9678-2xmc9                        1/1     Running   0             30m
----
+
. xref:longhorn-system/system-access/create-ingress.adoc[Crie um controlador de Ingress NGINX com autenticação básica] para acessar a interface do usuário. A autenticação na interface do usuário não está habilitada por padrão.
+
. xref:longhorn-system/system-access/system-access.adoc[Acesse a interface do usuário].
