= 在禁用的磁盘或节点上驱逐副本
:revdate: 2025-06-27
:page-revdate: {revdate}
:current-version: {page-component-version}

Longhorn支持自动驱逐功能，将选定的禁用磁盘或节点上的副本驱逐到其他合适的磁盘和节点上。同时，在驱逐过程中保持相同级别的高可用性。

NOTE: 此驱逐功能仅在选定的磁盘或节点禁用调度时才能启用。在驱逐期间，选定的磁盘或节点不能重新启用调度。

NOTE: 此驱逐功能适用于`Attached`和`Detached`的卷。如果卷为'已分离'，Longhorn将在驱逐之前自动附加它，并在驱逐完成后自动分离。

默认情况下，磁盘或节点的`Eviction Requested`为`false`。为了在驱逐过程中保持同样级别的高可用性，Longhorn只有在该卷的副本重建成功后，才驱逐每个卷中的一个副本。

== 选择要驱逐的磁盘或节点

要驱逐节点的磁盘，

. 前往`Node`选项卡，选择一个节点，并在下拉菜单中选择`Edit Node and Disks`。
. 确保磁盘已禁用调度，并将`Scheduling`设置为`Disable`。
. 将`Eviction Requested`设置为`true`并保存。

要驱逐一个节点，

. 前往`Node`选项卡，选择一个或多个节点，然后点击`Edit Node`。
. 确保节点已禁用调度，并将`Scheduling`设置为`Disable`。
. 将`Eviction Requested`设置为`true`，并保存。

== 取消磁盘或节点的驱逐

要取消磁盘或节点的驱逐，将相应的`Eviction Requested`设置为`false`。

== 检查驱逐状态

一旦驱逐成功，所选磁盘或节点上的`Replicas`数量应减少到0。

如果您点击`Replicas`数量，它将显示该磁盘上的副本名称。当您点击副本名称时，Longhorn UI将重定向网页到相应的卷页面，并显示卷状态。如果出现任何错误，例如没有空间，或找不到其他可调度的磁盘（调度故障），将显示错误。所有错误将记录在事件日志中。

如果在驱逐过程中发生任何错误，驱逐将被暂停，直到清理出新空间，或者将被取消。如果驱逐被取消，所选磁盘或节点上的剩余副本将保留在磁盘或节点上。
