= Managed Node Pools on Amazon Elastic Kubernetes Service (Amazon EKS)
:revdate: 2025-06-27
:page-revdate: {revdate}
:current-version: {page-component-version}

EKS supports configuring the same launch template. The nodes in the node-group will be recycled by new nodes with new configurations when updating the launch template version.

See https://docs.aws.amazon.com/eks/latest/userguide/launch-templates.html[Launch template support] for more information.

The following is an example to replace cluster nodes with new storage size.

== Storage Expansion

. In Longhorn, set `replica-replenishment-wait-interval` to `0`.
. Go to the launch template of the EKS cluster node-group. You can find in the EKS cluster tab `Configuration/Compute/<node-group-name>` and click the launch template.
. Click `Modify template (Create new version)` in the `Actions` drop-down menu.
. Choose the `Source template version` in the `Launch template name and version description`.
. Follow steps to <<_expand_volume,Expand volume>>, or <<_create_additional_volume,Create additional volume>>.
+
NOTE: If you choose to expand by <<_create_additional_volume,create additional volume>>, the disks need to be manually added to the disk list of the nodes after the EKS cluster upgrade.

=== Expand volume

. Update the volume size in `Configure storage`.
. Click `Create template version` to save changes.
. Go to the EKS cluster node-group and change `Launch template version` in `Node Group configuration`. Track the status in the `Update history` tab.

=== Create additional volume

. Click `Advanced` then `Add new volume` in `Configure storage` and fill in the fields.
. Adjust the auto-mount script and add to `User data` in `Advanced details`. Make sure the `DEV_PATH` matches the `Device name` of the additional volume.
+
----
 MIME-Version: 1.0
 Content-Type: multipart/mixed; boundary="==MYBOUNDARY=="

 --==MYBOUNDARY==
 Content-Type: text/x-shellscript; charset="us-ascii"

 #!/bin/bash

 # https://docs.aws.amazon.com/eks/latest/userguide/launch-templates.html#launch-template-user-data
 echo "Running custom user data script"

 DEV_PATH="/dev/sdb"
 mkfs -t ext4 ${DEV_PATH}

 MOUNT_PATH="/mnt/longhorn"
 mkdir ${MOUNT_PATH}
 mount ${DEV_PATH} ${MOUNT_PATH}
----

. Click `Create template version` to save changes.
. Go to the EKS cluster node-group and change `Launch template version` in `Node Group configuration`. Track the status in the `Update history` tab.
. In Longhorn, add the path of the mounted disk into the disk list of the nodes.
