= リビジョンカウンター
:revdate: 2025-06-27
:page-revdate: {revdate}
:doctype: book
:experimental:
:current-version: {page-component-version}

リビジョンカウンターは、{longhorn-product-name}が各レプリカの更新を追跡するために使用するメカニズムです。

レプリカの作成中に、{longhorn-product-name}は初期カウンターが0に設定された`revision.counter`ファイルを作成します。レプリカへの書き込みごとに、`revision.counter`ファイルのカウンターは1増加します。

{longhorn-product-name}エンジンは、起動時にレプリカ間で最善の整合性を達成するためのヒューリスティックとしてこれらのカウンターを使用します。{longhorn-product-name}の書き込みIOが並行しているため、リビジョンカウンターを有効にしてもデータの整合性は保証されません。{longhorn-product-name}は、自動回復中に最新の更新を持つレプリカを特定するためにこれらのカウンターも使用します。

リビジョンカウンターを無効にすることは、レプリカ上のすべての書き込みが追跡されないオプションです。この設定を使用すると、パフォーマンスが向上します。このオプションは、より高いパフォーマンスを好み、十分なCPUリソースを持つ安定したネットワークインフラストラクチャ（例：内部ネットワーク）がある場合に役立ちます。リビジョンカウンターが無効になっている場合、Longhorn Engineは起動時にすべてのレプリカのリビジョンカウンターのチェックをスキップします。ただし、自動回復は機能し続けます。なぜなら、{longhorn-product-name}はレプリカのヘッダーファイルの状態を使用して回復に使用するレプリカを特定できるからです。リビジョンカウンターなしで自動回復がどのように機能するかについての詳細は、<<_auto_salvage_support_with_revision_counter_disabled,リビジョンカウンター無効時の自動回復サポート>>を参照してください。

デフォルトでは、リビジョンカウンターは無効になっています。

[NOTE]
====
「サルベージ」とは、{longhorn-product-name}が故障状態のボリュームを回復しようとすることです。Longhorn Engineがすべてのレプリカとの接続を失い、すべてのレプリカがエラー状態としてマークされているとき、ボリュームは故障状態にあります。
====

= リビジョンカウンターを無効にする

== {longhorn-product-name} UIを使用する

{longhorn-product-name} UIからリビジョンカウンターを無効または有効にするには、menu:設定[リビジョンカウンターを無効にする]をクリックします。

一般設定に対してカスタマイズされた設定を持つ個別のボリュームを作成するには、*ボリューム*ページに移動し、*ボリュームを作成*をクリックします。

== マニフェストファイルを使用する

`StorageClass`は`disableRevisionCounter`パラメータを追加するようにカスタマイズできます。

デフォルトでは、`disableRevisionCounter`はfalseであり、リビジョンカウンターが有効になっています。

リビジョンカウンターを無効にするには、`disableRevisionCounter`をtrueに設定します：

[subs="+attributes",yaml]
----
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: best-effort-longhorn
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "1"
  disableRevisionCounter: "true"
  staleReplicaTimeout: "2880" # 48 hours in minutes
  fromBackup: ""
----

== リビジョンカウンターが無効な場合の自動サルベージサポート

リビジョンカウンターが無効な場合、自動回復のロジックは異なります。

リビジョンカウンターが有効で、ボリューム内のすべてのレプリカが'ERR'状態にある場合、エンジンコントローラーは故障状態になり、ボリュームを回復するために、最も大きなリビジョンカウンターを持つレプリカを'真実のソース'として取得し、他のレプリカを再構築します。

この場合、リビジョンカウンターが無効になっていると、エンジンコントローラーはすべてのレプリカの`volume-head-xxx.img`最終更新時刻とヘッドファイルサイズを取得します。次のステップも実行します：

. `volume-head-xxx.img`が最終更新された時点に基づいて、最も最近の最終更新タイムスタンプを持つレプリカを特定します。
. 上記のレプリカの最終更新タイムスタンプから5秒以内に最終更新タイムスタンプを持つすべてのレプリカを選択します。
. 上記のステップからのレプリカ候補の中で、候補のヘッドファイルサイズを比較し、最も大きなファイルサイズを持つものを選びます。
. 上記のステップからのレプリカ候補の中で、最も最近の更新タイムスタンプを持つ最良のレプリカを選びます。
. 最良のレプリカを'RW'モードに変更し、他のレプリカは'ERR'モードとしてマークされます。エラーのあるレプリカは、最良のレプリカに基づいて再構築されます。
