= Identifizieren Sie beschädigte Replikate
:revdate: 2025-06-27
:page-revdate: {revdate}
:current-version: {page-component-version}

Falls einer der von Longhorn verwendeten Festplatten defekt ist, können Sie intermittierende Ein-/Ausgabefehler beim Verwenden eines Longhorn-Volumes erleben.

Zum Beispiel kann eine Datei manchmal nicht gelesen werden, später jedoch schon. In diesem Szenario ist es wahrscheinlich, dass eine der Festplatten defekt ist, was dazu führt, dass eines der Replikate falsche Daten an den Benutzer zurückgibt.

Um das Volume wiederherzustellen, können wir das beschädigte Replikat identifizieren und es vom Volume entfernen:

. Reduzieren Sie die Arbeitslast, um das Volume zu trennen.
. Finden Sie alle Standorte der Replikate, indem Sie die Longhorn-Benutzeroberfläche überprüfen. Die Verzeichnisse, die von den Replikaten verwendet werden, werden als Tooltip für jedes Replikat in der Benutzeroberfläche angezeigt.
. Melden Sie sich an jedem Knoten an, der ein Replikat des Volumes enthält, und navigieren Sie zu dem Verzeichnis, das die Replikatdaten enthält.
+
Zum Beispiel könnte das Replikat gespeichert sein unter:

  /var/lib/longhorn/replicas/pvc-06b4a8a8-b51d-42c6-a8cc-d8c8d6bc65bc-d890efb2

. Führen Sie eine Prüfsumme für jede Datei unter diesem Verzeichnis aus.
+
Beispiel:
+
----
 # sha512sum /var/lib/longhorn/replicas/pvc-06b4a8a8-b51d-42c6-a8cc-d8c8d6bc65bc-d890efb2/*
 fcd1b3bb677f63f58a61adcff8df82d0d69b669b36105fc4f39b0baf9aa46ba17bd47a7595336295ef807769a12583d06a8efb6562c093574be7d14ea4d6e5f4  /var/lib/longhorn/replicas/pvc-06b4a8a8-b51d-42c6-a8cc-d8c8d6bc65bc-d890efb2/revision.counter
 c53649bf4ad843dd339d9667b912f51e0a0bb14953ccdc9431f41d46c85301dff4a021a50a0bf431a931a43b16ede5b71057ccadad6cf37a54b2537e696f4780  /var/lib/longhorn/replicas/pvc-06b4a8a8-b51d-42c6-a8cc-d8c8d6bc65bc-d890efb2/volume-head-000.img
 f6cd5e486c88cb66c143913149d55f23e6179701f1b896a1526717402b976ed2ea68fc969caeb120845f016275e0a9a5b319950ae5449837e578665e2ffa82d0  /var/lib/longhorn/replicas/pvc-06b4a8a8-b51d-42c6-a8cc-d8c8d6bc65bc-d890efb2/volume-head-000.img.meta
 e6f6e97a14214aca809a842d42e4319f4623adb8f164f7836e07dc8a3f4816a0389b67c45f7b0d9f833d50a731ae6c4670ba1956833f1feb974d2d12421b03f7  /var/lib/longhorn/replicas/pvc-06b4a8a8-b51d-42c6-a8cc-d8c8d6bc65bc-d890efb2/volume.meta
----

. Vergleichen Sie die Ausgaben jedes Replikats. Eines von ihnen sollte fehlschlagen oder unterschiedliche Ergebnisse im Vergleich zu den anderen haben. Dies wird das eine Replikat sein, das wir vom Volume entfernen müssen.
. Verwenden Sie die Longhorn-Benutzeroberfläche, um das identifizierte Replikat vom Volume zu entfernen.
. Erhöhen Sie die Arbeitslast, um sicherzustellen, dass der Fehler behoben ist.
