= Identifier les répliques corrompues
:revdate: 2025-06-27
:page-revdate: {revdate}
:current-version: {page-component-version}

Dans le cas où l'un des disques utilisés par Longhorn serait défectueux, vous pourriez rencontrer des erreurs d'entrée/sortie intermittentes lors de l'utilisation d'un volume Longhorn.

Par exemple, un fichier ne peut parfois pas être lu, mais plus tard, il peut l'être. Dans ce scénario, il est probable qu'un des disques soit défectueux, ce qui entraîne qu'une des répliques renvoie des données incorrectes à l'utilisateur.

Pour récupérer le volume, nous pouvons identifier la réplique corrompue et la supprimer du volume{nbsp}:

. Réduisez la charge de travail pour détacher le volume.
. Trouvez tous les emplacements des répliques en vérifiant l'interface utilisateur de Longhorn. Les répertoires utilisés par les répliques seront affichés sous forme d'info-bulle pour chaque réplique dans l'interface utilisateur.
. Connectez-vous à chaque nœud contenant une réplique du volume et accédez au répertoire contenant les données de la réplique.
+
Par exemple, la réplique pourrait être stockée à{nbsp}:

  /var/lib/longhorn/replicas/pvc-06b4a8a8-b51d-42c6-a8cc-d8c8d6bc65bc-d890efb2

. Exécutez une somme de contrôle pour chaque fichier dans ce répertoire.
+
Par exemple :
+
----
 # sha512sum /var/lib/longhorn/replicas/pvc-06b4a8a8-b51d-42c6-a8cc-d8c8d6bc65bc-d890efb2/*
 fcd1b3bb677f63f58a61adcff8df82d0d69b669b36105fc4f39b0baf9aa46ba17bd47a7595336295ef807769a12583d06a8efb6562c093574be7d14ea4d6e5f4  /var/lib/longhorn/replicas/pvc-06b4a8a8-b51d-42c6-a8cc-d8c8d6bc65bc-d890efb2/revision.counter
 c53649bf4ad843dd339d9667b912f51e0a0bb14953ccdc9431f41d46c85301dff4a021a50a0bf431a931a43b16ede5b71057ccadad6cf37a54b2537e696f4780  /var/lib/longhorn/replicas/pvc-06b4a8a8-b51d-42c6-a8cc-d8c8d6bc65bc-d890efb2/volume-head-000.img
 f6cd5e486c88cb66c143913149d55f23e6179701f1b896a1526717402b976ed2ea68fc969caeb120845f016275e0a9a5b319950ae5449837e578665e2ffa82d0  /var/lib/longhorn/replicas/pvc-06b4a8a8-b51d-42c6-a8cc-d8c8d6bc65bc-d890efb2/volume-head-000.img.meta
 e6f6e97a14214aca809a842d42e4319f4623adb8f164f7836e07dc8a3f4816a0389b67c45f7b0d9f833d50a731ae6c4670ba1956833f1feb974d2d12421b03f7  /var/lib/longhorn/replicas/pvc-06b4a8a8-b51d-42c6-a8cc-d8c8d6bc65bc-d890efb2/volume.meta
----

. Comparez la sortie de chaque réplique. L'une d'elles devrait échouer ou avoir des résultats différents par rapport aux autres. Celle-ci sera la réplique que nous devons supprimer du volume.
. Utilisez l'interface utilisateur de Longhorn pour supprimer la réplique identifiée du volume.
. Augmentez la charge de travail pour vous assurer que l'erreur a disparu.
