= Identifier et récupérer des erreurs de données
:revdate: 2025-06-27
:page-revdate: {revdate}
:current-version: {page-component-version}

Si vous avez rencontré un message d'erreur comme le suivant{nbsp}:

 'fsck' found errors on device /dev/longhorn/pvc-6288f5ea-5eea-4524-a84f-afa14b85780d but could not correct them.

Alors vous avez une situation de corruption de données. Cette section décrit comment résoudre le problème.

== Mauvais disque sous-jacent

Pour déterminer si l'erreur est causée par un des disques sous-jacents défectueux, suivez xref:data-integrity-recovery/data-recovery/identify-corrupted-replicas.adoc[ces étapes] pour identifier les répliques corrompues.

Si la plupart des répliques sur le disque sont défectueuses, cela signifie que le disque est désormais peu fiable et doit être remplacé.

Si une seule réplique sur le disque est défectueuse, cela peut être une situation connue sous le nom de `bit rot`. Dans ce cas, retirer la réplique est suffisant.

== Récupérer à partir d'un instantané

Si toutes les répliques sont identiques, alors le volume doit être récupéré en utilisant des instantanés.

La raison en est probablement que le bit défectueux a été écrit à partir de la charge de travail à laquelle le volume était attaché.

Pour revenir à un instantané précédent{nbsp}:

. En mode maintenance, attachez le volume à n'importe quel nœud.
. Revenir à un instantané. Vous devriez commencer par le plus récent.
. Détachez le volume du nœud en mode maintenance
. Rattachez le volume à un nœud auquel vous avez accès.
. Montez le volume depuis `/dev/longhorn/<volume_name>` et vérifiez le contenu du volume.
. Si le contenu du volume est toujours incorrect, recommencez à partir de l'étape 1.
. Une fois que vous avez trouvé un instantané utilisable, créez un nouvel instantané à partir de celui-ci et commencez à utiliser le volume normalement.

== Récupérer à partir d'une sauvegarde

Si toutes les méthodes ci-dessus ont échoué, utilisez une sauvegarde pour xref:snapshots-backups/volume-snapshots-backups/restore-volume-from-backup.adoc[récupérer le volume.]
