= データエラーを特定し、回復する
:revdate: 2025-06-27
:page-revdate: {revdate}
:current-version: {page-component-version}

次のようなエラーメッセージに遭遇した場合：

 'fsck' found errors on device /dev/longhorn/pvc-6288f5ea-5eea-4524-a84f-afa14b85780d but could not correct them.

それはデータ破損の状況です。このセクションでは、問題に対処する方法を説明します。

== 基盤ディスクの不良

エラーが基盤ディスクのいずれかの不良によるものであるかを判断するには、xref:data-integrity-recovery/data-recovery/identify-corrupted-replicas.adoc[これらの手順]に従って破損したレプリカを特定してください。

ディスク上のレプリカの大部分が不良であれば、そのディスクは信頼できないものであり、交換する必要があります。

ディスク上のレプリカが1つだけ不良であれば、それは`bit rot`として知られる状況かもしれません。この場合、レプリカを削除するだけで十分です。

== スナップショットから回復する

すべてのレプリカが同一であれば、ボリュームはスナップショットを使用して回復する必要があります。

その理由は、おそらく不良ビットがボリュームに接続されたワークロードから書き込まれたためです。

以前のスナップショットに戻すには：

. メンテナンスモードで、ボリュームを任意のノードに接続します。
. スナップショットに戻します。最新のものから始めるべきです。
. メンテナンスモードからボリュームを任意のノードに切り離します。
. アクセスできるノードにボリュームを再接続します。
. `/dev/longhorn/<volume_name>`からボリュームをマウントし、ボリュームの内容を確認します。
. ボリュームの内容がまだ不正確な場合は、ステップ1から繰り返してください。
. 使えるスナップショットを見つけたら、そこから新しいスナップショットを作成し、通常通りボリュームを使用し始めてください。

== バックアップから復元する

上記のすべての方法が失敗した場合は、バックアップを使用してxref:snapshots-backups/volume-snapshots-backups/restore-volume-from-backup.adoc[ボリュームを復元してください。]
