= Instalación
:revdate: 2026-01-12
:page-revdate: {revdate}
:description: Instalar SUSE® Storage en Kubernetes
:doctype: book
:current-version: {page-component-version}

NOTE: Esta guía de instalación rápida utiliza algunas configuraciones que no son para uso en producción.
Por favor, consulta xref:installation-setup/best-practices.adoc[Mejores Prácticas] para saber cómo configurar {longhorn-product-name} para uso en producción.

{longhorn-product-name} se puede instalar en un clúster de Kubernetes de varias maneras:

* xref:installation-setup/installation/install-using-rancher.adoc[]
* xref:installation-setup/installation/install-using-helm.adoc[]
* xref:installation-setup/installation/install-using-fleet.adoc[]
* xref:installation-setup/installation/install-using-flux.adoc[]
* xref:installation-setup/installation/install-using-argocd.adoc[]

Para instalar {longhorn-product-name} en un entorno aislado, consulta xref:installation-setup/installation/airgapped-environment.adoc[Instalación Aislada].

Para información sobre cómo personalizar la configuración predeterminada, consulta xref:longhorn-system/customize-default-settings.adoc[Personalización de la Configuración Predeterminada].

Para información sobre cómo desplegar {longhorn-product-name} en nodos específicos y rechazar cargas de trabajo generales para esos nodos, consulta la sección sobre xref:nodes/taints-tolerations.adoc[Taints y Tolerations].
