= Instalar {longhorn-product-name} utilizando Helm
:revdate: 2026-01-12
:page-revdate: {revdate}
:current-version: {page-component-version}

== Requisitos previos

[NOTE]
====
{longhorn-product-name}La instalación de  requiere acceso autenticado a la Colección de Aplicaciones de SUSE. Para más detalles, consulta https://docs.apps.rancher.io/get-started/authentication[guía de autenticación].
====

=== Herramientas

* Se requiere https://helm.sh/docs/[Helm] v3.0 o posterior.
* La xref:longhorn-system/system-access/longhorn-cli.adoc[Longhorn herramientas shell] se puede utilizar para comprobar el entorno {longhorn-product-name} en busca de posibles problemas.

=== Kubernetes Environment

* Se requiere un clúster de Kubernetes, con cada nodo cumpliendo los xref:installation-setup/requirements.adoc[requisitos de instalación].

=== Autenticación

* Para autenticar Helm con el repositorio de gráficos OCI de la Colección de Aplicaciones de SUSE, consulta la https://docs.apps.rancher.io/get-started/authentication/#helm[documentación de autenticación de Helm].
* Para permitir que Kubernetes extraiga imágenes del registro, sigue la https://docs.apps.rancher.io/get-started/authentication/#kubernetes[documentación de autenticación de Kubernetes] para crear un secreto y establecer el valor del gráfico `global.imagePullSecrets`.

== Instalación

. Para instalar {longhorn-product-name} con la configuración predeterminada, ejecuta:
+
[subs="+attributes",shell]
----
helm install longhorn oci://dp.apps.rancher.io/charts/suse-storage \
  --namespace longhorn-system \
  --create-namespace \
  --version <version> \ # Replace with the version you would like to install
  --set global.imagePullSecrets=<PULL_IMAGE_SECRET>
----

. Para confirmar que la ampliación fue exitosa, ejecuta:
+
[,bash]
----
kubectl -n longhorn-system get pod
----
+
El resultado debería verse como el siguiente:
+
[,bash]
----
NAME                                                READY   STATUS    RESTARTS   AGE
longhorn-ui-b7c844b49-w25g5                         1/1     Running   0          2m41s
longhorn-manager-pzgsp                              1/1     Running   0          2m41s
longhorn-driver-deployer-6bd59c9f76-lqczw           1/1     Running   0          2m41s
longhorn-csi-plugin-mbwqz                           2/2     Running   0          100s
csi-snapshotter-588457fcdf-22bqp                    1/1     Running   0          100s
csi-snapshotter-588457fcdf-2wd6g                    1/1     Running   0          100s
csi-provisioner-869bdc4b79-mzrwf                    1/1     Running   0          101s
csi-provisioner-869bdc4b79-klgfm                    1/1     Running   0          101s
csi-resizer-6d8cf5f99f-fd2ck                        1/1     Running   0          101s
csi-provisioner-869bdc4b79-j46rx                    1/1     Running   0          101s
csi-snapshotter-588457fcdf-bvjdt                    1/1     Running   0          100s
csi-resizer-6d8cf5f99f-68cw7                        1/1     Running   0          101s
csi-attacher-7bf4b7f996-df8v6                       1/1     Running   0          101s
csi-attacher-7bf4b7f996-g9cwc                       1/1     Running   0          101s
csi-attacher-7bf4b7f996-8l9sw                       1/1     Running   0          101s
csi-resizer-6d8cf5f99f-smdjw                        1/1     Running   0          101s
instance-manager-b34d5db1fe1e2d52bcfb308be3166cfc   1/1     Running   0          114s
engine-image-ei-df38d2e5-cv6nc                      1/1     Running   0          114s
----

. Para habilitar el acceso a la interfaz de usuario, necesitarás configurar un controlador de Ingress. La autenticación en la interfaz de usuario no está habilitada por defecto. Para información sobre cómo crear un controlador de Ingress NGINX con autenticación básica, consulta xref:longhorn-system/system-access/create-ingress.adoc[sección de creación de ingress].
. Accede a la interfaz de usuario utilizando xref:longhorn-system/system-access/system-access.adoc[pasos de acceso al sistema].

=== Configuración

{longhorn-product-name}El Helm Chart proporciona amplias opciones de configuración según tus necesidades específicas. Puedes configurar estas opciones proporcionando un archivo `values.yaml` o utilizando los flags `--set` durante `helm install` o `helm upgrade`.

Los aspectos configurables comunes incluyen:

* **Clase de almacenamiento**: Configuración predeterminada de la clase de almacenamiento.
* **Configuración de la interfaz de usuario**: Configuración de Ingress, tipo de servicio y opciones de autenticación para la {longhorn-product-name} interfaz de usuario.
* **Configuración del gestor y del motor**: Límites de recursos, recuentos de réplicas y otros parámetros operativos para {longhorn-product-name}los componentes kernel.
* **Gestión de nodos y discos**: Provisionamiento automático de discos, selectores de nodos y tolerancias.
* **Controlador CSI**: Configuración específica para los componentes de la Interfaz de Almacenamiento de Contenedores.
* **Redes**: Tipos de servicio y políticas de red.

Para una lista completa de todos los parámetros disponibles y sus descripciones, consulta la documentación oficial del xref:installation-setup/installation/helm-values.adoc[{longhorn-product-name} Helm Chart] y el archivo `values.yaml` en el repositorio del chart.
