= InstantĂ¡nea de volumen CSI asociada a una instantĂ¡nea de SUSEÂ® Storage
:revdate: 2025-09-29
:page-revdate: {revdate}
:current-version: {page-component-version}

La instantĂ¡nea en Longhorn es un objeto que representa el contenido de un volumen Longhorn en un momento particular. Se almacena dentro del clĂºster.

Para crear instantĂ¡neas Longhorn programĂ¡ticamente, puedes utilizar el mecanismo genĂ©rico de CSI VolumeSnapshot de Kubernetes. Para aprender mĂ¡s sobre el mecanismo CSI VolumeSnapshot, haz clic https://kubernetes.io/docs/concepts/storage/volume-snapshots/[aquĂ­].

____
*Requisito previo:* El soporte de instantĂ¡neas CSI necesita estar habilitado en tu clĂºster.
Si tu distribuciĂ³n de Kubernetes no proporciona el controlador de instantĂ¡neas de Kubernetes, asĂ­ como las definiciones de recursos personalizadas relacionadas con las instantĂ¡neas, necesitas desplegarlos manualmente.
Para mĂ¡s informaciĂ³n, consulta xref:snapshots-backups/csi-snapshots/enable-csi-snapshot-creation.adoc[Habilitar soporte de instantĂ¡neas CSI].
____

== Crear una instantĂ¡nea de volumen CSI asociada a una instantĂ¡nea Longhorn

Para crear una instantĂ¡nea de volumen CSI asociada a una instantĂ¡nea Longhorn, primero necesitas crear un objeto `VolumeSnapshotClass` con el parĂ¡metro `type` establecido en `snap` de la siguiente manera:

[subs="+attributes",yaml]
----
kind: VolumeSnapshotClass
apiVersion: snapshot.storage.k8s.io/v1
metadata:
  name: longhorn-snapshot-vsc
driver: driver.longhorn.io
deletionPolicy: Delete
parameters:
  type: snap
----

Para mĂ¡s informaciĂ³n sobre `VolumeSnapshotClass`, consulta la documentaciĂ³n de Kubernetes para https://kubernetes.io/docs/concepts/storage/volume-snapshot-classes/[VolumeSnapshotClasses].

DespuĂ©s de eso, crea un objeto Kubernetes `VolumeSnapshot` con `volumeSnapshotClassName` que apunte al nombre del `VolumeSnapshotClass` (`longhorn-snapshot-vsc`) y `source` que apunte al PVC del volumen Longhorn para el cual se debe crear una instantĂ¡nea Longhorn.

[subs="+attributes",yaml]
----
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: test-csi-volume-snapshot-longhorn-snapshot
spec:
  volumeSnapshotClassName: longhorn-snapshot-vsc
  source:
    persistentVolumeClaimName: test-vol
----

*Resultado:*
Se crea una instantĂ¡nea Longhorn. La creaciĂ³n del objeto `VolumeSnapshot` conduce a la creaciĂ³n de un objeto Kubernetes `VolumeSnapshotContent`.
El `VolumeSnapshotContent` se refiere a una instantĂ¡nea Longhorn en su campo `VolumeSnapshotContent.snapshotHandle` con el nombre `snap://volume-name/snapshot-name`.

=== Visualizando la instantĂ¡nea Longhorn

Para ver la instantĂ¡nea, haz clic en *Volumen* en la barra de navegaciĂ³n superior y haz clic en el volumen mencionado en el `VolumeSnapshotContent.snapshotHandle`. DesplĂ¡zate hacia abajo para ver la lista de todas las instantĂ¡neas de volumen.

=== CĂ³mo funciona el mecanismo CSI en este escenario

Cuando se crea el objeto VolumeSnapshot con kubectl, se utiliza el campo `VolumeSnapshot.uuid` para identificar una instantĂ¡nea de Longhorn y el objeto `VolumeSnapshotContent` asociado.

Esto crea una nueva instantĂ¡nea de Longhorn llamada `snapshot-uuid` y se devuelve la solicitud CSI.

A continuaciĂ³n, se crea un objeto `VolumeSnapshotContent` llamado `snapcontent-uuid` con la bandera `VolumeSnapshotContent.readyToUse` establecida en *true*.

== Restaurar PVC desde el VolumeSnapshot CSI asociado con la instantĂ¡nea de Longhorn.

Crea un objeto `PersistentVolumeClaim` donde el campo `dataSource` apunta a un objeto `VolumeSnapshot` existente que estĂ¡ asociado con la instantĂ¡nea de Longhorn.

El csi-provisioner lo recogerĂ¡ e instruirĂ¡ al controlador CSI de Longhorn para aprovisionar un nuevo volumen con los datos de la instantĂ¡nea de Longhorn asociada.

Un ejemplo `PersistentVolumeClaim` se muestra a continuaciĂ³n. El campo `dataSource` necesita apuntar a un objeto `VolumeSnapshot` existente.

[subs="+attributes",yaml]
----
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-restore-pvc
spec:
  storageClassName: longhorn
  dataSource:
    name: test-csi-volume-snapshot-longhorn-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
----

[NOTE]
====
* El valor `spec.resources.requests.storage` debe coincidir con el tamaĂ±o del objeto `VolumeSnapshot`.
* Al restaurar un volumen desde un `VolumeSnapshot` asociado a un volumen del motor de datos V2, puedes especificar el modo de clonaciĂ³n utilizando un `StorageClass`.
** Establece el parĂ¡metro `cloneMode` en `full-copy` o `linked-clone`.
** Si no especificas el parĂ¡metro `cloneMode`, el valor por defecto es `full-copy`.

Para mĂ¡s informaciĂ³n, consulta xref:longhorn-system/v2-data-engine/features/volume-clone.adoc[la documentaciĂ³n sobre la compatibilidad de clonaciĂ³n de volĂºmenes V2].
====
