= Identificar Réplicas Corrompidas
:revdate: 2025-06-27
:page-revdate: {revdate}
:current-version: {page-component-version}

No caso de um dos discos usados pelo Longhorn apresentar problemas, você pode experimentar erros intermitentes de entrada/saída ao usar um volume do Longhorn.

Por exemplo, um arquivo às vezes não pode ser lido, mas depois pode. Nesse cenário, é provável que um dos discos tenha apresentado problemas, resultando em uma das réplicas retornando dados incorretos para o usuário.

Para recuperar o volume, podemos identificar a réplica corrompida e removê-la do volume:

. Reduza a carga de trabalho para desanexar o volume.
. Encontre todos os locais das réplicas verificando a interface do Longhorn. Os diretórios usados pelas réplicas serão exibidos como uma dica de ferramenta para cada réplica na interface.
. Faça login em cada nó que contém uma réplica do volume e acesse o diretório que contém os dados da réplica.
+
Por exemplo, a réplica pode estar armazenada em:

  /var/lib/longhorn/replicas/pvc-06b4a8a8-b51d-42c6-a8cc-d8c8d6bc65bc-d890efb2

. Execute um checksum para cada arquivo nesse diretório.
+
Por exemplo:
+
----
 # sha512sum /var/lib/longhorn/replicas/pvc-06b4a8a8-b51d-42c6-a8cc-d8c8d6bc65bc-d890efb2/*
 fcd1b3bb677f63f58a61adcff8df82d0d69b669b36105fc4f39b0baf9aa46ba17bd47a7595336295ef807769a12583d06a8efb6562c093574be7d14ea4d6e5f4  /var/lib/longhorn/replicas/pvc-06b4a8a8-b51d-42c6-a8cc-d8c8d6bc65bc-d890efb2/revision.counter
 c53649bf4ad843dd339d9667b912f51e0a0bb14953ccdc9431f41d46c85301dff4a021a50a0bf431a931a43b16ede5b71057ccadad6cf37a54b2537e696f4780  /var/lib/longhorn/replicas/pvc-06b4a8a8-b51d-42c6-a8cc-d8c8d6bc65bc-d890efb2/volume-head-000.img
 f6cd5e486c88cb66c143913149d55f23e6179701f1b896a1526717402b976ed2ea68fc969caeb120845f016275e0a9a5b319950ae5449837e578665e2ffa82d0  /var/lib/longhorn/replicas/pvc-06b4a8a8-b51d-42c6-a8cc-d8c8d6bc65bc-d890efb2/volume-head-000.img.meta
 e6f6e97a14214aca809a842d42e4319f4623adb8f164f7836e07dc8a3f4816a0389b67c45f7b0d9f833d50a731ae6c4670ba1956833f1feb974d2d12421b03f7  /var/lib/longhorn/replicas/pvc-06b4a8a8-b51d-42c6-a8cc-d8c8d6bc65bc-d890efb2/volume.meta
----

. Compare a saída de cada réplica. Uma delas deve falhar ou ter resultados diferentes em comparação com as outras. Esta será a réplica que precisamos remover do volume.
. Use a interface do Longhorn para remover a réplica identificada do volume.
. Aumente a carga de trabalho para garantir que o erro tenha sido resolvido.
