= 無効化されたディスクまたはノード上のレプリカを退避する
:revdate: 2025-06-27
:page-revdate: {revdate}
:current-version: {page-component-version}

Longhornは、選択された無効化されたディスクまたはノード上のレプリカを他の適切なディスクやノードに自動的に退避する機能をサポートしています。退避中も同じレベルの高可用性が維持されます。

NOTE: この退避機能は、選択されたディスクまたはノードのスケジューリングが無効化されている場合にのみ有効にできます。退避中は、選択されたディスクまたはノードをスケジューリングのために再有効化することはできません。

NOTE: この退避機能は、`Attached`および`Detached`のボリュームに対して機能します。ボリュームが「切り離されている」場合、Longhornは退避の前に自動的にそれをアタッチし、退避が完了したら自動的にデタッチします。

デフォルトでは、ディスクまたはノードの`Eviction Requested`は`false`です。退避中に同じレベルの高可用性を維持するために、Longhornはこのボリュームのレプリカの再構築が成功した後にのみ、ボリュームごとに1つのレプリカを退避します。

== 退避するディスクまたはノードを選択する

ノードのディスクを退避するには、

. 「`Node`」タブに移動して、1つのノードを選択し、ドロップダウンメニューから「`Edit Node and Disks`」を選択します。
. ディスクがスケジューリング用に無効化されていることを確認し、`Scheduling`を`Disable`に設定します。
. `Eviction Requested`を`true`に設定し、保存します。

ノードを退避するには、

. 「`Node`」タブに移動して、1つ以上のノードを選択し、`Edit Node`をクリックします。
. ノードがスケジューリング用に無効化されていることを確認し、`Scheduling`を`Disable`に設定します。
. `Eviction Requested`を`true`に設定し、保存します。

== ディスクまたはノードの退避をキャンセルする

ディスクまたはノードの退避をキャンセルするには、対応する`Eviction Requested`設定を`false`に設定します。

== 退避ステータスを確認する

選択したディスクまたはノードの`Replicas`の数は、退避が成功すると0に減少する必要があります。

「`Replicas`」の数字をクリックすると、そのディスク上のレプリカ名が表示されます。レプリカ名をクリックすると、Longhorn UIはウェブページを該当するボリュームのページにリダイレクトし、ボリュームのステータスを表示します。エラーが発生した場合（例：スペースがない、または別のスケジュール可能なディスクが見つからない（スケジュールエラー））、エラーが表示されます。すべてのエラーはイベントログに記録されます。

退避中にエラーが発生した場合、退避は新しいスペースがクリアされるまで一時停止されるか、キャンセルされます。退避がキャンセルされた場合、選択したディスクまたはノード上の残りのレプリカはディスクまたはノードに残ります。
