include::partial$longhorn-globals.adoc[]
= {product-name} Overview
:description: Cloud native distributed block storage for Kubernetes
:current-version: {page-component-version}

*{product-name}* is a lightweight, reliable, and powerful distributed https://cloudacademy.com/blog/object-storage-block-storage/[block storage] system for Kubernetes.

{product-name} is derived from the open source project called https://www.cncf.io/projects/longhorn/[Longhorn]. The name Longhorn is used interchangeably with {product-name} in this documentation.

{product-name} implements distributed block storage using containers and microservices. {product-name} creates a dedicated storage controller for each block device volume and synchronously replicates the volume across multiple replicas stored on multiple nodes. The storage controller and replicas are themselves orchestrated using Kubernetes.

== Features

* Enterprise-grade distributed block storage with no single point of failure
* Incremental snapshot of block storage
* Backup to secondary storage (https://www.extrahop.com/resources/protocols/nfs/[NFS] or https://aws.amazon.com/s3/[S3]-compatible object storage) built on efficient change block detection
* Recurring snapshots and backups
* Automated, non-disruptive upgrades. You can upgrade the entire {product-name} software stack without disrupting running storage volumes.
* An intuitive GUI dashboard
