= Copias de seguridad del sistema SUSE® Storage
:revdate: 2025-06-27
:page-revdate: {revdate}
:current-version: {page-component-version}

____
Las versiones anteriores permitían restaurar el sistema SUSE® Storage utilizando herramientas de terceros.
____

* xref:snapshots-backups/system-backups/restore-to-cluster-using-rancher-snapshot.adoc[Restaurar a un clúster que contiene datos utilizando la instantánea de Rancher]
* xref:snapshots-backups/system-backups/restore-to-new-cluster-using-velero.adoc[Restaurar a un nuevo clúster utilizando Velero]

____
Las versiones actuales de SUSE® Storage incluyen copias de seguridad y restauración del sistema listas para usar.

* Los recursos personalizados de SUSE® Storage se respaldarán y se agruparán en un único archivo de copia de seguridad del sistema, que luego se guardará en el destino de copia de seguridad remoto.
* Más tarde, puedes elegir una copia de seguridad del sistema para restaurar a un nuevo clúster o restaurar a un clúster existente.
____

* xref:snapshots-backups/system-backups/create-system-backup.adoc[Hacer copia de seguridad del sistema Longhorn]
* xref:snapshots-backups/system-backups/restore-system.adoc[Restaurar el sistema Longhorn]
