= Important Notes
:current-version: {page-component-version}

Please see https://github.com/longhorn/longhorn/releases/tag/v{current-version}[here] for the full release notes.

[WARNING]
====
An incorrect Longhorn image tag (v1.8.x-head) was used in the https://github.com/longhorn/longhorn/blob/v1.8.0/deploy/longhorn.yaml[deployment manifest] and the https://github.com/longhorn/longhorn/blob/v1.8.0/chart/values.yaml#L40-L65[Helm chart]. The correct tag for Longhorn v1.8.0 images is `v1.8.0`. For more information, see https://github.com/longhorn/longhorn/issues/10336[Issue #10336].

If you installed or upgraded Longhorn using the deployment manifest or the Helm chart from the https://github.com/longhorn/longhorn[main Longhorn repository], perform the following actions to resolve the issue:

- **New installations**: Replace `v1.8.x-head` with `v1.8.0` in the deployment manifest or the Helm chart before deploying Longhorn.

- **Upgrades**: Replace `v1.8.x-head` with `v1.8.0` in the deployment manifest or Helm chart. Next, upgrade the Longhorn system and update the engine image for volumes that use `v1.8.x-head`.

This issue does not affect installations and upgrades performed using the charts in the https://charts.longhorn.io/[Longhorn Helm repository]. For more information, see xref:installation-setup/installation/install-using-helm.adoc[Install with Helm].
====

== Removal

=== Remove Environment Check Script

The environment check script (`environment_check.sh`), which was deprecated in v1.7.0, has been removed in v1.9.0. Use the xref:longhorn-system/system-access/longhorn-cli.adoc[Longhorn Command Line Tool] to check the Longhorn environment for potential issues.

== Deprecation

=== Deprecate `longhorn.io/v1beta1` API

The `v1beta1` version of the Longhorn API is deprecated in v1.9.0 and will be removed in v1.10.0. During Longhorn system upgrades, custom resources using `longhorn.io/v1beta1` are automatically migrated to `longhorn.io/v1beta2`.

Deprecated APIs are no longer served and may cause undesirable behavior. Avoid using `longhorn.io/v1beta1` in new code and, if possible, update existing code to exclude this version.

== General

=== Kubernetes Version Requirement

The upgrade of the CSI external snapshotter to version v8.2.0 requires that all clusters run Kubernetes v1.25 or later. Ensure your Kubernetes version meets this requirement before you upgrade to {longhorn-product-name} v1.8.0 or a newer version.

=== CRD Upgrade Validation

During an upgrade, the Custom Resource Definition (CRD) might be applied after the new Longhorn Manager starts. This order helps prevent the controller from processing objects that contain deprecated data or fields. However, this sequencing can cause the Longhorn Manager to fail during the initial upgrade phase if the CRD is not yet applied.

If the Longhorn Manager crashes during the upgrade, check the logs to determine if the CRD not being applied is the cause of the failure. In such cases, the logs might contain error messages similar to the following:

[,log]
----
time="2025-03-27T06:59:55Z" level=fatal msg="Error starting manager: upgrade resources failed: BackingImage in version \"v1beta2\" cannot be handled as a BackingImage: strict decoding error: unknown field \"spec.diskFileSpecMap\", unknown field \"spec.diskSelector\", unknown field \"spec.minNumberOfCopies\", unknown field \"spec.nodeSelector\", unknown field \"spec.secret\", unknown field \"spec.secretNamespace\"" func=main.main.DaemonCmd.func3 file="daemon.go:94"
----

== System Backup And Restore

=== Recurring System Backup

You can create a recurring job for system backup creation. For more information, see https://github.com/longhorn/longhorn/issues/6534[Issue #6534].

== V2 Data Engine

=== Longhorn System Upgrade

Longhorn currently does not support live upgrading of V2 volumes. Ensure that all V2 volumes are detached before initiating the upgrade process.

=== Newly Introduced Functionalities since Longhorn v1.9.0

==== Performance Enhancement

* xref:longhorn-system/v2-data-engine/features/selective-engine-activation.adoc[Support UBLK Frontend]

==== Data Recovery

* https://github.com/longhorn/longhorn/issues/6613[Disaster recovery volumes]
* https://github.com/longhorn/longhorn/issues/8430[Auto-salvage volumes]
* https://github.com/longhorn/longhorn/issues/9488[Delta replica rebuilding using snapshot checksum]

==== Networking

* https://github.com/longhorn/longhorn/issues/6450[Storage Network]

==== Backing Image

* https://github.com/longhorn/longhorn/issues/10356[Encryption]