= Use a Volume as an iSCSI Target
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2026-06-01
:page-revdate: {revdate}
:current-version: {page-component-version}

{longhorn-product-name} supports iSCSI target front-end mode. You can connect to it through any iSCSI client, including `open-iscsi`, and virtual machine hypervisor like KVM, as long as it is in the same network as the Longhorn system.

The Longhorn CSI driver does not support iSCSI mode.

To start a volume with the iSCSI target front-end mode, select `iSCSI` as the front-end when xref:volumes/create-volumes.adoc[creating the volume].

After the volume has been attached, you will see something like the following in the `endpoint` field:

[subs="+attributes",text]
----
iscsi://10.42.0.21:3260/iqn.2014-09.com.rancher:testvolume/1
----

In this example,

* The IP and port is `10.42.0.21:3260`.
* The target name is `iqn.2014-09.com.rancher:testvolume`.
* The volume name is `testvolume`.
* The LUN number is 1. {longhorn-product-name} always uses LUN 1.

The above information can be used to connect to the iSCSI target provided by {longhorn-product-name} using an iSCSI client.
