= Meilleures pratiques
:revdate: 2026-02-03
:page-revdate: {revdate}
:current-version: {page-component-version}

La configuration suivante est recommandée pour les environnements de production.

== Matériel minimum recommandé

* 3 nœuds
* 4 vCPUs par nœud
* 4 GiB par nœud
* Dispositif de stockage SSD/NVMe ou similaire sur le nœud (recommandé)
* Dispositif de stockage HDD/Disque tournant ou similaire sur le nœud (vérifié)
 ** 500/250 IOPS max par volume (1 MiB E/S)
 ** 500/250 débit max par volume (MiB/s)

[WARNING]
====
Bien que {longhorn-product-name} puisse fonctionner avec des HDD (disques tournants) comme stockage, il est important de comprendre que *latence* joue un rôle beaucoup plus important dans la stabilité des volumes que les IOPS ou le débit. C'est parce que les HDD sont mécaniques, s'appuyant sur des plateaux tournants et des têtes de lecture ou d'écriture mobiles pour accéder aux données. Ce mouvement physique introduit des délais inhérents (temps de recherche et délai de rotation), entraînant une latence beaucoup plus élevée par rapport aux SSD ou aux disques NVMe, qui utilisent de la mémoire flash et n'ont pas de pièces mobiles. Cela peut directement causer de l'instabilité, surtout lorsque plusieurs tâches intensives en entrée/sortie sont en cours d'exécution, telles que{nbsp}:

* Opérations d'E/S en avant vers les répliques
* Opérations d'E/S en avant depuis les répliques
* Reconstruction des volumes
* Sauvegardes ou autres charges de travail

L'augmentation de la latence due à l'utilisation de HDD, combinée à d'autres charges de travail en entrée/sortie, peut entraîner *instabilité des volumes*. Par conséquent, nous recommandons des disques *SSD ou NVMe* pour de meilleures performances et stabilité, en particulier pour les charges de travail de production.

Les IOPS et le débit mentionnés (500/250 IOPS max par volume et 500/250 débit max par volume) sont destinés à servir de références générales basées sur la configuration de test mais *ne doivent pas être considérés comme des exigences strictes*. La latence, et pas seulement le débit, est le facteur le plus important pour garantir la stabilité du système.
====

== Architecture

{longhorn-product-name} prend en charge les architectures suivantes{nbsp}:

. AMD64
. ARM64

== Système d'exploitation

[NOTE]
====
CentOS Linux a été retiré de la liste des systèmes d'exploitation vérifiés ci-dessous, car il a été abandonné au profit de CentOS Stream [https://www.redhat.com/en/blog/faq-centos-stream-updates#Q5[ref]], une distribution Linux en rolling release. Les tests pour les distributions open-source en aval basées sur RHEL se concentrent sur des versions de niveau entreprise, telles que Rocky Linux et Oracle Linux.
====

Les distributions et versions de systèmes d'exploitation Linux suivantes ont été vérifiées lors des tests de version v{patch-version}. Cependant, cela n'implique pas que {longhorn-product-name} prenne exclusivement en charge ces distributions. {longhorn-product-name} devrait bien fonctionner sur tout cluster Kubernetes certifié fonctionnant sur des nœuds Linux avec une large gamme de systèmes d'exploitation généralistes, ainsi que sur des systèmes d'exploitation optimisés pour les conteneurs comme SLE Micro.

|===
| Non. | SE | Versions

| 1.
| Ubuntu
| 24.04

| 2.
| SUSE Linux Enterprise Server
| 16

| 3.
| SUSE Linux Enterprise Micro
| 6.1

| 4.
| Red Hat Enterprise Linux
| 10.1
|===

{longhorn-product-name} s'appuie fortement sur la fonctionnalité du noyau Linux et fonctionne mieux sur certaines versions du noyau Linux. Les activités suivantes, en particulier, bénéficient de l'utilisation de versions spécifiques du noyau Linux.

* Optimiser ou améliorer le système de fichiers{nbsp}: Utilisez un noyau Linux avec la version `v5.8` ou ultérieure. Voir https://github.com/longhorn/longhorn/issues/2507#issuecomment-857195496[Problème #2507] pour plus de détails.
* Activer le paramètre xref:longhorn-system/settings.adoc#_freeze_filesystem_for_snapshot[Geler le système de fichiers pour l'instantané]{nbsp}: Utilisez un noyau Linux avec la version `5.17` ou ultérieure pour garantir qu'un crash de volume pendant un gel du système de fichiers ne puisse pas bloquer un nœud.
* Activer le xref:longhorn-system/v2-data-engine/prerequisites.adoc[Moteur de données V2]{nbsp}: Utilisez un noyau Linux avec la version `5.19` ou ultérieure pour garantir

La liste ci-dessous contient les versions du noyau Linux connues défectueuses que les utilisateurs devraient éviter d'utiliser{nbsp}:

|===
| Non. | Version | Distro | Contexte supplémentaire

| 1.
| 6.5.6
| Noyau Linux vanilla
| Lié à ce bug https://longhorn.io/kb/troubleshooting-rwx-volume-fails-to-attached-caused-by-protocol-not-supported/

| 2.
| 5.15.0-94
| Ubuntu
| Lié à ce bug https://longhorn.io/kb/troubleshooting-rwx-volume-fails-to-attached-caused-by-protocol-not-supported/

| 3.
| 6.5.0-21
| Ubuntu
| Lié à ce bug https://longhorn.io/kb/troubleshooting-rwx-volume-fails-to-attached-caused-by-protocol-not-supported/

| 4.
| 6.5.0-1014-aws
| Ubuntu
| Lié à ce bug https://longhorn.io/kb/troubleshooting-rwx-volume-fails-to-attached-caused-by-protocol-not-supported/
|===

== Kubernetes

=== Kubernetes Version

Assurez-vous que votre cluster exécute Kubernetes v1.21 ou une version ultérieure avant de mettre à niveau {longhorn-product-name}.

Nous recommandons d'exécuter votre cluster Kubernetes sur l'une des versions suivantes. Ces versions sont les versions actives prises en charge avant la version {longhorn-product-name}, et ont été testées avec {longhorn-product-name} v{patch-version}.

|===
| Version | Publiée | Fin du service

| 1.35
| 17 décembre 2025
| 28 février 2027

| 1.34
| 27 août 2025
| 27 octobre 2026

| 1.33
| 23 avril 2025
| 28 juin 2026

| 1.32
| 11 décembre 2024
| 28 février 2026
|===

Référencé à https://endoflife.date/kubernetes.

=== Configuration de CoreDNS

Assurez-vous que CoreDNS fonctionne avec au moins deux réplicas pour maintenir une haute disponibilité. Cette configuration minimise les interruptions dans la résolution DNS lorsqu'un pod CoreDNS subit une perturbation temporaire.

== Configuration des nœuds et des disques

Nous recommandons la configuration suivante pour les nœuds et les disques.

=== Utilisez un disque dédié

Il est recommandé de dédier un disque pour le stockage de {longhorn-product-name} en production, au lieu d'utiliser le disque racine.

=== Stockage disponible minimal et surprovisionnement

Si vous devez utiliser le disque racine, utilisez la configuration par défaut de `minimal available storage percentage` qui est de 25 %, et réglez `overprovisioning percentage` à 100 % pour minimiser le risque de pression sur le disque.

Si vous utilisez un disque dédié pour {longhorn-product-name}, vous pouvez abaisser le réglage `minimal available storage percentage` à 10 %.

Pour le pourcentage de surprovisionnement, cela dépend de l'espace que votre volume utilise en moyenne. Par exemple, si votre charge de travail n'utilise que la moitié de la taille du volume disponible, vous pouvez régler le pourcentage de surprovisionnement à `200`, ce qui signifie que {longhorn-product-name} considère le disque comme ayant une taille planifiable deux fois supérieure à sa taille totale moins l'espace réservé.

=== Gestion de l'espace disque

Puisque {longhorn-product-name} ne prend actuellement pas en charge le partitionnement entre les différents disques, nous recommandons d'utiliser https://en.wikipedia.org/wiki/Logical_Volume_Manager_(Linux)[LVM] pour agréger tous les disques pour {longhorn-product-name} en une seule partition, afin qu'elle puisse être facilement étendue à l'avenir.

=== Configuration des disques supplémentaires

Tous les disques supplémentaires doivent être écrits dans le fichier `/etc/fstab` pour permettre un montage automatique après le redémarrage de la machine.

N'utilisez pas de lien symbolique pour les disques supplémentaires. Utilisez `mount --bind` au lieu de `ln -s` et assurez-vous qu'il se trouve dans le fichier `fstab`. Pour plus de détails, voir xref:nodes/multiple-disks.adoc#_use_an_alternative_path_for_a_disk_on_the_node[la section sur le support de plusieurs disques.]

=== Configuration des disques par défaut avant et après l'installation

Pour utiliser un répertoire autre que le `/var/lib/longhorn` par défaut pour le stockage, le paramètre `Default Data Path` peut être modifié avant d'installer le système. Pour des détails sur la modification des paramètres avant l'installation, reportez-vous à xref:longhorn-system/customize-default-settings.adoc[cette section.]

La fonctionnalité xref:nodes/default-disk-and-node-config.adoc[Configuration par défaut des nœuds/disques] peut être utilisée pour personnaliser le disque par défaut après l'installation. Personnaliser les configurations par défaut pour les disques et les nœuds est utile pour l'évolutivité du cluster car cela élimine le besoin de configurer {longhorn-product-name} manuellement pour chaque nouveau nœud si le nœud contient plus d'un disque, ou si la configuration du disque est différente pour les nouveaux nœuds. N'oubliez pas d'activer `Create default disk only on labeled node` si applicable.

== Optimisation des performances des volumes

Avant de configurer les charges de travail, assurez-vous d'avoir mis en place les exigences de base suivantes pour des performances optimales des volumes.

* SSDs SATA/NVMe ou disques durs avec des performances similaires
* Bande passante réseau de 10 Gbps entre les nœuds
* Classe de priorité dédiée pour les composants gérés par le système et déployés par l'utilisateur {longhorn-product-name}. Par défaut, {longhorn-product-name} installe la classe de priorité par défaut `longhorn-critical`.

Les sections suivantes décrivent d'autres recommandations pour les environnements de production.

=== Performances d'E/S

* *Réseau de stockage*{nbsp}: Utilisez un xref:longhorn-system/networking/storage-network.adoc#_setting_storage_network[réseau de stockage dédié] pour améliorer les performances d'E/S et la stabilité.
* *{longhorn-product-name} disque*{nbsp}: Utilisez un xref:nodes/multiple-disks.adoc#_add_a_disk[disque dédié] pour le stockage {longhorn-product-name} au lieu d'utiliser le disque racine.
* *Nombre de répliques*{nbsp}: Définissez le xref:longhorn-system/settings.adoc#_default_replica_count[nombre de répliques par défaut] sur "2" pour atteindre la disponibilité des données avec une meilleure utilisation de l'espace disque ou un impact réduit sur les performances du système. Cette pratique est particulièrement bénéfique pour les applications intensives en données.
* *Étiquette de stockage*: Utilisez xref:nodes/storage-tags.adoc[les étiquettes de stockage] pour définir le niveau de stockage pour les applications intensives en données. Par exemple, seuls des disques haute performance peuvent être utilisés pour stocker des données sensibles à la performance.
* *Localité des données*: Utilisez `best-effort` comme la xref:high-availability/data-locality.adoc[localité des données] par défaut des {longhorn-product-name} StorageClasses.
+
Pour les applications qui prennent en charge la réplication des données (par exemple, une base de données distribuée), vous pouvez utiliser l'option `strict-local` pour garantir qu'une seule réplique est créée pour chaque volume. Cette pratique empêche l'utilisation excessive de l'espace disque et la surcharge des performances d'E/S associée à la réplication des volumes.
+
Pour les applications intensives en données, vous pouvez utiliser des fonctions de planification de pods telles que le sélecteur de nœuds ou la tolérance aux taints. Ces fonctions vous permettent de planifier la charge de travail sur un nœud étiqueté de stockage spécifique avec une seule réplique.

=== Efficacité de l'espace

* *Instantanés récurrents*: Nettoyez périodiquement les instantanés générés par le système et conservez uniquement le nombre d'instantanés qui a du sens pour votre mise en œuvre.
+
Pour les applications avec capacité de réplication, supprimez périodiquement xref:introduction/concepts.adoc#_2_4_3_deleting_snapshots[tous les types d'instantanés].

* *Trim récurrent du système de fichiers*: Périodiquement, xref:volumes/trim-filesystem.adoc[procédez au trim du système de fichiers] à l'intérieur des volumes pour récupérer de l'espace disque.
* *Gestion de l'espace des instantanés*: xref:snapshots-backups/volume-snapshots-backups/snapshot-space-management.adoc[Configurez les paramètres globaux et spécifiques aux volumes] pour éviter l'épuisement inattendu de l'espace disque.

=== Reprise après sinistre

* *Sauvegardes récurrentes*: Créez xref:snapshots-backups/volume-snapshots-backups/create-recurring-backup-snapshot-job.adoc[des tâches de sauvegarde récurrentes] pour les volumes d'applications critiques.
* *Sauvegarde du système*: Créez des xref:snapshots-backups/system-backups/create-system-backup.adoc#_create_a_longhorn_system_backup[sauvegardes système] périodiques.

== Déploiement des charges de travail

Si vous utilisez `ext4` comme système de fichiers du volume, nous vous recommandons d'ajouter une vérification de vivacité aux charges de travail pour aider à récupérer automatiquement d'une interruption causée par le réseau, d'un redémarrage de nœud ou d'un redémarrage de Docker. Voir xref:high-availability/volume-recovery.adoc[cette section] pour plus de détails.

== Maintenance des volumes

Il est fortement recommandé d'utiliser la fonction de sauvegarde intégrée de {longhorn-product-name}. Vous pouvez enregistrer des sauvegardes dans un stockage d'objets tel que S3 ou sur un serveur NFS. L'enregistrement dans un stockage d'objets est préférable car il offre généralement une meilleure fiabilité. Un autre avantage est que vous n'avez pas besoin de monter et démonter la cible, ce qui peut compliquer le basculement et les mises à niveau.

Pour chaque volume, planifiez au moins une sauvegarde récurrente. Si vous devez exécuter {longhorn-product-name} en production sans un stockage de sauvegarde, alors planifiez au moins un instantané récurrent pour chaque volume.

{longhorn-product-name} crée des instantanés automatiquement lors de la reconstruction d'une réplique. Les instantanés ou sauvegardes récurrents peuvent également nettoyer automatiquement l'instantané généré par le système.

=== Gestionnaire d'instances UC garanti

Nous vous recommandons de définir la demande d'UC pour les pods du gestionnaire d'instances {longhorn-product-name}.

=== Moteur de données V1

Le paramètre `Guaranteed Instance Manager CPU` vous permet de réserver un pourcentage des ressources UC allouables totales sur chaque nœud pour chaque pod de gestionnaire d'instances lorsque le moteur de données V1 est activé. La valeur par défaut est de 12.

Définissez une valeur spécifique en milli-UC pour les pods du gestionnaire d'instances sur un nœud particulier en mettant à jour le champ de demande d'UC du gestionnaire d'instances pour ce nœud.

[NOTE]
====
Ce champ remplace le paramètre ci-dessus pour le nœud spécifié.
====

Référez-vous à xref:longhorn-system/settings.adoc#_guaranteed_instance_manager_cpu[Gestionnaire d'instances UC garanti] pour plus de détails.

=== Moteur de Données V2

Le paramètre `Guaranteed Instance Manager CPU for V2 Data Engine` vous permet de réserver un nombre spécifique de milli-UC sur chaque nœud pour chaque pod de gestionnaire d'instances lorsque le Moteur de Données V2 est activé. Par défaut, le daemon cible du Kit de Développement de Performance de Stockage (SPDK) au sein de chaque pod de gestionnaire d'instances utilise 1 noyau d'UC. Configurer une valeur minimale d'utilisation de l'UC est essentiel pour maintenir la stabilité du moteur et des répliques, surtout pendant les périodes de forte charge de travail sur le nœud. La valeur par défaut est 1250.

== Classe de Stockage

Évitez de modifier la Classe de Stockage par défaut nommée `longhorn`. Changer ses paramètres peut causer des problèmes lors des futures mises à niveau. Pour changer les paramètres définis dans la Classe de Stockage, vous pouvez créer une nouvelle Classe de Stockage en vous référant aux xref:longhorn-system/examples-resources.adoc#_storageclass[exemples de Classe de Stockage].

== Paramètres de Planification

=== Niveau de Réplica Nœud Anti-Affinité Souple

Recommandation{nbsp}: `false`

Ce paramètre doit être défini sur `false` dans un environnement de production pour garantir la meilleure disponibilité du volume. Sinon, un événement de défaillance d'un nœud peut entraîner la défaillance de plus d'une réplique d'un volume.

=== Autoriser la Création de Volumes avec Disponibilité Dégradée

Recommandation{nbsp}: `false`

Désactivez ce paramètre (`false`) dans les environnements de production pour garantir une disponibilité maximale du volume lors de sa création. Lorsqu'il est activé (`true`), la création de volumes réussit même si le système ne peut planifier qu'une seule réplique. Cela crée un risque où le cluster manque d'espace sans notifier immédiatement l'utilisateur.

=== Équilibre Automatique des Répliques

Recommandation{nbsp}: `least-effort`

Pour les environnements de production, nous recommandons de régler l'Équilibre Automatique des Répliques sur `least-effort`. Ce paramètre garantit qu'au moins une réplique est placée sur un nœud différent dans chaque zone, offrant une haute disponibilité (HA) supplémentaire.

Dans certains cas particuliers, vous pourriez envisager d'utiliser le `best-effort`, qui tente en continu de répartir uniformément les répliques sur les nœuds et les zones. Cependant, ce paramètre peut entraîner des reconstructions fréquentes si le cluster est instable.

Pour la plupart des utilisateurs, avoir plusieurs répliques sans réglage de l'Équilibre Automatique des Répliques est suffisant pour atteindre une HA de base, surtout si vous préférez éviter des reconstructions excessives et une utilisation excessive des ressources.
