= Argo CDを使用して{longhorn-product-name}をインストールします。
:revdate: 2026-01-12
:page-revdate: {revdate}
:current-version: {page-component-version}

== 前提条件

[NOTE]
====
{longhorn-product-name}のインストールには、SUSE Application Collectionへの認証されたアクセスが必要です。詳細については、 https://docs.apps.rancher.io/get-started/authentication[認証ガイド]を確認してください。
====

* あなたのワークステーション： https://argo-cd.readthedocs.io/en/stable/cli_installation/[Argo CD CLI]をインストールします。
* Kubernetesクラスタ：
 ** 各ノードがxref:installation-setup/requirements.adoc[インストール要件]を満たしていることを確認してください。
 ** https://argo-cd.readthedocs.io/en/stable/[Argo CD]をインストールします。
+
[,bash]
----
kubectl create namespace argocd
kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/core-install.yaml
----
+
`argocd`ネームスペース内でArgo CDコンポーネントのデプロイメントに少し時間をかけてください。

____
xref:longhorn-system/system-access/longhorn-cli.adoc[Longhornコマンドラインツール]を使用して、{longhorn-product-name}環境の潜在的な問題を確認できます。
____

== インストール

. Argo CDにログインします。
+
[,bash]
----
 argocd login --core
----

. 現在のネームスペースを`argocd`に設定します。
+
[,bash]
----
 kubectl config set-context --current --namespace=argocd
----

. {longhorn-product-name}アプリケーションカスタムリソースを作成します。
+
[subs="+attributes",bash]
----
cat > longhorn-application.yaml <<EOF
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: default
  sources:
    - chart: longhorn
      repoURL: https://charts.longhorn.io/
      targetRevision: v{{<current-version>}} # Replace with the Longhorn version you'd like to install or upgrade to
      helm:
        values: |
          preUpgradeChecker:
            jobEnabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  # add ignoreDifferences to prevent preserveUnknownFields field from make causing the application to be out of sync
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: engineimages.longhorn.io
      jsonPointers: ["/spec/preserveUnknownFields"]
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: engines.longhorn.io
      jsonPointers: ["/spec/preserveUnknownFields"]
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: instancemanagers.longhorn.io
      jsonPointers: ["/spec/preserveUnknownFields"]
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: nodes.longhorn.io
      jsonPointers: ["/spec/preserveUnknownFields"]
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: replicas.longhorn.io
      jsonPointers: ["/spec/preserveUnknownFields"]
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: settings.longhorn.io
      jsonPointers: ["/spec/preserveUnknownFields"]
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: volumes.longhorn.io
      jsonPointers: ["/spec/preserveUnknownFields"]
EOF
kubectl apply -f longhorn-application.yaml
----

. 設定された設定で{longhorn-product-name}をデプロイします。
+
[,bash]
----
 argocd app sync longhorn
----

. {longhorn-product-name}が正常にインストールされたことを確認します。
+
[,bash]
----
 kubectl -n longhorn-system get pod
----
+
正常なインストールの例：
+
[,bash]
----
 NAME                                                READY   STATUS    RESTARTS   AGE
 longhorn-ui-b7c844b49-w25g5                         1/1     Running   0          2m41s
 longhorn-manager-pzgsp                              1/1     Running   0          2m41s
 longhorn-driver-deployer-6bd59c9f76-lqczw           1/1     Running   0          2m41s
 longhorn-csi-plugin-mbwqz                           2/2     Running   0          100s
 csi-snapshotter-588457fcdf-22bqp                    1/1     Running   0          100s
 csi-snapshotter-588457fcdf-2wd6g                    1/1     Running   0          100s
 csi-provisioner-869bdc4b79-mzrwf                    1/1     Running   0          101s
 csi-provisioner-869bdc4b79-klgfm                    1/1     Running   0          101s
 csi-resizer-6d8cf5f99f-fd2ck                        1/1     Running   0          101s
 csi-provisioner-869bdc4b79-j46rx                    1/1     Running   0          101s
 csi-snapshotter-588457fcdf-bvjdt                    1/1     Running   0          100s
 csi-resizer-6d8cf5f99f-68cw7                        1/1     Running   0          101s
 csi-attacher-7bf4b7f996-df8v6                       1/1     Running   0          101s
 csi-attacher-7bf4b7f996-g9cwc                       1/1     Running   0          101s
 csi-attacher-7bf4b7f996-8l9sw                       1/1     Running   0          101s
 csi-resizer-6d8cf5f99f-smdjw                        1/1     Running   0          101s
 instance-manager-b34d5db1fe1e2d52bcfb308be3166cfc   1/1     Running   0          114s
 engine-image-ei-df38d2e5-cv6nc                      1/1     Running   0          114s
----

. xref:longhorn-system/system-access/create-ingress.adoc[基本認証を使用してNGINX Ingressコントローラーを作成]し、UIにアクセスします。UIへの認証はデフォルトで有効になっていません。
. xref:longhorn-system/system-access/system-access.adoc[UIにアクセスします]。
