= Contributing
:weight: 6
:current-version: {page-origin-branch}

Longhorn is open source software, so contributions are greatly welcome. Please read the https://github.com/cncf/foundation/blob/master/code-of-conduct.md[Cloud Native Computing Foundation Code of Conduct] and https://github.com/longhorn/longhorn/blob/master/CONTRIBUTING.md[Contributing Guidelines] before contributing.

Contributing code is not the only way of contributing. We value feedback very much and many of the Longhorn features are originated from users' feedback. If you have any feedback, feel free to https://github.com/longhorn/longhorn/issues/new/choose[file an issue] and talk to the developers at the https://slack.cncf.io/[CNCF] https://cloud-native.slack.com/messages/longhorn[#longhorn] slack channel.

Longhorn is a https://www.cncf.io/projects/longhorn/[CNCF Incubating Project.]

image::https://raw.githubusercontent.com/cncf/artwork/master/other/cncf/horizontal/color/cncf-color.svg[Longhorn is a CNCF Incubating Project]

== Source Code

Longhorn is 100% open source software under the auspices of the https://cncf.io[Cloud Native Computing Foundation]. The project's source code is spread across a number of repos:

|===
| Component | What it does | GitHub repo

| Longhorn Backing Image Manager
| Backing image download, sync, and deletion in a disk
| https://github.com/longhorn/backing-image-manager[longhorn/backing-image-manager]

| Longhorn Engine
| Core controller/replica logic
| https://github.com/longhorn/longhorn-engine[longhorn/longhorn-engine]

| Longhorn Instance Manager
| Controller/replica instance lifecycle management
| https://github.com/longhorn/longhorn-instance-manager[longhorn/longhorn-instance-manager]

| Longhorn Manager
| Longhorn orchestration, includes CSI driver for Kubernetes
| https://github.com/longhorn/longhorn-manager[longhorn/longhorn-manager]

| Longhorn Share Manager
| NFS provisioner that exposes Longhorn volumes as ReadWriteMany volumes
| https://github.com/longhorn/longhorn-share-manager[longhorn/longhorn-share-manager]

| Longhorn UI
| The Longhorn dashboard
| https://github.com/longhorn/longhorn-ui[longhorn/longhorn-ui]
|===

== License

Copyright (c) 2014-2021 The Longhorn Authors.

Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0[Apache License 2.0].

Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
