= Upgrade Longhorn Manager
:current-version: {page-component-version}

== Upgrade

Upgrading the {longhorn-product-name} Helm chart involves updating your deployment to a newer version or switching between Longhorn community images and {longhorn-product-name} images.

The general Helm command for upgrading is:

[,shell]
----
helm upgrade longhorn oci://dp.apps.rancher.io/charts/suse-storage \
  --namespace longhorn-system \
  --version <new-version> \
  --set global.imagePullSecrets={application-collection} \
  -f values.yaml
----

Or, if upgrading without a specific `values.yaml` file and only changing the version:

[,shell]
----
helm upgrade longhorn oci://dp.apps.rancher.io/charts/suse-storage \
  --namespace longhorn-system \
  --version <new-version> \
  --set global.imagePullSecrets={application-collection}
----

* **Upgrade Path**: Refer to the official xref:upgrades/upgrades.adoc[SUSE Storage upgrade documentation] for specific version-to-version upgrade paths, prerequisites, and post-upgrade verification steps. This is important to ensure a smooth upgrade and data integrity.
* **Configuration Changes**: If you have custom configurations, ensure you carry them over to the new chart version, merging with any default changes.
