= Conventions de documents
:revdate: 2025-06-27
:page-revdate: {revdate}

== Étiquettes de version

Chaque version mineure est supportée jusqu'à ce que la prochaine version mineure devienne stable.

* *Dev*{nbsp}: Le logiciel est en cours de développement actif et n'a pas été testé de manière approfondie. La mise à niveau depuis des versions antérieures ou vers des versions ultérieures n'est pas supportée. Les versions "Dev" se produisent généralement à la fin d'un sprint et peuvent se produire lorsque d'autres définitions de terminé sont respectées. Étant donné la nature non officielle de la version, utilisez le logiciel uniquement à des fins de test.

* *Dernier*{nbsp}: Le logiciel a passé toutes les étapes de vérification et de test. Tous les problèmes connus restants sont considérés comme acceptables. Utilisez le logiciel uniquement à des fins de test.

* *Stable*{nbsp}: Le logiciel est considéré comme fiable et exempt de problèmes critiques. Cette version est recommandée pour un usage général.

* *EOL*{nbsp}: Le logiciel a atteint la fin de sa durée de vie utile et aucun entretien au niveau du code n'est fourni. Vous pouvez continuer à utiliser le logiciel dans les termes de l'accord de licence. Il est recommandé de passer à une version stable.

[NOTE]
====
{longhorn-product-name} fournit une documentation sur les nouvelles fonctionnalités, les améliorations et les correctifs mis en œuvre dans les versions majeures, mineures et de correctif.
====

== Étiquettes de fonctionnalités :

Les fonctionnalités étiquetées **Expérimental** et **Avant-première technique** offrent un aperçu des innovations à venir et offrent des opportunités de tester de nouvelles technologies dans votre environnement.

* *Expérimental*: La fonctionnalité est incomplète mais son fonctionnement essentiel est opérationnel. Des tests dans un environnement contrôlé ont montré qu'elle peut coexister avec des fonctionnalités stables existantes. En raison des composants manquants et/ou de la fonctionnalité en évolution, la fonctionnalité n'est pas recommandée pour une utilisation dans des environnements de production.

* *Avant-première technique*: La fonctionnalité est presque complète et son fonctionnement ne devrait pas changer de manière significative. Des tests dans un environnement contrôlé ont montré qu'elle peut coexister avec des fonctionnalités stables existantes. Explorez la fonctionnalité en profondeur avant de l'utiliser dans des environnements de production.

Ces fonctionnalités ont les limitations suivantes :

* Encore en développement et peuvent être fonctionnellement incomplètes, instables ou d'une autre manière inadaptées à une utilisation en production.
* Non prise en charge.
* Peut être disponible uniquement pour des architectures matérielles spécifiques. Les détails et la fonctionnalité sont susceptibles de changer. Il en résulte que la mise à niveau vers des versions ultérieures peut être impossible et peut nécessiter une nouvelle installation.
* Peut être supprimé du produit à tout moment. Cela peut se produire, par exemple, si nous découvrons que la fonctionnalité ne répond pas aux besoins des clients ou du marché, ou ne respecte pas les normes de l'entreprise.

[NOTE]
====
Les fonctionnalités *Expérimental* et *Avant-première technique* sont généralement désactivées par défaut. La documentation fournit des informations sur la manière dont vous pouvez activer et configurer de telles fonctionnalités.
====

== Avertissements :

Les admonitions sont des blocs de texte qui fournissent des informations supplémentaires ou importantes. Chaque bloc de texte est marqué par une étiquette et une icône spéciales.

* *Remarque*: Informations supplémentaires qui sont utiles mais non critiques.

* *Important*: Informations qui nécessitent une attention particulière, telles que des changements dans le comportement du produit.

* *Conseil*: Conseils et suggestions utiles, tels que des méthodes alternatives pour accomplir une tâche.

* *Attention*: Informations à prendre en compte avant de procéder à des actions spécifiques, telles que des erreurs qui peuvent survenir.

* *Avertissement*: Informations critiques sur des conséquences nuisibles, telles que des dommages irréversibles et la perte de données.