= Installieren Sie {longhorn-product-name} mit Helm
:revdate: 2026-01-12
:page-revdate: {revdate}
:current-version: {page-component-version}

== Voraussetzungen

[NOTE]
====
{longhorn-product-name}Die Installation von erfordert authentifizierten Zugriff auf die SUSE Application Collection. Für weitere Details, überprüfen Sie https://docs.apps.rancher.io/get-started/authentication[den Authentifizierungsleitfaden].
====

=== Werkzeuge

* https://helm.sh/docs/[Helm] Version 3.0 oder neuer ist erforderlich.
* Das xref:longhorn-system/system-access/longhorn-cli.adoc[Longhorn-Kommandozeilenwerkzeug] kann verwendet werden, um die {longhorn-product-name} Umgebung auf potenzielle Probleme zu überprüfen.

=== Kubernetes Environment

* Ein Kubernetes-Cluster, bei dem jeder Knoten die xref:installation-setup/requirements.adoc[Installationsanforderungen] erfüllt, ist erforderlich.

=== Authentifizierung

* Um Helm mit dem OCI-Chart-Repository der SUSE Application Collection zu authentifizieren, beziehen Sie sich auf die https://docs.apps.rancher.io/get-started/authentication/#helm[Dokumentation zur Helm-Authentifizierung].
* Um Kubernetes zu ermöglichen, Bilder aus der Registry zu ziehen, folgen Sie der https://docs.apps.rancher.io/get-started/authentication/#kubernetes[Dokumentation zur Kubernetes-Authentifizierung], um ein Secret zu erstellen und den `global.imagePullSecrets` Chart-Wert festzulegen.

== Installation

. Installieren Sie {longhorn-product-name} mit der Standardkonfiguration, führen Sie aus:
+
[subs="+attributes",shell]
----
helm install longhorn oci://dp.apps.rancher.io/charts/suse-storage \
  --namespace longhorn-system \
  --create-namespace \
  --version <version> \ # Replace with the version you would like to install
  --set global.imagePullSecrets=<PULL_IMAGE_SECRET>
----

. Um zu bestätigen, dass die Implementierung erfolgreich war, führen Sie aus:
+
[,bash]
----
kubectl -n longhorn-system get pod
----
+
Das Ergebnis sollte folgendermaßen aussehen:
+
[,bash]
----
NAME                                                READY   STATUS    RESTARTS   AGE
longhorn-ui-b7c844b49-w25g5                         1/1     Running   0          2m41s
longhorn-manager-pzgsp                              1/1     Running   0          2m41s
longhorn-driver-deployer-6bd59c9f76-lqczw           1/1     Running   0          2m41s
longhorn-csi-plugin-mbwqz                           2/2     Running   0          100s
csi-snapshotter-588457fcdf-22bqp                    1/1     Running   0          100s
csi-snapshotter-588457fcdf-2wd6g                    1/1     Running   0          100s
csi-provisioner-869bdc4b79-mzrwf                    1/1     Running   0          101s
csi-provisioner-869bdc4b79-klgfm                    1/1     Running   0          101s
csi-resizer-6d8cf5f99f-fd2ck                        1/1     Running   0          101s
csi-provisioner-869bdc4b79-j46rx                    1/1     Running   0          101s
csi-snapshotter-588457fcdf-bvjdt                    1/1     Running   0          100s
csi-resizer-6d8cf5f99f-68cw7                        1/1     Running   0          101s
csi-attacher-7bf4b7f996-df8v6                       1/1     Running   0          101s
csi-attacher-7bf4b7f996-g9cwc                       1/1     Running   0          101s
csi-attacher-7bf4b7f996-8l9sw                       1/1     Running   0          101s
csi-resizer-6d8cf5f99f-smdjw                        1/1     Running   0          101s
instance-manager-b34d5db1fe1e2d52bcfb308be3166cfc   1/1     Running   0          114s
engine-image-ei-df38d2e5-cv6nc                      1/1     Running   0          114s
----

. Um den Zugriff auf die Benutzeroberfläche zu ermöglichen, müssen Sie einen Ingress-Controller einrichten. Die Authentifizierung zur Benutzeroberfläche ist standardmäßig nicht aktiviert. Für Informationen zur Erstellung eines NGINX Ingress-Controllers mit grundlegender Authentifizierung, beziehen Sie sich auf xref:longhorn-system/system-access/create-ingress.adoc[den Abschnitt zur Erstellung von Ingress].
. Greifen Sie auf die Benutzeroberfläche zu, indem Sie xref:longhorn-system/system-access/system-access.adoc[die Schritte zum Systemzugriff] verwenden.

=== Konfiguration

Das {longhorn-product-name} Helm-Chart bietet umfangreiche Konfigurationsoptionen gemäß Ihren spezifischen Anforderungen. Sie können diese Optionen konfigurieren, indem Sie eine `values.yaml` Datei bereitstellen oder `--set` Flags während `helm install` oder `helm upgrade` verwenden.

Häufig konfigurierbare Aspekte sind:

* **Speicherklasse**: Einstellungen der Standard-Speicherklasse.
* **Benutzeroberflächeneinstellungen**: Ingress-Konfiguration, Servicetyp und Authentifizierungsoptionen für die {longhorn-product-name} Benutzeroberfläche.
* **Manager- und Engine-Einstellungen**: Ressourcengrenzen, Replikazahlen und andere betriebliche Parameter für die {longhorn-product-name} Kernelkomponenten.
* **Knoten- und Datenträgerverwaltung**: Automatische Datenträgerbereitstellung, Knotenauswähler und Toleranzen.
* **CSI Driver**: Konfiguration, die speziell für die Komponenten des Container Storage Interface bestimmt ist.
* **Netzwerk**: Servicetypen und Netzwerkrichtlinien.

Für eine umfassende Liste aller verfügbaren Parameter und deren Beschreibungen, siehe die offizielle xref:installation-setup/installation/helm-values.adoc[{longhorn-product-name} Helm-Chart-Dokumentation] und die `values.yaml` Datei im Repository des Charts.
