= Installation
:revdate: 2026-01-12
:page-revdate: {revdate}
:description: Installieren Sie SUSE® Storage auf Kubernetes
:doctype: book
:current-version: {page-component-version}

NOTE: Dieser schnelle Installationsleitfaden verwendet einige Konfigurationen, die nicht für den Produktionsgebrauch geeignet sind.
Bitte sehen Sie sich xref:installation-setup/best-practices.adoc[Best Practices] an, um {longhorn-product-name} für den Produktionsgebrauch zu konfigurieren.

{longhorn-product-name} kann auf einem Kubernetes-Cluster auf verschiedene Arten installiert werden:

* xref:installation-setup/installation/install-using-rancher.adoc[]
* xref:installation-setup/installation/install-using-helm.adoc[]
* xref:installation-setup/installation/install-using-fleet.adoc[]
* xref:installation-setup/installation/install-using-flux.adoc[]
* xref:installation-setup/installation/install-using-argocd.adoc[]

Um {longhorn-product-name} in einer Air-Gapped-Umgebung zu installieren, beziehen Sie sich auf xref:installation-setup/installation/airgapped-environment.adoc[Air-Gapped Installation].

Für Informationen zur Anpassung der Standardeinstellungen beziehen Sie sich auf xref:longhorn-system/customize-default-settings.adoc[Customizing Default Settings].

Für Informationen zum Bereitstellen von {longhorn-product-name} auf bestimmten Knoten und zur Ablehnung allgemeiner Arbeitslasten für diese Knoten beziehen Sie sich auf den Abschnitt über xref:nodes/taints-tolerations.adoc[Taints and Tolerations].
