= Installieren Sie {longhorn-product-name} mit dem Helm-Controller
:revdate: 2026-02-02
:page-revdate: {revdate}
:current-version: {page-component-version}

Sie können {longhorn-product-name} mit dem in RKE2 und K3s integrierten Helm-Controller installieren.

== Voraussetzungen

[NOTE]
====
Die Installation von {longhorn-product-name} erfordert authentifizierten Zugriff auf die SUSE Application Collection. Für weitere Details überprüfen Sie https://docs.apps.rancher.io/get-started/authentication[Authentifizierungsleitfaden].
====

* Kubernetes-Cluster: Stellen Sie sicher, dass jeder Knoten die xref:installation-setup/requirements.adoc[Installationsanforderungen] erfüllt. Der Cluster sollte RKE2 oder K3s ausführen.

____
Das xref:longhorn-system/system-access/longhorn-cli.adoc[Longhorn-Kommandozeilenwerkzeug] kann verwendet werden, um die {longhorn-product-name} Umgebung auf potenzielle Probleme zu überprüfen.
____

== Installation

[NOTE]
====
* Die anfänglichen Einstellungen können xref:longhorn-system/customize-default-settings.adoc#_using_helm[mit Helm-Optionen oder durch Bearbeiten der Implementierungskonfigurationsdatei angepasst werden].
* Für Kubernetes v1.25 oder früher, wenn Ihr Cluster weiterhin den Pod Security Policy Admission Controller aktiviert, setzen Sie den Helm-Wert `enablePSP` auf `true`, um die `longhorn-psp` PodSecurityPolicy-Ressource zu installieren, die es privilegierten Longhorn-Pods ermöglicht, zu starten.
====

. Erstellen Sie eine HelmChart YAML-Datei, die der folgenden ähnlich ist:
+
[subs="+attributes",yaml]
----
apiVersion: helm.cattle.io/v1
  kind: HelmChart
  metadata:
    annotations:
      helmcharts.cattle.io/managed-by: helm-controller
    finalizers:
    - wrangler.cattle.io/on-helm-chart-remove
    generation: 1
    name: longhorn-install
    namespace: default
  spec:
    version: v{patch-version}
    chart: longhorn
    repo: https://charts.longhorn.io
    failurePolicy: abort
    targetNamespace: longhorn-system
    createNamespace: true
----
+
[IMPORTANT]
====
* Stellen Sie sicher, dass `spec.failurePolicy` auf "abort" gesetzt ist.  Der einzige andere Wert ist der Standard: "reinstall", der {longhorn-product-name} deinstalliert.  Mit "abort" wird es regelmäßig erneut versucht, wodurch der Benutzer die Möglichkeit hat, das Problem zu beheben.
+
* Anstatt das Repository, die Version und den Chartnamen anzugeben, kann die YAML auch ein Bild der Charts selbst verwenden:
+
[,yaml]
----
spec:
  chartContent:  <tarball of chart directory | base64 -w 0>
----
+
Für vollständige Details siehe die Dokumentation des HelmChart-Controllers: https://documentation.suse.com/cloudnative/rke2/latest/en/add-ons/helm.html[{rke2-product-name} - Helm] oder https://documentation.suse.com/cloudnative/k3s/latest/en/helm.html[{k3s-product-name} - Helm].
====
+
. Wenden Sie die YAML an, um die HelmChart CR und einen Installationsjob zu erstellen.
+
[,shell]
----
$ kubectl apply -f helmchart_repo_install.yaml
helmchart.helm.cattle.io/longhorn-install created
----
+
[NOTE]
====
Das Löschen der HelmChart CR initiiert die Deinstallation von {longhorn-product-name}.
====
. Überprüfen Sie die erstellten Ressourcen.
+
[subs="+attributes",shell]
----
$ kubectl get jobs
NAME                            COMPLETIONS   DURATION   AGE
helm-install-longhorn-install   0/1           8s         8s
$ kubectl get pods
NAME                                  READY   STATUS      RESTARTS   AGE
helm-install-longhorn-install-lngm8   0/1     Completed   0          25s
$ kubectl get helmcharts
NAME               JOB                     CHART      TARGETNAMESPACE   VERSION   REPO                         HELMVERSION   BOOTSTRAP
longhorn-install   helm-install-longhorn   longhorn   longhorn-system   v{patch-version}    https://charts.longhorn.io
----
+
. Überprüfen Sie, ob die Implementierung erfolgreich war.
+
[,bash]
----
kubectl -n longhorn-system get pod
----
+
Beispiel für das Ergebnis:
+
[,bash]
----
NAME                                                READY   STATUS    RESTARTS      AGE
csi-attacher-85c7684cfd-67kqc                       1/1     Running   0             29m
csi-attacher-85c7684cfd-jbddj                       1/1     Running   0             29m
csi-attacher-85c7684cfd-t85bw                       1/1     Running   0             29m
csi-provisioner-68cdb8b96-46d9q                     1/1     Running   0             29m
csi-provisioner-68cdb8b96-dgf5f                     1/1     Running   0             29m
csi-provisioner-68cdb8b96-mh8q7                     1/1     Running   0             29m
csi-resizer-86dd765b9-d27cs                         1/1     Running   0             29m
csi-resizer-86dd765b9-scqxm                         1/1     Running   0             29m
csi-resizer-86dd765b9-zpcv7                         1/1     Running   0             29m
csi-snapshotter-65b46b8749-dtvh2                    1/1     Running   0             29m
csi-snapshotter-65b46b8749-g67fn                    1/1     Running   0             29m
csi-snapshotter-65b46b8749-nfgzm                    1/1     Running   0             29m
engine-image-ei-221c9c21-gd5d6                      1/1     Running   0             29m
engine-image-ei-221c9c21-v6clp                      1/1     Running   0             29m
engine-image-ei-221c9c21-zzdrt                      1/1     Running   0             29m
instance-manager-77d11dda6091967f9b30011c9876341b   1/1     Running   0             29m
instance-manager-870c250b69a4fe01382ed46156d33f47   1/1     Running   0             29m
instance-manager-a4099c5ce28b423c3cc2667906f4b0b4   1/1     Running   0             29m
longhorn-csi-plugin-jfbh5                           3/3     Running   0             29m
longhorn-csi-plugin-w768w                           3/3     Running   0             29m
longhorn-csi-plugin-xcghm                           3/3     Running   0             29m
longhorn-driver-deployer-586bc86bf9-bkwk6           1/1     Running   0             30m
longhorn-manager-c4xtv                              1/1     Running   1 (30m ago)   30m
longhorn-manager-kgqts                              1/1     Running   0             30m
longhorn-manager-n8xdr                              1/1     Running   0             30m
longhorn-ui-69667f9678-2lvxn                        1/1     Running   0             30m
longhorn-ui-69667f9678-2xmc9                        1/1     Running   0             30m
----
+
. xref:longhorn-system/system-access/create-ingress.adoc[Erstellen Sie einen NGINX Ingress-Controller mit grundlegender Authentifizierung], um auf die Benutzeroberfläche zuzugreifen. Die Authentifizierung zur Benutzeroberfläche ist standardmäßig nicht aktiviert.
+
. xref:longhorn-system/system-access/system-access.adoc[Zugriff auf die Benutzeroberfläche].
