= Installieren Sie SUSE® Storage mit Flux
:revdate: 2026-01-12
:page-revdate: {revdate}
:current-version: {page-component-version}

== Voraussetzungen

[NOTE]
====
Die {longhorn-product-name} Installation erfordert authentifizierten Zugriff auf die SUSE Application Collection. Für weitere Details, überprüfen Sie https://docs.apps.rancher.io/get-started/authentication[den Authentifizierungsleitfaden].
====

* Ihr Arbeitsplatz: Installieren Sie https://helm.sh/docs/[Helm] v3.0 oder höher.
* Kubernetes-Cluster:
 ** Stellen Sie sicher, dass jeder Knoten die xref:installation-setup/requirements.adoc[Installationsanforderungen] erfüllt.
 ** https://fluxcd.io/flux/installation/#install-the-flux-cli[Installieren Sie die Flux-Kommandozeilenschnittstelle und Controller].
 ** https://fluxcd.io/flux/installation/bootstrap/github/[Starten Sie Flux mit GitHub neu] unter Verwendung der Flux-Kommandozeilenschnittstelle.
Führen Sie die folgenden Befehle aus, um Ihr persönliches Zugriffstoken (PAT) von GitHub als Umgebungsvariable zu exportieren, die Flux-Controller in Ihrem Cluster bereitzustellen und die Controller zu konfigurieren, um den Clusterzustand aus dem angegebenen GitHub-Repository zu synchronisieren.
+
[,bash]
----
export GITHUB_TOKEN=<gh-token>
flux bootstrap github \
  --token-auth \
  --owner=<github_username> \
  --repository=<github_repo_name> \
  --branch=<branch_name> \
  --path=<folder_path_within_repo> \
  --personal
----

____
Das xref:longhorn-system/system-access/longhorn-cli.adoc[Longhorn-Kommandozeilenwerkzeug] kann verwendet werden, um die Longhorn-Umgebung auf potenzielle Probleme zu überprüfen.
____

== Installation

. Erstellen Sie eine benutzerdefinierte Ressource (CR) vom Typ HelmRepository, die auf die {longhorn-product-name} Helm-Chart-URL verweist.
+
[,bash]
----
 kubectl create ns longhorn-system
 flux create source helm longhorn-repo \
   --url=https://charts.longhorn.io \
   --namespace=longhorn-system \
   --export > helmrepo.yaml
 kubectl apply -f helmrepo.yaml
----

. Erstellen Sie eine HelmRelease-CR, die auf das HelmRepository verweist und die Version des zu installierenden Helm-Charts angibt.
+
[subs="+attributes",bash]
----
 flux create helmrelease longhorn-release \
   --chart=longhorn \
   --source=HelmRepository/longhorn-repo \
   --chart-version=v{patch-version} \
   --namespace=longhorn-system \
   --export > helmrelease.yaml
 kubectl apply -f helmrelease.yaml
----

. Überprüfen Sie, ob die HelmRelease-CR erfolgreich erstellt und synchronisiert wurde.
+
[,bash]
----
 flux get helmrelease longhorn-release -n longhorn-system
----

. Überprüfen Sie, ob {longhorn-product-name} erfolgreich installiert wurde.
+
[,bash]
----
 kubectl -n longhorn-system get pod
----
+
Beispiel für eine erfolgreiche Installation:
+
[,bash]
----
 NAME                                                READY   STATUS    RESTARTS   AGE
 longhorn-ui-b7c844b49-w25g5                         1/1     Running   0          2m41s
 longhorn-manager-pzgsp                              1/1     Running   0          2m41s
 longhorn-driver-deployer-6bd59c9f76-lqczw           1/1     Running   0          2m41s
 longhorn-csi-plugin-mbwqz                           2/2     Running   0          100s
 csi-snapshotter-588457fcdf-22bqp                    1/1     Running   0          100s
 csi-snapshotter-588457fcdf-2wd6g                    1/1     Running   0          100s
 csi-provisioner-869bdc4b79-mzrwf                    1/1     Running   0          101s
 csi-provisioner-869bdc4b79-klgfm                    1/1     Running   0          101s
 csi-resizer-6d8cf5f99f-fd2ck                        1/1     Running   0          101s
 csi-provisioner-869bdc4b79-j46rx                    1/1     Running   0          101s
 csi-snapshotter-588457fcdf-bvjdt                    1/1     Running   0          100s
 csi-resizer-6d8cf5f99f-68cw7                        1/1     Running   0          101s
 csi-attacher-7bf4b7f996-df8v6                       1/1     Running   0          101s
 csi-attacher-7bf4b7f996-g9cwc                       1/1     Running   0          101s
 csi-attacher-7bf4b7f996-8l9sw                       1/1     Running   0          101s
 csi-resizer-6d8cf5f99f-smdjw                        1/1     Running   0          101s
 instance-manager-b34d5db1fe1e2d52bcfb308be3166cfc   1/1     Running   0          114s
 engine-image-ei-df38d2e5-cv6nc                      1/1     Running   0          114s
----

. xref:longhorn-system/system-access/create-ingress.adoc[Erstellen Sie einen NGINX Ingress-Controller mit grundlegender Authentifizierung], um auf die Benutzeroberfläche zuzugreifen. Die Authentifizierung zur Benutzeroberfläche ist standardmäßig nicht aktiviert.
. xref:longhorn-system/system-access/system-access.adoc[Zugriff auf die Benutzeroberfläche].

== Kontinuierliche Operationen über GitOps

Sie können exportierte Manifeste in Ihr GitOps-Repository übertragen und pushen.

[subs="+attributes",bash]
----
 git add helmrepo.yaml helmrelease.yaml
 git commit -m "Add HelmRepository and HelmRelease for {longhorn-product-name} installation"
 git push origin <branch_name>
----

Anschließend können Sie die HelmRelease- und HelmRepository-CRs ändern, indem Sie die YAML-Manifeste in Ihrem GitOps-Repository bearbeiten. Flux erkennt die Änderungen automatisch und wendet sie an, ohne direkten Zugriff auf Ihren Kubernetes-Cluster zu benötigen.
