= Uninstallation

== Prerequisite

To prevent {longhorn-product-name} from being accidentally uninstalled (which leads to data lost), there is a new setting, xref:longhorn-system/settings.adoc#_deleting_confirmation_flag[deleting-confirmation-flag]. If this flag is `false`, the uninstallation job will fail. Set this flag to `true` to allow uninstallation. You can set this flag using setting page in the {longhorn-product-name} UI or `kubectl -n longhorn-system patch -p '{"value": "true"}' --type=merge lhs deleting-confirmation-flag`.

To prevent damage to the Kubernetes cluster, it is recommended to delete all Kubernetes workloads using {longhorn-product-name} volumes (PersistentVolume, PersistentVolumeClaim, StorageClass, Deployment, StatefulSet, DaemonSet, etc).

== Completely Remove {longhorn-product-name}

To completely remove the {longhorn-product-name} deployment from your Kubernetes cluster, use the `helm uninstall` command.

[,shell]
----
helm uninstall longhorn --namespace longhorn-system
----
