= Solução de problemas
:revdate: 2025-06-27
:page-revdate: {revdate}
:aliases: ["/spdk/troubleshooting.md"]
:current-version: {page-component-version}

== Instalação

=== Erro "O pacote 'linux-modules-extra-x.x.x-x-generic' não possui candidato à instalação" durante a instalação em máquinas Debian

Para máquinas Debian, se você encontrar erros semelhantes aos abaixo ao instalar módulos extras do kernel Linux, você precisa encontrar uma versão disponível em sites de repositórios de pacotes como https://pkgs.org/search/?q=linux-modules-extra[este] em vez de confiar diretamente em `uname -r`:

[subs="+attributes",log]
----
apt install -y linux-modules-extra-`uname -r`
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package linux-modules-extra-5.15.0-67-generic is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'linux-modules-extra-5.15.0-67-generic' has no installation candidate
----

Por exemplo, para Ubuntu 22.04, uma versão válida é `linux-modules-extra-5.15.0-76-generic`:

[subs="+attributes",shell]
----
apt update -y
apt install -y linux-modules-extra-5.15.0-76-generic
----

== Disco

=== Erro "Argumento inválido" no status do disco após adicionar um disco do tipo bloco

Após adicionar um disco do tipo bloco, o status do disco exibe mensagens de erro:

----
Disk disk-1(/dev/nvme1n1) on node dereksu-ubuntu-pool1-bf77ed93-2d2p9 is not ready:
failed to generate disk config: error: rpc error: code = Internal desc = rpc error: code = Internal
desc = failed to add block device: failed to create AIO bdev: error sending message, id 10441,
method bdev_aio_create, params {disk-1 /host/dev/nvme1n1 4096}: {"code": -22,"message": "Invalid argument"}
----

Em seguida, inspecione a mensagem de log do pod do gerenciador de instâncias no mesmo nó. Se o log revelar o seguinte:

----
[2023-06-29 08:51:53.762597] bdev_aio.c: 762:create_aio_bdev: *WARNING*: Specified block size 4096 does not match auto-detected block size 512
[2023-06-29 08:51:53.762640] bdev_aio.c: 788:create_aio_bdev: *ERROR*: Disk size 100000000000 is not a multiple of block size 4096
----

Essas mensagens indicam que o tamanho do seu disco não é um múltiplo do tamanho do bloco 4096 e não é suportado pelo sistema Longhorn.

Para resolver esse problema, você pode seguir os passos

. Remova o disco do tipo bloco recém-adicionado do nó.
. Particione o disco do tipo bloco usando a ferramenta `fdisk` e certifique-se de que o tamanho da partição seja um múltiplo do tamanho do bloco 4096.
. Adicione o disco particionado ao nó Longhorn.
