= Mettre à niveau Kubernetes sur Azure Kubernetes Service (AKS)
:revdate: 2026-01-12
:page-revdate: {revdate}
:current-version: {page-component-version}

AKS fournit `az aks upgrade` pour la mise à niveau des nœuds sur place par réimagerie des nœuds, mais cela entraînera la perte des disques d'origine {longhorn-product-name}, ce qui signifie qu'il n'y aura plus de disques permettant la reconstruction des répliques dans les nœuds mis à niveau.

Nous suggérons d'utiliser le remplacement de pool de nœuds pour mettre à niveau les nœuds agents, mais d'utiliser `az aks upgrade` pour les nœuds du plan de contrôle afin d'assurer la sécurité des données.

. Dans {longhorn-product-name}, définissez `replica-replenishment-wait-interval` sur `0`.
. Mettre à niveau le plan de contrôle AKS.
+
----
 AKS_RESOURCE_GROUP=<aks-resource-group>
 AKS_CLUSTER_NAME=<aks-cluster-name>
 AKS_K8S_VERSION_UPGRADE=<aks-k8s-version>

 az aks upgrade \
     --resource-group ${AKS_RESOURCE_GROUP} \
     --name ${AKS_CLUSTER_NAME} \
     --kubernetes-version ${AKS_K8S_VERSION_UPGRADE} \
     --control-plane-only
----

. Ajouter un nouveau pool de nœuds.
+
----
 AKS_NODEPOOL_NAME_NEW=<new-nodepool-name>
 AKS_DISK_SIZE=<disk-size-in-gb>
 AKS_NODE_NUM=<number-of-nodes>

 az aks nodepool add \
   --resource-group ${AKS_RESOURCE_GROUP} \
   --cluster-name ${AKS_CLUSTER_NAME} \
   --name ${AKS_NODEPOOL_NAME_NEW} \
   --node-count ${AKS_NODE_NUM} \
   --node-osdisk-size ${AKS_DISK_SIZE} \
   --kubernetes-version ${AKS_K8S_VERSION_UPGRADE} \
   --mode System
----

. Utiliser l'interface {longhorn-product-name} pour désactiver la planification des disques et demander l'éviction des nœuds dans l'ancien pool de nœuds.
. Cordonner et vider les nœuds Kubernetes dans l'ancien pool de nœuds.
+
----
 AKS_NODEPOOL_NAME_OLD=<old-nodepool-name>

 for n in `kubectl get nodes | grep ${AKS_NODEPOOL_NAME_OLD}- | awk '{print $1}'`; do
   kubectl cordon $n && \
   kubectl drain $n --ignore-daemonsets --delete-emptydir-data
 done
----

. Supprimer l'ancien pool de nœuds.
+
----
 az aks nodepool delete \
   --cluster-name ${AKS_CLUSTER_NAME} \
   --name ${AKS_NODEPOOL_NAME_OLD} \
   --resource-group ${AKS_RESOURCE_GROUP}
----
