= Synchronize Backup Volumes Manually
:weight: 6
:current-version: {page-origin-branch}

After creating a backup, Longhorn creates a backup volume that corresponds to the original volume (on which the backup is based). A backup volume is an object in the backupstore that contains multiple backups of the same volume.

Earlier Longhorn versions poll and update all backup volumes at a xref:references/settings.adoc#backupstore-poll-interval[fixed interval]. Longhorn v1.6.2 provides a way for you to manually synchronize backup volumes with the backup target.

IMPORTANT: You must set up a xref:snapshots-and-backups/backup-and-restore/set-backup-target.adoc[backup target] and verify that a backup volume was created before attempting to synchronize. Longhorn returns an error when no backup target and backup volume exist.

* Synchronize all backup volumes:
 .. On the Longhorn UI, go to *Backup*.
 .. Click *Sync All Backup Volumes*.
* Synchronize a single backup volume:
 .. On the Longhorn UI, go to *Backup*.
 .. Select a backup volume.
 .. Click *Sync Backup Volume*.

To check if synchronization was successful, click the name of the backup volume on the *Backup* screen.
