= Sauvegardes du système SUSE® Storage
:revdate: 2025-06-27
:page-revdate: {revdate}
:current-version: {page-component-version}

____
Les versions antérieures vous permettaient de restaurer le système SUSE® Storage en utilisant des outils tiers.
____

* xref:snapshots-backups/system-backups/restore-to-cluster-using-rancher-snapshot.adoc[Restaurer vers un cluster contenant des données en utilisant un instantané Rancher]
* xref:snapshots-backups/system-backups/restore-to-new-cluster-using-velero.adoc[Restaurer vers un nouveau cluster en utilisant Velero]

____
Les versions actuelles de SUSE® Storage incluent des sauvegardes et restaurations système prêtes à l'emploi.

* Les ressources personnalisées de SUSE® Storage seront sauvegardées et regroupées dans un seul fichier de sauvegarde système, puis enregistrées sur la cible de sauvegarde distante.
* Plus tard, vous pouvez choisir une sauvegarde système à restaurer sur un nouveau cluster ou sur un cluster existant.
____

* xref:snapshots-backups/system-backups/create-system-backup.adoc[Sauvegarder le système Longhorn]
* xref:snapshots-backups/system-backups/restore-system.adoc[Restaurer le système Longhorn]
