= Longhorn Engineを自動的にアップグレードする
:revdate: 2026-01-08
:page-revdate: {revdate}
:current-version: {page-component-version}

{longhorn-product-name}は、Longhorn Managerをアップグレードした後に、Longhornボリュームを新しいデフォルトエンジンバージョンに自動的にアップグレードすることを可能にします。この機能は、{longhorn-product-name}をアップグレードする際に必要な手動作業の量を減らします。この機能に関連するいくつかの概念は以下の通りです：

== 1.ノードごとの同時自動エンジンアップグレード制限設定

これは、Longhorn Managerをアップグレードした後に、{longhorn-product-name}がボリュームのエンジンを新しいデフォルトエンジンイメージに自動的にアップグレードする方法を制御する設定です。この設定の値は、同時にデフォルトエンジンイメージにアップグレードできるノードごとの最大エンジン数を指定します。

値が0の場合、{longhorn-product-name}はボリュームのエンジンをデフォルトバージョンに自動的にアップグレードしません。この値が大きいほど、Longhorn Engineアップグレードプロセスが早く完了します。

ただし、この設定に大きな値を与えると、Longhorn Engineアップグレードプロセス中にノードのCPUとメモリをより多く消費します。エラーの余地を残すため、値を3に設定することを推奨しますが、失敗したアップグレードによってシステムに過度な負荷がかからないようにしてください。

== 2.異なるボリューム条件における{longhorn-product-name}の動作。

以下のケースでは、`concurrent automatic engine upgrade per node limit`の設定が0より大きいと仮定します。

. 接続されたボリューム
+
ボリュームが接続状態で健康な場合、{longhorn-product-name}はボリュームのLonghorn Engineを新しいデフォルトエンジンイメージに自動的にライブアップグレードします。

. 切り離されたボリューム
+
{longhorn-product-name}は、切り離されたボリュームに対してオフラインアップグレードを自動的に実行します。

. 災害復旧ボリューム
+
{longhorn-product-name}は、災害復旧ボリュームの完全な復元を引き起こすため、xref:data-integrity-recovery/disaster-recovery-volumes.adoc[災害復旧ボリューム]を新しいデフォルトエンジンイメージに自動的にアップグレードしません。完全な復元は、システム内の他の実行中のロングホーンボリュームのパフォーマンスに影響を与える可能性があります。したがって、{longhorn-product-name} は、災害復旧ボリュームのエンジンを手動でアップグレードするのに適した時期を決定することをあなたに委ねます（例えば、システムがアイドル状態のときやメンテナンス時間中など）。
+
ただし、災害復旧ボリュームをアクティブにすると、そのボリュームはアクティブになった後に切り離されます。
この時、{longhorn-product-name}は、切り離されたボリュームの場合と同様に、該当ボリュームに対してオフラインアップグレードを自動的に実行します。

== 3.アップグレードが失敗した場合はどうなりますか？

ボリュームがエンジンのアップグレードに失敗した場合、ボリュームの仕様にあるエンジンイメージは、ボリュームのステータスにあるエンジンイメージとは異なるままとなります。{longhorn-product-name} は成功するまでアップグレードを継続的に再試行します。

ノードごとにアップグレードに失敗するボリュームが多すぎる場合（つまり、`concurrent automatic engine upgrade per node limit` の設定を超える場合）、{longhorn-product-name} はそのノードでのボリュームのアップグレードを停止します。

== 4.自動アップグレード中の古いインスタンスマネージャーポッドのライブネスとクリーンアップ

ライブアップグレード中の古いインスタンスマネージャーポッドのライブネスとクリーンアップについては、xref:upgrades/longhorn-components/instance-manager-pods-during-upgrade.adoc[アップグレード中のインスタンスマネージャーポッド] ドキュメントを参照してください。
