= Longhorn Engineを手動でアップグレードする
:revdate: 2025-06-27
:page-revdate: {revdate}
:current-version: {page-component-version}

Longhorn UIを使用してLonghorn Engineを手動でアップグレードできます。

== 前提条件

Longhorn Engineのイメージをアップグレードする前に、必ずバックアップを作成してください。

Longhorn Engineをアップグレードする前に、Longhorn Managerをアップグレードしてください。

== オフラインアップグレード

ライブアップグレードが利用できない場合や、ボリュームが劣化状態にある場合は、次の手順に従ってください：

. xref:data-integrity-recovery/disaster-recovery-volumes.adoc[関連するワークロードのデタッチ手順]に従ってください。
. バッチ選択を使用してすべてのボリュームを選択します。バッチ操作ボタン*エンジンをアップグレード*をクリックし、リストにあるエンジンイメージを選択します。これは、このリリースのマネージャーに付属するデフォルトのエンジンです。
. すべてのワークロードを再開します。Kubernetesワークロードの一部でないボリュームは、Longhorn UIからアタッチする必要があります。

== ライブアップグレード

{longhorn-product-name} v1.8.xからv{current-version}へのライブエンジンアップグレードをサポートしています。

`iSCSI`フロントエンドはライブアップグレードをサポートしていません。

ライブアップグレードは、正常なボリュームでのみ行うべきです。

. アップグレードしたいボリュームを選択してください。
. ドロップダウンで`Upgrade Engine`をクリックします。
. アップグレードしたいエンジンイメージを選択してください。
 .. 通常、リストには唯一のエンジンイメージしか表示されません。UIは現在のイメージをリストから除外するためです。
. [OK] をクリックします。

ライブアップグレード中、ユーザーは一時的にレプリカの数が2倍に見えるでしょう。アップグレードが完了した後、ユーザーは以前と同じ数のレプリカが表示され、ボリュームの`Engine Image`フィールドが更新される必要があります。

ライブアップグレード後、RancherやKubernetesはエンジンの古いイメージを表示し続け、新しいバージョンのレプリカを表示することに注意してください。これは想定内です。ボリューム詳細ページにボリュームイメージとして新しいバージョンのイメージが表示されていれば、アップグレードは成功です。

== 古いイメージをクリーンアップしてください。

すべてのイメージのアップグレードが完了したら、Longhorn UIから`Settings/Engine Image`を選択してください。今、デフォルトでないイメージを削除できるはずです。
