= 使用 Helm 安装 {longhorn-product-name}
:revdate: 2026-01-12
:page-revdate: {revdate}
:current-version: {page-component-version}

== 先决条件

[NOTE]
====
{longhorn-product-name}安装 需要对 SUSE 应用程序集合的认证访问。有关更多详细信息，请查看 https://docs.apps.rancher.io/get-started/authentication[认证指南]。
====

=== 工具

* 需要 https://helm.sh/docs/[Helm] v3.0 或更高版本。
* 可以使用 xref:longhorn-system/system-access/longhorn-cli.adoc[Longhorn 命令行工具] 检查 {longhorn-product-name} 环境中的潜在问题。

=== Kubernetes 环境

* 需要一个 Kubernetes 集群，每个节点都满足 xref:installation-setup/requirements.adoc[安装要求]。

=== 身份验证

* 要使用 SUSE 应用程序集合 OCI 图表储存库对 Helm 进行认证，请参考 https://docs.apps.rancher.io/get-started/authentication/#helm[Helm 认证文档]。
* 要允许 Kubernetes 从注册表中拉取镜像，请按照 https://docs.apps.rancher.io/get-started/authentication/#kubernetes[Kubernetes 认证文档] 创建一个密钥并设置 `global.imagePullSecrets` 图表值。

== 安装

. 使用默认配置安装 {longhorn-product-name}，运行：
+
[subs="+attributes",shell]
----
helm install longhorn oci://dp.apps.rancher.io/charts/suse-storage \
  --namespace longhorn-system \
  --create-namespace \
  --version <version> \ # Replace with the version you would like to install
  --set global.imagePullSecrets=<PULL_IMAGE_SECRET>
----

. 要确认部署成功，请运行：
+
[,bash]
----
kubectl -n longhorn-system get pod
----
+
结果应如下所示：
+
[,bash]
----
NAME                                                READY   STATUS    RESTARTS   AGE
longhorn-ui-b7c844b49-w25g5                         1/1     Running   0          2m41s
longhorn-manager-pzgsp                              1/1     Running   0          2m41s
longhorn-driver-deployer-6bd59c9f76-lqczw           1/1     Running   0          2m41s
longhorn-csi-plugin-mbwqz                           2/2     Running   0          100s
csi-snapshotter-588457fcdf-22bqp                    1/1     Running   0          100s
csi-snapshotter-588457fcdf-2wd6g                    1/1     Running   0          100s
csi-provisioner-869bdc4b79-mzrwf                    1/1     Running   0          101s
csi-provisioner-869bdc4b79-klgfm                    1/1     Running   0          101s
csi-resizer-6d8cf5f99f-fd2ck                        1/1     Running   0          101s
csi-provisioner-869bdc4b79-j46rx                    1/1     Running   0          101s
csi-snapshotter-588457fcdf-bvjdt                    1/1     Running   0          100s
csi-resizer-6d8cf5f99f-68cw7                        1/1     Running   0          101s
csi-attacher-7bf4b7f996-df8v6                       1/1     Running   0          101s
csi-attacher-7bf4b7f996-g9cwc                       1/1     Running   0          101s
csi-attacher-7bf4b7f996-8l9sw                       1/1     Running   0          101s
csi-resizer-6d8cf5f99f-smdjw                        1/1     Running   0          101s
instance-manager-b34d5db1fe1e2d52bcfb308be3166cfc   1/1     Running   0          114s
engine-image-ei-df38d2e5-cv6nc                      1/1     Running   0          114s
----

. 要启用对 UI 的访问，您需要设置一个 Ingress 控制器。默认情况下，UI 的认证未启用。有关使用基本认证创建 NGINX Ingress 控制器的信息，请参考 xref:longhorn-system/system-access/create-ingress.adoc[创建 Ingress 部分]。
. 使用 xref:longhorn-system/system-access/system-access.adoc[系统访问步骤] 访问 UI。

=== 配置

{longhorn-product-name} Helm 图表根据您的具体需求提供广泛的配置选项。您可以通过提供 `values.yaml` 文件或在 `helm install` 或 `helm upgrade` 期间使用 `--set` 标志来配置这些选项。

常见的可配置方面包括：

* **存储类**：默认存储类设置。
* **UI 设置**：{longhorn-product-name} UI 的入口配置、服务类型和认证选项。
* **管理器和引擎设置**：{longhorn-product-name} 内核组件的资源限制、副本数量和其他操作参数。
* **节点和磁盘管理**：自动磁盘配置、节点选择器和容忍度。
* **CSI 驱动程序**：特定于容器存储接口组件的配置。
* **网络**：服务类型和网络策略。

有关所有可用参数及其描述的完整列表，请参阅官方 xref:installation-setup/installation/helm-values.adoc[{longhorn-product-name} Helm Chart 文档] 和图表储存库中的 `values.yaml` 文件。
