= Installez {longhorn-product-name} en utilisant Argo CD
:revdate: 2026-01-12
:page-revdate: {revdate}
:current-version: {page-component-version}

== Conditions préalables

[NOTE]
====
{longhorn-product-name}L'installation de  nécessite un accès authentifié à la SUSE Application Collection. Pour plus de détails, consultez https://docs.apps.rancher.io/get-started/authentication[le guide d'authentification].
====

* Votre poste de travail{nbsp}: Installez le https://argo-cd.readthedocs.io/en/stable/cli_installation/[Argo CD CLI].
* Cluster Kubernetes{nbsp}:
 ** Assurez-vous que chaque nœud remplit les xref:installation-setup/requirements.adoc[exigences d'installation].
 ** Installez https://argo-cd.readthedocs.io/en/stable/[Argo CD].
+
[,bash]
----
kubectl create namespace argocd
kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/core-install.yaml
----
+
Laissez un certain temps pour le déploiement des composants Argo CD dans l'espace de noms `argocd`.

____
L'xref:longhorn-system/system-access/longhorn-cli.adoc[outil de ligne de commande Longhorn] peut être utilisé pour vérifier l'environnement {longhorn-product-name} pour d'éventuels problèmes.
____

== Installation

. Connectez-vous à Argo CD.
+
[,bash]
----
 argocd login --core
----

. Définissez l'espace de noms actuel sur `argocd`.
+
[,bash]
----
 kubectl config set-context --current --namespace=argocd
----

. Créez la ressource personnalisée de {longhorn-product-name}l'Application.
+
[subs="+attributes",bash]
----
cat > longhorn-application.yaml <<EOF
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: default
  sources:
    - chart: longhorn
      repoURL: https://charts.longhorn.io/
      targetRevision: v{{<current-version>}} # Replace with the Longhorn version you'd like to install or upgrade to
      helm:
        values: |
          preUpgradeChecker:
            jobEnabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  # add ignoreDifferences to prevent preserveUnknownFields field from make causing the application to be out of sync
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: engineimages.longhorn.io
      jsonPointers: ["/spec/preserveUnknownFields"]
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: engines.longhorn.io
      jsonPointers: ["/spec/preserveUnknownFields"]
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: instancemanagers.longhorn.io
      jsonPointers: ["/spec/preserveUnknownFields"]
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: nodes.longhorn.io
      jsonPointers: ["/spec/preserveUnknownFields"]
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: replicas.longhorn.io
      jsonPointers: ["/spec/preserveUnknownFields"]
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: settings.longhorn.io
      jsonPointers: ["/spec/preserveUnknownFields"]
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: volumes.longhorn.io
      jsonPointers: ["/spec/preserveUnknownFields"]
EOF
kubectl apply -f longhorn-application.yaml
----

. Déployez {longhorn-product-name} avec les paramètres configurés.
+
[,bash]
----
 argocd app sync longhorn
----

. Vérifiez que {longhorn-product-name} a été installé avec succès.
+
[,bash]
----
 kubectl -n longhorn-system get pod
----
+
Exemple d'une installation réussie{nbsp}:
+
[,bash]
----
 NAME                                                READY   STATUS    RESTARTS   AGE
 longhorn-ui-b7c844b49-w25g5                         1/1     Running   0          2m41s
 longhorn-manager-pzgsp                              1/1     Running   0          2m41s
 longhorn-driver-deployer-6bd59c9f76-lqczw           1/1     Running   0          2m41s
 longhorn-csi-plugin-mbwqz                           2/2     Running   0          100s
 csi-snapshotter-588457fcdf-22bqp                    1/1     Running   0          100s
 csi-snapshotter-588457fcdf-2wd6g                    1/1     Running   0          100s
 csi-provisioner-869bdc4b79-mzrwf                    1/1     Running   0          101s
 csi-provisioner-869bdc4b79-klgfm                    1/1     Running   0          101s
 csi-resizer-6d8cf5f99f-fd2ck                        1/1     Running   0          101s
 csi-provisioner-869bdc4b79-j46rx                    1/1     Running   0          101s
 csi-snapshotter-588457fcdf-bvjdt                    1/1     Running   0          100s
 csi-resizer-6d8cf5f99f-68cw7                        1/1     Running   0          101s
 csi-attacher-7bf4b7f996-df8v6                       1/1     Running   0          101s
 csi-attacher-7bf4b7f996-g9cwc                       1/1     Running   0          101s
 csi-attacher-7bf4b7f996-8l9sw                       1/1     Running   0          101s
 csi-resizer-6d8cf5f99f-smdjw                        1/1     Running   0          101s
 instance-manager-b34d5db1fe1e2d52bcfb308be3166cfc   1/1     Running   0          114s
 engine-image-ei-df38d2e5-cv6nc                      1/1     Running   0          114s
----

. xref:longhorn-system/system-access/create-ingress.adoc[Créez un contrôleur d'Ingress NGINX avec une authentification de base] pour accéder à l'interface utilisateur. L'authentification à l'interface utilisateur n'est pas activée par défaut.
. xref:longhorn-system/system-access/system-access.adoc[Accédez à l'interface utilisateur].
