= Installation
:revdate: 2026-01-12
:page-revdate: {revdate}
:description: Installez SUSE® Storage sur Kubernetes
:doctype: book
:current-version: {page-component-version}

NOTE: Ce guide d'installation rapide utilise certaines configurations qui ne sont pas destinées à un usage en production.
Veuillez consulter xref:installation-setup/best-practices.adoc[Meilleures Pratiques] pour savoir comment configurer {longhorn-product-name} pour un usage en production.

{longhorn-product-name} peut être installé sur un cluster Kubernetes de plusieurs manières{nbsp}:

* xref:installation-setup/installation/install-using-rancher.adoc[]
* xref:installation-setup/installation/install-using-helm.adoc[]
* xref:installation-setup/installation/install-using-fleet.adoc[]
* xref:installation-setup/installation/install-using-flux.adoc[]
* xref:installation-setup/installation/install-using-argocd.adoc[]

Pour installer {longhorn-product-name} dans un environnement isolé physiquement, reportez-vous à xref:installation-setup/installation/airgapped-environment.adoc[Installation isolée physiquement].

Pour des informations sur la personnalisation des paramètres par défaut, reportez-vous à xref:longhorn-system/customize-default-settings.adoc[Personnalisation des Paramètres par Défaut].

Pour des informations sur le déploiement de {longhorn-product-name} sur des nœuds spécifiques et le rejet des charges de travail générales pour ces nœuds, reportez-vous à la section xref:nodes/taints-tolerations.adoc[Taints and Tolerations].
