= Rancherスナップショットを使用して、SUSE® Storageをクラスターに復元します。
:revdate: 2025-06-27
:page-revdate: {revdate}
:current-version: {page-component-version}

== 前提:

* 復元前、クラスター内には*ほとんどのデータと基盤となるディスクがまだ存在しており*、それらはそのまま再利用できます。
* すべてのボリュームデータを保持するバックアップストアがあります。
* 設定xref:longhorn-system/settings.adoc#_disable_revision_counter[`Disable Revision Counter`]はfalseです。（デフォルトではfalseです。）そうでない場合、ユーザーはボリュームレプリカ間のデータが一貫しているか手動で確認する必要があるか、バックアップからボリュームを直接復元する必要があります。

== 期待されること：

* すべての設定とノードおよびディスクの設定が復元されます。
* 有効なデータがまだ存在する限り、バックアップを使用せずにボリュームを回復できます。言い換えれば、バックアップの復元を避けるように努めます。これにより、復旧時間目標（RTO）を短縮し、帯域幅を節約できる可能性があります。
* 復元後、関連するボリュームが有効なレプリカをまだ含んでいる限り、無効または同期が取れていないレプリカを検出します。

== Rancher復元の動作と要件

* すべてのノードでKubernetesコンポーネントを再起動する必要があります。そうでないと、Longhornで多数のリソース更新の競合が発生します。

== 復元後のアクション

* すべてのノードのKubernetesコンポーネントを再起動します。詳細については、上記のリンクを参照してください。
* すべてのLonghorn Managerポッドを停止すると、Kubernetesが自動的に再起動します。Longhorn Managerポッドの競合が消えるのを待ちます。
* すべてのボリュームが再接続される可能性があります。単一のポッドがロングホーンボリュームを使用する場合、ユーザーはシャットダウンしてから再作成する必要があります。デプロイメントまたはステートフルセットの場合、ロングホーンは関連するポッドを自動的に終了させてから再起動します。
* スナップショット後、クラスターの復元前に次のことが発生した場合：
 ** ボリュームが変更されていない場合：ユーザーは何もする必要はありません。
 ** データが更新された場合：通常、ユーザーは何もする必要はありません。Longhornが最新のデータを含まないレプリカを自動的に失敗させます。
 ** 新しいボリュームが作成された場合：このボリュームは復元後に消えます。ユーザーは新しいボリュームを再作成し、消えたボリュームのレプリカに基づいてxref:data-integrity-recovery/data-recovery/retrieve-volume-data-from-replica.adoc[a single replica volume]を起動し、その後データを新しいボリュームに転送する必要があります。
 ** ボリュームが削除された場合：ボリュームが削除されるとデータがクリーンアップされるため、復元されたボリュームにはデータが含まれていません。ユーザーは再度削除する必要があるかもしれません。
 ** DRボリュームの場合：ユーザーは何もする必要はありません。Longhornは完全な復元を再実行します。
 ** ボリュームに対していくつかの操作が適用されます：
  *** ［Backup: ボリュームのバックアップ情報は自動的に再同期されるべきです。
  *** スナップショット:ボリュームが接続されると、ボリュームのスナップショット情報は再同期されるべきです。
  *** レプリカの再構築とレプリカの削除：
   **** 新しいレプリカが再構築される場合、それらのレプリカは復元後にLonghornシステムから消えます。ユーザーはレプリカデータを手動でクリーンアップする必要があるか、これらのレプリカのデータディレクトリを使用して単一のレプリカボリュームをエクスポートし、必要に応じてデータ回復を行います。
   **** 失敗した/削除されたレプリカがあり、少なくとも1つのレプリカが正常であれば、失敗した/削除されたレプリカは復元後に戻ります。その後、Longhornはこれらの復元されたレプリカにデータが含まれていないことを検出し、正常なレプリカからこれらのレプリカに最新のデータをコピーします。
   **** すべてのレプリカがスナップショット後に新しいレプリカに置き換えられた場合、ボリュームは復元後に無効なレプリカのみを含むことになります。その後、ユーザーはデータ回復のためにxref:data-integrity-recovery/data-recovery/retrieve-volume-data-from-replica.adoc[a single replica volume]をエクスポートする必要があります。
  *** エンジンイメージのアップグレード：ユーザーはアップグレードをやり直す必要があります。
  *** 拡張：ボリュームの仕様サイズは現在のサイズよりも小さくなります。これは、誰かがボリュームの縮小を要求しているようなものですが、実際にはLonghornは内部でそれを処理することを拒否します。ボリュームを回復するには、ユーザーはワークロードをスケールダウンし、拡張をやり直す必要があります。
 ** *注意*：ユーザーが問題のあるボリュームを復元する方法がわからない場合、最も簡単な方法は常にバックアップから新しいボリュームを復元することです。
* スナップショット後にLonghornシステムがアップグレードされた場合、新しい設定とノード設定の変更は消えます。ユーザーはアップグレードをやり直し、その後設定とノードの設定を再度修正する必要があります。
* スナップショット後にノードがLonghornシステムから削除された場合、そのノードは戻りませんが、削除されたノード上のポッドは復元されます。ユーザーは、これらのポッドが状態`Terminating`で停止してしまう可能性があるため、手動でクリーンアップする必要があります。
* スナップショット後にノードがLonghornシステムに追加された場合、Longhornはクラスターの復元後にそのノード上のすべての必要なワークロードを自動的に再起動する必要があります。ただし、ユーザーは、このノード上のすべての新しいレプリカやエンジンが復元後に消えてしまうことに注意してください。

== 参考資料

* 関連するGitHubの問題は https://github.com/longhorn/longhorn/issues/2228.です。このGitHubの投稿では、1人のユーザーがデータを含まない新しいクラスターにLonghornを復元する方法を提供しています。
