= 高速レプリカ再構築
:revdate: 2025-06-27
:page-revdate: {revdate}
:current-version: {page-component-version}

Longhornはスナップショットディスクファイルのチェックサムに基づいて、高速レプリカ再構築をサポートしています。

== 概要

従来のレプリカ再構築処理は、すべてのスナップショットディスクファイルを走査します。各データブロックについて、クライアント（正常なレプリカ）はローカルデータブロックをハッシュ化し、リモート側（再構築されたレプリカ）の対応するデータブロックのチェックサムを要求します。その後、クライアントは2つのチェックサムを比較して、データブロックをリモート側に送信し、データブロックを上書きする必要があるかどうかを判断します。したがって、これはIOおよび計算集約型のプロセスであり、特にボリュームが大きい場合やスナップショットファイルが多数含まれている場合にそうなります。

ユーザーが`snapshot-data-integrity`を`enabled`または`fast-check`に設定することでスナップショットデータ整合性チェック機能を有効にすると、変更タイムスタンプとスナップショットディスクファイルのチェックサムが記録されます。以下の2つの条件が満たされている限り、スナップショットディスクファイルの同期をスキップできます。

* スナップショットディスクファイルの変更タイムスタンプと記録された値が同じです。
* ローカルおよびリモートのスナップショットディスクファイルが同じチェックサムを持っています。

その結果、不必要な計算の数を減らすことで、全体の処理を加速し、システムパフォーマンスへの影響を軽減できます。

== 設定

=== グローバル設定

* fast-replica-rebuild-enabled +
+
この設定により、高速レプリカ再構築機能が有効になります。これはスナップショットディスクファイルのチェックサムに依存しているため、スナップショットデータ整合性を*enable*または*fast-check*に設定することが前提条件です。xref:data-integrity-recovery/snapshot-data-integrity-check.adoc[スナップショットデータ整合性チェック]を参照してください。
