= ボリューム回復
:revdate: 2025-06-27
:page-revdate: {revdate}
:current-version: {page-component-version}

Longhornは、さまざまな状況でボリューム機能を維持するための2つのメカニズムを提供します。

== 自動ワークロードポッド削除

この回復メカニズムは、設定xref:longhorn-system/settings.adoc#_automatically_delete_workload_pod_when_the_volume_is_detached_unexpectedly[_ボリュームが予期せず切り離されたときにワークロードポッドを自動的に削除する_]によって有効になります。

次のいずれかの状況が発生した場合、Longhornはコントローラー（たとえば、Deployment、StatefulSet、またはDaemonSet）によって管理されているワークロードポッドを自動的に削除しようとします。削除後、コントローラーはワークロードポッドを再起動し、Kubernetesがボリュームの再接続と再マウントを処理します。

. ボリュームが予期せず切り離された場合、これは https://github.com/longhorn/longhorn/issues/703[Kubernetesのアップグレード]、 https://github.com/longhorn/longhorn/issues/686[コンテナランタイムの再起動]、ネットワーク接続の問題、またはボリュームエンジンのクラッシュが原因である可能性があります。
. すべてのレプリカが故障した後、ボリュームは自動的に救出されます。これは、ネットワーク接続の問題が原因である可能性があります。Longhornは使用可能なレプリカを特定し、それらをボリュームに使用します。
. RWXボリュームを使用しているShare Managerポッドでエラーが発生しました。

Longhornがワークロードポッドを自動的に削除するのを防ぎたい場合は、Longhorn UIで設定xref:longhorn-system/settings.adoc#_automatically_delete_workload_pod_when_the_volume_is_detached_unexpectedly[_ボリュームが予期せず切り離されたときにワークロードポッドを自動的に削除する_]を無効にしてください。

Longhornはコントローラーのないポッドを削除しません。なぜなら、そのようなポッドは削除後に再起動できないからです。予期せず切り離されたボリュームを回復するには、コントローラーのないポッドを手動で削除して再起動する必要があります。

== 自動ボリューム再マウント

この回復メカニズムは、特定の設定によって制御されていません。

IOエラーが発生した場合、ボリュームの状態は読み取り専用に変更されることがあります。IOエラーは、以下のようなさまざまな問題によって引き起こされる可能性があります：

* ネットワーク切断：エンジンとレプリカ間の接続が中断されました。
* 高いディスク遅延：レプリカと対応するディスク間のデータ転送に著しい遅延があります。

Longhornは、ボリュームのグローバルマウントポイントの状態を10秒ごとに確認します。ボリュームのファイルシステムが読み取り専用に変更されると、Longhornはボリュームのデータエンジンにその状態を更新します。その後、Longhornはホスト上のグローバルマウントポイントを自動的に再マウントし、状態を読み書きに戻そうとします。再マウントが成功すると、ワークロードポッドは中断することなく機能し続けます。ただし、マウントポイントが書き込み保護され、Longhornがマウントポイントを再マウントできない場合は、ワークロードを手動で再作成して、再接続および再マウントを強制する必要があるかもしれません。

NOTE: このメカニズムは、いくつかの状況では機能しない可能性があります。たとえば、ボリュームのデータエンジンがクラッシュした場合、Longhornは自動的にボリュームを切り離し、再接続します。この場合、ファイルシステムは読み取り専用に変更されます。Longhornは読み取り専用モードを検出し、状態を更新しますが、<<_automatic_volume_remounting,自動ボリューム再マウント>>はデバイスが現在書き込み保護されているため、再び読み書きに戻すことはできません。この場合、<<_automatic_workload_pod_deletion,自動ワークロードポッド削除>>メカニズムに頼ることしかできません。これは、ワークロードポッドが再作成された後にボリュームの再マウントを可能にします。

== まとめ

<<_automatic_workload_pod_deletion,自動ワークロードポッド削除>>は、予期しない障害が発生したときにトリガーされます。コントローラーはワークロードポッドを削除し、その後再起動し、Kubernetesがボリュームの再接続と再マウントを処理します。このプロセスは、ワークロードに中断を引き起こす可能性があります。Longhornがワークロードポッドを自動的に削除しないようにしたい場合は、Longhorn UIで設定xref:longhorn-system/settings.adoc#_automatically_delete_workload_pod_when_the_volume_is_detached_unexpectedly[_ボリュームが予期せず切り離されたときにワークロードポッドを自動的に削除する_]を無効にしてください。

<<_automatic_volume_remounting,自動ボリューム再マウント>>は、ボリュームのファイルシステムが読み取り専用に変更されたときにトリガーされます。Longhornはホスト上のグローバルマウントポイントを再マウントし、状態を読み書きに戻します。
