= アップグレード時のインスタンスマネージャーポッド
:revdate: 2026-01-08
:page-revdate: {revdate}
:current-version: {page-component-version}

ライブアップグレード後、一部の*古いインスタンスマネージャーポッド*がまだ実行中であることに気付くかもしれません。これは予期される動作であり、*バグではありません*。

== なぜこれが起こるのか

{longhorn-product-name}は、ライブアップグレード中にインスタンスマネージャーポッドを管理するために次の戦略を使用します：

* 古いインスタンスマネージャーポッドは、エンジンまたはレプリカプロセスが実行されていないときに即座にクリーンアップされます。
* ボリュームの*ライブエンジンアップグレード*中：
** レプリカプロセスは、アップグレードされたエンジンイメージを使用して新しいインスタンスマネージャーポッドに再作成されます。
** I/Oを中断しないように、{longhorn-product-name}はボリュームが接続されている間、新しいインスタンスマネージャーポッドでアップグレードされたエンジンイメージを使用して新しいエンジンプロセスを開始することはできません。その代わりに、古いインスタンスマネージャーポッドは、ボリュームが切り離されるまで新しいエンジンプロセスのライフサイクルを管理し続けます。その結果、新しいエンジンプロセスは古いインスタンスマネージャーポッドで実行されます。

その結果、古いインスタンスマネージャーポッドは、アクティブなエンジンプロセスをホストしている限り、実行され続けます。ボリュームが切り離され、エンジンまたはレプリカプロセスが残っていない場合、{longhorn-product-name}は自動的に古いインスタンスマネージャーポッドをクリーンアップします。

== どのボリュームが古いインスタンスマネージャーポッドを使用しているかを確認する方法

どのボリュームがまだ古いインスタンスマネージャーポッドを使用しているかは、{longhorn-product-name} UIから確認できます：

* *ボリューム* > *名前* > *ボリュームの詳細* > *インスタンスマネージャー*に移動します。

== 古いインスタンスマネージャーポッドを完全にクリーンアップする方法

{longhorn-product-name}がすべての古いインスタンスマネージャーポッドをクリーンアップできるようにするには：

. まだ古いインスタンスマネージャーポッドを使用しているすべてのボリュームを切り離します。
. エンジンまたはレプリカプロセスが残っていない場合、{longhorn-product-name}は自動的に古いインスタンスマネージャーポッドを削除します。
