= SUSE® Storage System Sicherungen
:revdate: 2025-06-27
:page-revdate: {revdate}
:current-version: {page-component-version}

____
Frühere Versionen ermöglichten es Ihnen, das SUSE® Storage-System mit Drittanbieter-Tools wiederherzustellen.
____

* xref:snapshots-backups/system-backups/restore-to-cluster-using-rancher-snapshot.adoc[Wiederherstellung in einen Cluster, der Daten enthält, mithilfe des Rancher-Snapshots]
* xref:snapshots-backups/system-backups/restore-to-new-cluster-using-velero.adoc[Wiederherstellung in einen neuen Cluster mit Velero]

____
Aktuelle SUSE® Storage-Versionen beinhalten sofort einsatzbereite System-Sicherungs- und Wiederherstellungsfunktionen.

* SUSE® Storage benutzerdefinierte Ressourcen werden gesichert und in einer einzigen System-Sicherungsdatei gebündelt, die dann im Remote-Sicherungsziel gespeichert wird.
* Später können Sie eine System-Sicherung auswählen, um sie in einen neuen Cluster oder in einen bestehenden Cluster wiederherzustellen.
____

* xref:snapshots-backups/system-backups/create-system-backup.adoc[Sicherung des Longhorn-Systems]
* xref:snapshots-backups/system-backups/restore-system.adoc[Wiederherstellung des Longhorn-Systems]
